### ISSUE TITLE
Add ability to run amd64 binary on M1

### ISSUE THREAD

**Issue by lukepolo** [kubernetes/minikube#10243]
**Steps to reproduce the issue:** 
1. Install docker for m1
`https://docs.docker.com/docker-for-mac/apple-m1/`
2. Install Minikube 
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
sudo install minikube-darwin-amd64 /usr/local/bin/minikube
```
3. run minikube start

minikube start log
https://gist.github.com/lukepolo/af6c8402995002471d38d1833616ce6e

minikube logs
https://gist.github.com/lukepolo/525e7092b69bfe75263dbb018b297eb2

**Comment by afbjorklund** [comment]
Looks like a `kubeadm` (or docker) bug, on this shiny new platform:

```
I0123 17:52:46.144192   29153 ssh_runner.go:236] Start: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables"
| W0123 17:52:46.473914   29153 out.go:181] 💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by gchicoye** [comment]
Hi,
I'm facing the same issue

```
minikube v1.17.1 sur Darwin 11.1
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Utilisation du pilote docker basé sur le profil existant
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Préparation de Kubernetes v1.20.2 sur Docker 20.10.2...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped


💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:


😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by lukepolo** [comment]
with the newer version i get 


```
warning package.json: No license field
$ minikube start && minikube addons enable ingress && npm run apply
😄  minikube v1.17.1 on Darwin 11.1 (arm64)
✨  Automatically selected the hyperkit driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
❗  Startup with hyperkit driver failed, trying with alternate driver ssh: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
💀  Removed all traces of the "minikube" cluster.
👍  Starting control plane node minikube in cluster minikube
🤦  StartHost failed, but will try again: config: please provide an IP address
😿  Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address

❌  Exiting due to PR_HYPERKIT_CRASHED: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

error Command failed with exit code 60.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by afbjorklund** [comment]
I _think_ HyperKit crashed for the lack of an ISO, but it doesn't actually show that in the non-verbose log above.

If you want to avoid Docker and avoid HyperKit, you _could_ start a Linux (somehow) and then use "ssh" driver.
But that's more of a workaround, the long-term plan is that both KIC and ISO should work - also on ARM platform.

The automatic failover from "hyperkit" to "ssh" sounds more like a bug, that should definitely be a opt-in decision.

**Comment by medyagh** [comment]
@lukepolo do u happeng to be using it with rosetta ?

**Comment by spowelljr** [comment]
Copying @tstromberg's comment from a duplicate issue to centralize information. https://github.com/kubernetes/minikube/issues/10846#issuecomment-800771368

> The `qemu` message says to me 3 things:
> 
> * The user is probably using the `amd64` download of minikube on `arm64` (so it's running in rosetta)
> * minikube isn't aware of the possibility of the runtime architecture being different than the compile-time  architecture (GOOS), so it's maybe requesting the amd64 Docker images for kicbase? It shouldn't have a different architecture name, so that would be weird.
> * Docker's amd64 emulation via qemu has quirks to be worked out.

**Comment by lukepolo** [comment]
I was able to get it working with the new docker. Closing.

**Comment by spowelljr** [comment]
@gchicoye @orrymr @thetruechar @g-smaller

@lukepolo said he was able to get it working with the new version of Docker, could you try updating Docker to the latest version and see if it's fixed for you as well?

**Comment by orrymr** [comment]
@spowelljr 
No, I updated to Docker Desktop RC1. I get this error:

```
😄  minikube v1.18.1 on Darwin 11.0.1
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped


💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped


😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

I should note, that in my[ original issue](https://github.com/kubernetes/minikube/issues/10846), I'd installed the arm64 version of Minikube. I have subsequently uninstalled that. The error above I got after installing Minikube amd64:

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64\n
sudo install minikube-darwin-amd64 /usr/local/bin/minikube
```

What is strange to me, is that the error above references Docker 20.10.3. However, docker --version yields the following: Docker version 20.10.5, build 55c4c88
🤷

**Comment by spowelljr** [comment]
@orrymr Is it possible you have two versions of minikube installed?

**Comment by orrymr** [comment]
@spowelljr I've installed and uninstalled Minikube a bunch of times (both using brew and by curl'ing it) so it's definitely possible. 
I thought I'd diligently cleaned up after myself, but possibly not. How would I tell if there are multiple versions installed?
`$ which minikube` points to `/usr/local/bin/minikube` - if that helps?

**Comment by spowelljr** [comment]
@orrymr Sorry, I meant to say Docker, accidentally typed minikube, my mistake. Because if minikube is detecting a diff Docker version seem like it might be pointing to another instance that might be existing.

**Comment by orrymr** [comment]
@spowelljr 
No worries :)

`$ minikube docker-env `
reveals the following:
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:61079"
export DOCKER_CERT_PATH="/Users/orrymr/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

**# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)**
```

Which makes me think that my shell is running a different version of docker-daemon to minikube. I don't know how to verify this, though.

Not really sure what else to do, but the problem persists.

**Comment by orrymr** [comment]
If this helps, [here](https://gist.github.com/orrymr/1158bd18361b3e1998736a8d221dc5ad) is the output of 

`$ minikube start --alsologtostderr`

**Comment by spowelljr** [comment]
Re-opening due to others not being able to get it to work.

**Comment by NatureLingRan** [comment]
I execute  `rm -rf ~/Library/Containers/com.docker.docker`

Solve the problem successfully

**Comment by medyagh** [comment]
@ilya-zuyev investigate if this needs to be added to our solution messages

**Comment by sharifelgamal** [comment]
We now display a user-friendly error message if they run an amd64 binary on arm64, we're working on supporting running it.

**Comment by peripurnama** [comment]
is there a way to enable ingress on mac m1 ?
