### ISSUE TITLE
"setting autostart for network default" fails linux/kvm2/libvirt

### ISSUE THREAD

**Issue by gdamjan** [kubernetes/minikube#10297]
**Steps to reproduce the issue:** 

1. libvirt 7.0.0
2. minikube delete
3. minikube start --interactive=true --container-runtime=cri-o

**Full output of failed command:** 

```
😄  minikube v1.16.0 on Arch 
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: setting autostart for network default: virError(Code=55, Domain=19, Message='Requested operation is not valid: cannot set autostart for transient network')
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: setting autostart for network default: virError(Code=55, Domain=19, Message='Requested operation is not valid: cannot set autostart for transient network')

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: setting autostart for network default: virError(Code=55, Domain=19, Message='Requested operation is not valid: cannot set autostart for transient network')

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

** Some additional info **
the `default` network in *my* libvirt installation is a transient network bridge, i.e. it's defined outside of libvirt and "imported" into it. Even if I try to set it to "autostart" with libvirt tools, libvirt complains that it's not possible:
```
Error changing network settings: Requested operation is not valid: cannot set autostart for transient network

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/hostnets.py", line 328, in _net_apply
    net.set_autostart(auto)
  File "/usr/share/virt-manager/virtManager/object/network.py", line 89, in set_autostart
    self._backend.setAutostart(value)
  File "/usr/lib/python3.9/site-packages/libvirt.py", line 3241, in setAutostart
    if ret == -1: raise libvirtError ('virNetworkSetAutostart() failed', net=self)
libvirt.libvirtError: Requested operation is not valid: cannot set autostart for transient network
```
… so maybe minikube shouldn't try to configure the "default" network in libvirt when it is working perfectly fine?

**Comment by afbjorklund** [comment]
Currently it is not possible to "opt-out" of this, it is done for both default network and private network.

Having a toggle for it could work.

**Comment by gdamjan** [comment]
ok, I'm gonna take a look at it.

 what would be the most similar option that does something like this?

**Comment by afbjorklund** [comment]
> what would be the most similar option that does something like this?

Some kind of mix between kvm-network and kvm-hidden perhaps
