### ISSUE TITLE
0.16.0, 0.17.1 fail to start

### ISSUE THREAD

**Issue by ash2k** [kubernetes/minikube#1090]
**Minikube version** (use `minikube version`):
`minikube version: v0.16.0`

**Environment**:
- **OS** (e.g. from /etc/os-release):
macOS 10.12.3
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
`xhyve`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`):
```
cat ~/.minikube/machines/minikube/config.json | grep iso
        "Boot2DockerURL": "file:///Users/ash2k/.minikube/cache/iso/minikube-v1.0.2.iso",
```
- **Install tools**:
`brew cask install minikube`
- **Others**:

**What happened**:
`minikube start --vm-driver=xhyve` starts the cluster but it crashes and restarts in a loop. REST API is up and down. Please see the logs attached - there are some stacktraces with SIGSEGVs/panics.

**What you expected to happen**:
It should work :)

**How to reproduce it** (as minimally and precisely as possible):
I don't know, I had 0.15.0 installed then uninstalled it via `brew cask uninstall minikube`, then installed 0.16.0 and it cannot start properly.

**Anything else do we need to know**:
[minikube logs.txt](https://github.com/kubernetes/minikube/files/752281/minikube.logs.txt)

**Comment by ash2k** [comment]
It works after I did a `minikube delete` and deleted `~/.minikube`. But those stacktraces indicate a bug somewhere which someone may need to look into.

**Comment by ash2k** [comment]
Well, it stopped working after I stopped it and later started again. Restart does not help.
```
Feb 10 09:26:42 minikube localkube[3151]: I0210 09:26:42.391114    3151 replication_controller.go:219] Starting RC Manager
Feb 10 09:26:42 minikube localkube[3151]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 10 09:26:42 minikube localkube[3151]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb3b16d]
Feb 10 09:26:42 minikube localkube[3151]: goroutine 3518 [running]:
Feb 10 09:26:42 minikube localkube[3151]: panic(0x2d579c0, 0xc420016030)
Feb 10 09:26:42 minikube localkube[3151]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 10 09:26:42 minikube localkube[3151]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc4200fa910, 0x0, 0x0, 0x0, 0xc425597c1c, 0x2)
Feb 10 09:26:42 minikube localkube[3151]:         /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:313 +0x24d
Feb 10 09:26:42 minikube localkube[3151]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper-fm(0x0, 0x0, 0x0, 0x0, 0x0)
Feb 10 09:26:42 minikube localkube[3151]:         /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:106 +0x48
Feb 10 09:26:42 minikube localkube[3151]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0xc420217400, 0xc4228a6340, 0x5aa7c20, 0xc4228a6340, 0x5aa7c20, 0xc4228a6340, 0xc42519e300, 0x5aa3a60, 0xc4227811c0, 0x2e74636361757063, ...)
Feb 10 09:26:42 minikube localkube[3151]:         /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:367 +0x1996
Feb 10 09:26:42 minikube localkube[3151]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2(0xc42519e300)
Feb 10 09:26:42 minikube localkube[3151]:         /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0xc4
Feb 10 09:26:42 minikube localkube[3151]: created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
Feb 10 09:26:42 minikube localkube[3151]:         /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
Feb 10 09:26:42 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 10 09:26:42 minikube systemd[1]: localkube.service: Unit entered failed state.
Feb 10 09:26:42 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
Feb 10 09:26:45 minikube systemd[1]: localkube.service: Service hold-off time over, scheduling restart.
Feb 10 09:26:45 minikube systemd[1]: Stopped Localkube.
```
[logs2.txt](https://github.com/kubernetes/minikube/files/766308/logs2.txt)

**Comment by r2d4** [comment]
I haven't seen this issue before.  

Are you still seeing these errors?  If so, if you could provide some steps to reproduce, that would help debug.

**Comment by ash2k** [comment]
I'm using minikube from time to time and it happened to me twice. I described both times above and unfortunately I cannot provide more information, sorry.

**Comment by ash2k** [comment]
minikube version: v0.17.1
```
Mar 10 04:38:29 minikube localkube[6130]: I0310 04:38:29.225590    6130 event.go:217] Event(api.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"058a3ee0-045d-11e7-b4a1-da027787b657", APIVersion:"v1", ResourceVersion:"40892", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube became leader
Mar 10 04:38:29 minikube localkube[6130]: I0310 04:38:29.227438    6130 replication_controller.go:219] Starting RC Manager
Mar 10 04:38:29 minikube localkube[6130]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 10 04:38:29 minikube localkube[6130]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xdecd8d]
Mar 10 04:38:29 minikube localkube[6130]: goroutine 1551 [running]:
Mar 10 04:38:29 minikube localkube[6130]: panic(0x3592cc0, 0xc420018030)
Mar 10 04:38:29 minikube localkube[6130]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc420158910, 0x0, 0x0, 0x0, 0xc42106330c, 0x2)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:313 +0x24d
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper-fm(0x0, 0x0, 0x0, 0x0, 0x0)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:106 +0x48
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0xc420422a00, 0xc420ee4000, 0x675a7c0, 0xc420ee4000, 0x675a7c0, 0xc420ee4000, 0xc421cd5f20, 0x6756300, 0xc420d52540, 0x3b81477, ...)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:367 +0x1996
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2(0xc421cd5f20)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0xc4
Mar 10 04:38:29 minikube localkube[6130]: created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Unit entered failed state.
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
Mar 10 04:38:32 minikube systemd[1]: localkube.service: Service hold-off time over, scheduling restart.
Mar 10 04:38:32 minikube systemd[1]: Stopped Localkube.
```

I fix this with minikube stop && minikube delete && rm -rf ~/.minikube and then starting it again. Otherwise stop/start does not help. I just rebooted my machine, started minikube and this happened again. I'm doing some experiments with TPRs - can it be the cause?

**Comment by donspaulding** [comment]
@ash2k does your cluster have any ThirdPartyResources added to it?

`kubectl get thirdpartyresource --all-namespaces`

**Comment by r2d4** [comment]
Yeah this is the same issue as #1252.  We should probably close one and track it there

**Comment by ash2k** [comment]
@donspaulding, yes, I mentioned it in one of the comments above :)

**Comment by r2d4** [comment]
Closing this and tracking it in #1252
