### ISSUE TITLE
`minikube start` with `podman` driver fails with `index ouf range` error

### ISSUE THREAD

**Issue by oliversalzburg** [kubernetes/minikube#12489]
**Steps to reproduce the issue:** 

1. `minikube start --driver=podman --container-runtime=cri-o`

I'm running this in a WSL2 environment.

I found #10088 and #10110, which seemed to relate to the same issue, but it seems like this should no longer be a problem with the version I'm using.

I see the `Error downloading kic artifacts:  not yet implemented` error, but also couldn't make sense of either the referenced issue #8426 or other tickets mentioning this error.

**Full output of failed command if not `minikube start`:**
<details>
I0916 18:43:31.844826    4893 out.go:298] Setting OutFile to fd 1 ...
I0916 18:43:31.845562    4893 out.go:311] Setting ErrFile to fd 2...
I0916 18:43:31.845702    4893 root.go:313] Updating PATH: /home/oliver/.minikube/bin
I0916 18:43:31.846103    4893 out.go:305] Setting JSON to false
I0916 18:43:31.887752    4893 start.go:111] hostinfo: {"hostname":"oliver-home","uptime":99900,"bootTime":1631710712,"procs":8,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"11.0","kernelVersion":"5.10.16.3-microsoft-standard-WSL2","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"51f357b8-28e6-46fc-889c-fee60effb53c"}
I0916 18:43:31.887932    4893 start.go:121] virtualization:
I0916 18:43:31.892046    4893 out.go:177] 😄  minikube v1.23.0 on Debian 11.0
😄  minikube v1.23.0 on Debian 11.0
I0916 18:43:31.892288    4893 notify.go:169] Checking for updates...
I0916 18:43:31.892543    4893 driver.go:343] Setting default libvirt URI to qemu:///system
I0916 18:43:32.074689    4893 podman.go:121] podman version: 3.0.1
I0916 18:43:32.078126    4893 out.go:177] ✨  Using the podman driver based on user configuration
✨  Using the podman driver based on user configuration
I0916 18:43:32.078229    4893 start.go:278] selected driver: podman
I0916 18:43:32.078274    4893 start.go:751] validating driver "podman" against <nil>
I0916 18:43:32.078315    4893 start.go:762] status for podman: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0916 18:43:32.101088    4893 cli_runner.go:115] Run: sudo -n podman system info --format json
I0916 18:43:32.305039    4893 info.go:285] podman info: {Host:{BuildahVersion:1.19.6 CgroupVersion:v1 Conmon:{Package:conmon: /usr/bin/conmon Path:/usr/bin/conmon Version:conmon version 2.0.25, commit: unknown} Distribution:{Distribution:debian Version:11} MemFree:29329051648 MemTotal:67332890624 OCIRuntime:{Name:crun Package:crun: /usr/bin/crun Path:/usr/bin/crun Version:crun version 0.17
commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL} SwapFree:17179869184 SwapTotal:17179869184 Arch:amd64 Cpus:12 Eventlogger:journald Hostname:oliver-home Kernel:5.10.16.3-microsoft-standard-WSL2 Os:linux Rootless:false Uptime:27h 44m 59.46s (Approximately 1.12 days)} Registries:{Search:[registry.access.redhat.com docker.io]} Store:{ConfigFile:/etc/containers/storage.conf ContainerStore:{Number:0} GraphDriverName:overlay GraphOptions:{} GraphRoot:/var/lib/containers/storage GraphStatus:{BackingFilesystem:extfs NativeOverlayDiff:true SupportsDType:true UsingMetacopy:false} ImageStore:{Number:0} RunRoot:/run/containers/storage VolumePath:/var/lib/containers/storage/volumes}}
I0916 18:43:32.305183    4893 start_flags.go:264] no existing cluster config was found, will generate one from the flags
I0916 18:43:32.305734    4893 start_flags.go:345] Using suggested 16000MB memory alloc based on sys=64213MB, container=64213MB
I0916 18:43:32.305909    4893 start_flags.go:719] Wait components to verify : map[apiserver:true system_pods:true]
I0916 18:43:32.305990    4893 cni.go:93] Creating CNI manager for ""
I0916 18:43:32.306046    4893 cni.go:160] "podman" driver + crio runtime found, recommending kindnet
I0916 18:43:32.306096    4893 start_flags.go:273] Found "CNI" CNI - setting NetworkPlugin=cni
I0916 18:43:32.306153    4893 start_flags.go:278] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c Memory:16000 CPUs:2 DiskSize:20000 VMDriver: Driver:podman HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:crio CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0}
I0916 18:43:32.312482    4893 out.go:177] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0916 18:43:32.312589    4893 cache.go:117] Beginning downloading kic base image for podman with crio
I0916 18:43:32.315496    4893 out.go:177] 🚜  Pulling base image ...
🚜  Pulling base image ...
I0916 18:43:32.315676    4893 preload.go:131] Checking if preload exists for k8s version v1.22.1 and runtime crio
I0916 18:43:32.315724    4893 preload.go:147] Found local preload: /home/oliver/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v12-v1.22.1-cri-o-overlay-amd64.tar.lz4
I0916 18:43:32.315796    4893 cache.go:56] Caching tarball of preloaded images
I0916 18:43:32.315727    4893 cache.go:145] Downloading gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c to local cache
I0916 18:43:32.316131    4893 image.go:59] Checking for gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c in local cache directory
I0916 18:43:32.316187    4893 image.go:62] Found gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c in local cache directory, skipping pull
I0916 18:43:32.316244    4893 image.go:103] gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c exists in cache, skipping pull
I0916 18:43:32.316287    4893 cache.go:148] successfully saved gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c as a tarball
I0916 18:43:32.316310    4893 preload.go:173] Found /home/oliver/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v12-v1.22.1-cri-o-overlay-amd64.tar.lz4 in cache, skipping download
I0916 18:43:32.316338    4893 cache.go:59] Finished verifying existence of preloaded tar for  v1.22.1 on crio
I0916 18:43:32.316650    4893 profile.go:148] Saving config to /home/oliver/.minikube/profiles/minikube/config.json ...
I0916 18:43:32.316710    4893 lock.go:36] WriteFile acquiring /home/oliver/.minikube/profiles/minikube/config.json: {Name:mk9c9b67d186b8ce828ad82221b7328216510723 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
E0916 18:43:32.316908    4893 cache.go:200] Error downloading kic artifacts:  not yet implemented, see issue #8426
I0916 18:43:32.316950    4893 cache.go:205] Successfully downloaded all kic artifacts
I0916 18:43:32.316967    4893 start.go:313] acquiring machines lock for minikube: {Name:mk67045e7129aa12330db0d059e8f4c0c90f5d6f Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0916 18:43:32.317084    4893 start.go:317] acquired machines lock for "minikube" in 65.6µs
I0916 18:43:32.317146    4893 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.26@sha256:d4aa14fbdc3a28a60632c24af937329ec787b02c89983c6f5498d346860a848c Memory:16000 CPUs:2 DiskSize:20000 VMDriver: Driver:podman HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:crio CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.1 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0} &{Name: IP: Port:8443 KubernetesVersion:v1.22.1 ControlPlane:true Worker:true}
I0916 18:43:32.317214    4893 start.go:126] createHost starting for "" (driver="podman")
I0916 18:43:32.320536    4893 out.go:204] 🔥  Creating podman container (CPUs=2, Memory=16000MB) ...
🔥  Creating podman container (CPUs=2, Memory=16000MB) ...| I0916 18:43:32.320873    4893 start.go:160] libmachine.API.Create for "minikube" (driver="podman")
I0916 18:43:32.320974    4893 client.go:168] LocalClient.Create starting
I0916 18:43:32.321086    4893 main.go:130] libmachine: Reading certificate data from /home/oliver/.minikube/certs/ca.pem
I0916 18:43:32.321188    4893 main.go:130] libmachine: Decoding PEM data...
I0916 18:43:32.321280    4893 main.go:130] libmachine: Parsing certificate...
I0916 18:43:32.321397    4893 main.go:130] libmachine: Reading certificate data from /home/oliver/.minikube/certs/cert.pem
I0916 18:43:32.321476    4893 main.go:130] libmachine: Decoding PEM data...
I0916 18:43:32.321564    4893 main.go:130] libmachine: Parsing certificate...
I0916 18:43:32.345891    4893 cli_runner.go:115] Run: sudo -n podman network inspect minikube --format "{{range .plugins}}{{if eq .type "bridge"}}{{(index (index .ipam.ranges 0) 0).subnet}},{{(index (index .ipam.ranges 0) 0).gateway}}{{end}}{{end}}"
/ W0916 18:43:32.504705    4893 cli_runner.go:162] sudo -n podman network inspect minikube --format "{{range .plugins}}{{if eq .type "bridge"}}{{(index (index .ipam.ranges 0) 0).subnet}},{{(index (index .ipam.ranges 0) 0).gateway}}{{end}}{{end}}" returned with exit code 125
I0916 18:43:32.516988    4893 network_create.go:255] running [podman network inspect minikube] to gather additional debugging logs...
- I0916 18:43:32.528478    4893 cli_runner.go:115] Run: sudo -n podman network inspect minikube
\ W0916 18:43:32.674624    4893 cli_runner.go:162] sudo -n podman network inspect minikube returned with exit code 125
I0916 18:43:32.674689    4893 network_create.go:258] error running [sudo -n podman network inspect minikube]: sudo -n podman network inspect minikube: exit status 125
stdout:
[]

stderr:
Error: error inspecting object: no such network minikube
I0916 18:43:32.674758    4893 network_create.go:260] output of [sudo -n podman network inspect minikube]: -- stdout --
[]

-- /stdout --
** stderr **
Error: error inspecting object: no such network minikube

** /stderr **
I0916 18:43:32.696502    4893 cli_runner.go:115] Run: sudo -n podman network inspect podman --format "{{range .plugins}}{{if eq .type "bridge"}}{{(index (index .ipam.ranges 0) 0).subnet}},{{(index (index .ipam.ranges 0) 0).gateway}}{{end}}{{end}}"
/ I0916 18:43:32.864669    4893 client.go:171] LocalClient.Create took 543.6304ms
panic: runtime error: index out of range [1] with length 1

goroutine 193 [running]:
k8s.io/minikube/pkg/drivers/kic/oci.podmanNetworkInspect({0x1e8561f, 0x6})
        /app/pkg/drivers/kic/oci/network_create.go:242 +0x7f0
k8s.io/minikube/pkg/drivers/kic/oci.containerNetworkInspect({0xc0011ac440, 0x33f2718}, {0x1e8561f, 0xc0011c97c0})
        /app/pkg/drivers/kic/oci/network_create.go:161 +0x19e
k8s.io/minikube/pkg/drivers/kic/oci.CreateNetwork({0xc0011ac440, 0x6}, {0xc0011ac410, 0x1e808d6})
        /app/pkg/drivers/kic/oci/network_create.go:73 +0x1ed
k8s.io/minikube/pkg/drivers/kic.(*Driver).Create(0xc0011a6140)
        /app/pkg/drivers/kic/kic.go:95 +0x496
k8s.io/minikube/pkg/minikube/machine.(*LocalClient).Create(0xc000dac6c0, 0xc000dd4cc0)
        /app/pkg/minikube/machine/client.go:242 +0x5f2
k8s.io/minikube/pkg/minikube/machine.timedCreateHost.func2()
        /app/pkg/minikube/machine/start.go:193 +0x38
created by k8s.io/minikube/pkg/minikube/machine.timedCreateHost
        /app/pkg/minikube/machine/start.go:192 +0x17d
</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! 
Curious what is the podman version installed on the WSL2 ?

Also please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:


```
$ minikube logs --file=logs.txt
```` 

/triage needs-information
/kind support

**Comment by oliversalzburg** [comment]
`podman --version` prints 3.0.1. I attached the `logs.txt` to the original post. The output it produces made me assume no logs would be produced until a cluster is started. But it's there now.

**Comment by medyagh** [comment]
@oliversalzburg  thats odd I dont see that error in the file you attached, I am curious would this help if you purge minikube?

```
minikube delete --all --purge
```

**Comment by medyagh** [comment]
in the Audit there is no minikube start, I am curious do u Ctrl+C the minikube start or is it just hangning ?


```

==> Audit <==
|---------|------|----------|--------|---------|--------------------------------|--------------------------------|
| Command | Args | Profile  |  User  | Version |           Start Time           |            End Time            |
|---------|------|----------|--------|---------|--------------------------------|--------------------------------|
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:17:49 CEST | Thu, 16 Sep 2021 18:17:53 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:22:56 CEST | Thu, 16 Sep 2021 18:23:00 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:32:20 CEST | Thu, 16 Sep 2021 18:32:21 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:34:47 CEST | Thu, 16 Sep 2021 18:34:52 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:37:23 CEST | Thu, 16 Sep 2021 18:37:27 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 18:43:20 CEST | Thu, 16 Sep 2021 18:43:24 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 19:04:24 CEST | Thu, 16 Sep 2021 19:04:28 CEST |
| delete  |      | minikube | oliver | v1.23.0 | Thu, 16 Sep 2021 19:05:48 CEST | Thu, 16 Sep 2021 19:05:49 CEST |
|---------|------|----------|--------|---------|--------------------------------|--------------------------------|

```

**Comment by oliversalzburg** [comment]
I didn't Ctrl+C any of the processes I was running yesterday. I just went through several iterations to see if I can find my mistake.

I now ran `minikube delete --all --purge` first, then ran `minikube start --driver=podman --container-runtime=cri-o` again. This resulted in the original error behavior.

I then ran `minikube logs --file=logs.txt` and got [logs.txt](https://github.com/kubernetes/minikube/files/7183718/logs.txt). The output of the command noted to also attach the additional file [minikube_logs_a15606cd8c429498f482f0869e7ab4a2ed08e63b_0.log](https://github.com/kubernetes/minikube/files/7183726/minikube_logs_a15606cd8c429498f482f0869e7ab4a2ed08e63b_0.log)

**Comment by oliversalzburg** [comment]
@medyagh Any idea what else I should be looking into?

**Comment by spowelljr** [comment]
Thanks for the logs @oliversalzburg, I've found the bug and will push up a PR soon.

**Comment by oliversalzburg** [comment]
@spowelljr Is #12382 maybe the same as this one?
