### ISSUE TITLE
Cannot start minikube on mac, localkube fails to start

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/minikube#1376]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Minikube version** (use `minikube version`):
 minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX 10.12.4 (16E195)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
```
$ cat ~/.minikube/machines/minikube/config.json | grep -i ISO
"Boot2DockerURL": "file:///Users/mehdy/.minikube/cache/iso/minikube-v1.0.6.iso",
$ minikube ssh cat /etc/VERSION
cat: can't open '/etc/VERSION': No such file or directory
E0418 10:34:33.678661   23252 ssh.go:44] Error attempting to ssh/run-ssh-command: exit status 1
```
- **Install tools**: Docker, virtualbox
- **Others**:

**What happened**:
minikube start does not fail but kubectl get pods doesn't work. Logs show localkube cannot start

**What you expected to happen**:
localkube start. kubectl connect to minikube cluster.

**How to reproduce it** (as minimally and precisely as possible):

```
$HOME$ minikube status
minikubeVM: Stopped
localkube: N/A
$HOME$ minikube start --kubernetes-version v1.6.0
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
$HOME$ minikube status
minikubeVM: Running
localkube: Stopped
$HOME$ kubectl get pods
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
$HOME$
```

**Anything else do we need to know**:

Logs:

```
...
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.128065    4352 event.go:217] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-scheduler", UID:"98da9f27-1fbe-11e7-9dcd-08002714b4b4", APIVersion:"v1", ResourceVersion:"477838", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube became leader
Apr 18 17:32:01 minikube localkube[4352]: E0418 17:32:01.158058    4352 certificates.go:38] Failed to start certificate controller: open /etc/kubernetes/ca/ca.pem: no such file or directory
Apr 18 17:32:01 minikube localkube[4352]: W0418 17:32:01.158098    4352 controllermanager.go:434] Skipping "certificatesigningrequests"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.158641    4352 controllermanager.go:437] Started "endpoint"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.159501    4352 controllermanager.go:437] Started "daemonset"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.159853    4352 controllermanager.go:437] Started "cronjob"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.160482    4352 controllermanager.go:437] Started "job"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.161688    4352 daemoncontroller.go:199] Starting Daemon Sets controller manager
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.161775    4352 cronjob_controller.go:95] Starting CronJob Manager
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.162364    4352 controllermanager.go:437] Started "disruption"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.162763    4352 controllermanager.go:437] Started "ttl"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.163039    4352 disruption.go:269] Starting disruption controller
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.163204    4352 ttlcontroller.go:117] Starting TTL controller
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.163630    4352 controllermanager.go:437] Started "replicationcontroller"
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.163784    4352 replication_controller.go:150] Starting RC Manager
Apr 18 17:32:01 minikube localkube[4352]: I0418 17:32:01.164540    4352 controllermanager.go:437] Started "podgc"
Apr 18 17:32:01 minikube localkube[4352]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 17:32:01 minikube localkube[4352]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x179d51d]
Apr 18 17:32:01 minikube localkube[4352]: goroutine 1854 [running]:
Apr 18 17:32:01 minikube localkube[4352]: panic(0x37d62a0, 0xc420016030)
Apr 18 17:32:01 minikube localkube[4352]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 18 17:32:01 minikube localkube[4352]: k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc420324eb0, 0x0, 0x0, 0x0, 0x20, 0x1100000009)
Apr 18 17:32:01 minikube localkube[4352]:         /go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/apimachinery/registered/registered.go:286 +0x24d
Apr 18 17:32:01 minikube localkube[4352]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.startNamespaceController(0x68ddca0, 0xc423b648c0, 0x68e8cc0, 0xc4245b9c80, 0x0, 0x0, 0x0, 0x0, 0xc420483bd0, 0x1, ...)
Apr 18 17:32:01 minikube localkube[4352]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:103 +0x5d
Apr 18 17:32:01 minikube localkube[4352]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0xc4245b8f90, 0xc4215d0840, 0x68ddca0, 0xc423b648c0, 0x68ddca0, 0xc423b648c0, 0xc423222480, 0x0, 0x10002)
Apr 18 17:32:01 minikube localkube[4352]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:428 +0x5b3
Apr 18 17:32:01 minikube localkube[4352]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2(0xc423222480)
Apr 18 17:32:01 minikube localkube[4352]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0xc6
Apr 18 17:32:01 minikube localkube[4352]: created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
Apr 18 17:32:01 minikube localkube[4352]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
Apr 18 17:32:01 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 18 17:32:01 minikube systemd[1]: localkube.service: Unit entered failed state.
Apr 18 17:32:01 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
```

**Comment by mbohlool** [comment]
This fixed it:

```bash
$HOME$ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
$HOME$ rm -rf ~/.minikube
$HOME$ minikube start
Starting local Kubernetes cluster...
Starting VM...
Downloading Minikube ISO
 89.51 MB / 89.51 MB [==============================================] 100.00% 0s
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
$HOME$ kubectl get pods
No resources found.
```

Should have been an old ISO issue.
