### ISSUE TITLE
minikube service --url <service> panics when you try to get a ClusterIP service

### ISSUE THREAD

**Issue by jak42** [kubernetes/minikube#13839]
### What Happened?

The trace below says it all.

james@volttron-mod-installed:\~/Documents/kube-volttron$ kubectl get service
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP              9d
vcentral     ClusterIP   10.99.195.5     <none>        8443/TCP,22916/TCP   9d
vremote      ClusterIP   10.105.67.178   <none>        8443/TCP,22916/TCP   9d
james@volttron-mod-installed:~/Documents/kube-volttron$ minikube service --url vcentral
😿  service default/vcentral has no node port
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x369af20, {0xc000211d20, 0x1, 0x2})
	/app/cmd/minikube/cmd/service.go:138 +0x609
github.com/spf13/cobra.(*Command).execute(0x369af20, {0xc000211d00, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x369aa20)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:157 +0xa31
main.main()
	/app/cmd/minikube/main.go:86 +0x255

### Attach the log file

See the above.

### Operating System

Ubuntu

### Driver

Docker

**Comment by zhan9san** [comment]
Hi @jak42 

This is a known issue and fixed in [#13736 ](https://github.com/kubernetes/minikube/issues/13736#issuecomment-1063470210)

You can try the minikube binary in comment
