### ISSUE TITLE
Minikube rejects user connection, Localkube fails to start ("The connection to the server was refused - did you specify the right host or port?")

### ISSUE THREAD

**Issue by jflory7** [kubernetes/minikube#1698]
## Metadata

**BUG REPORT or FEATURE REQUEST?** (choose one): _Bug report_
**Minikube version** (use `minikube version`): _v0.20.0_
**Environment**:
- **OS**: `Red Hat Enterprise Linux Workstation 7.3 (Maipo)`
- **VM Driver**: `virtualbox`
- **ISO version**: `v0.21.0`

## What happened

**Localkube fails to start, preventing access to the Minikube VM.**

In short, I start Minikube with `minikube start` and it starts up fine without error. However, any time that I try to interact with the local cluster, I receive this error:

```
$ kubectl cluster-info 
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
```

Using `kubectl`, I am unable to do anything to interact with the local cluster at all. This is similar to #1381, #1498, #1546, etc. However, when I checked the logs, I saw that the `localkube.service` failed to start. I don't understand how or why it failed, but it seems like this is partially to blame for the inability to interact with Minikube.

#### Disclaimer

I am behind a firewall and using a custom ISO file. However, my ISO only includes a custom `resolv.conf` and added SSL certificates to `/etc/ssl/` and `/etc/ssl/certs`. The ISO was built with the last upstream commit being 6f5972f9b590c03241c986df5630d85e07a95813.

## Expected behavior

1. `minikube start`
2. `kubectl cluster-info`

> Kubernetes master is running at https://192.168.99.100:8443
> To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

## How to reproduce

1. `minikube start`
2. `kubectl cluster-info`

> The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?

3. `minikube ssh`
4. `/usr/local/bin/localkube --dns-domain=cluster.local --node-ip=192.168.99.100 --generate-certs=false --logtostderr=true --enable-dns=false`
5. [Error stacktrace](https://paste.fedoraproject.org/paste/mSYHM3HVaYvpV7XToP-lBg)

## Other information

This is a little shorter than the full stacktrace above.

```
$ systemctl status -l localkube
● localkube.service - Localkube
   Loaded: loaded (/lib/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-07-14 17:50:34 UTC; 1s ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
  Process: 20625 ExecStart=/usr/local/bin/localkube --dns-domain=cluster.local --node-ip=192.168.99.100 --generate-certs=false --logtostderr=true --enable-dns=false (code=exited, status=2)
 Main PID: 20625 (code=exited, status=2)
      CPU: 346ms

Jul 14 17:50:34 minikube localkube[20625]: net.lookupIP(0x68e6780, 0xc421a65a40, 0xc421aa73c8, 0x9, 0xc42000d740, 0x0, 0x0, 0xc42154b698, 0x6c5cae)
Jul 14 17:50:34 minikube localkube[20625]:         /usr/local/go/src/net/lookup_unix.go:70 +0xf9
Jul 14 17:50:34 minikube localkube[20625]: net.glob..func11(0x68e6780, 0xc421a65a40, 0x4b917c8, 0xc421aa73c8, 0x9, 0xc421c07900, 0x0, 0xc42000d740, 0xc4203eb900, 0x3b9aca00)
Jul 14 17:50:34 minikube localkube[20625]:         /usr/local/go/src/net/hook.go:19 +0x52
Jul 14 17:50:34 minikube localkube[20625]: net.lookupIPContext.func1(0xc42154b788, 0x627d88, 0xc420db3590, 0x68e6740)
Jul 14 17:50:34 minikube localkube[20625]:         /usr/local/go/src/net/lookup.go:119 +0x5c
Jul 14 17:50:34 minikube localkube[20625]: internal/singleflight.(*Group).doCall(0x6b0ece0, 0xc421a86f50, 0xc421aa73c8, 0x9, 0xc421a0f0b0)
Jul 14 17:50:34 minikube localkube[20625]:         /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c
Jul 14 17:50:34 minikube localkube[20625]: created by internal/singleflight.(*Group).DoChan
Jul 14 17:50:34 minikube localkube[20625]:         /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x339
```

…and…

```
$ journalctl -lu localkube
-- Logs begin at Fri 2017-07-14 17:45:04 UTC, end at Fri 2017-07-14 17:51:25 UTC. --
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).wait(0xc4216e8ae0, 0x72, 0xc420e22e78, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).waitRead(0xc4216e8ae0, 0x68c2940, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jul 14 17:45:04 minikube localkube[15262]: net.(*netFD).Read(0xc4216e8a80, 0xc4217833c2, 0x1, 0x1, 0x0, 0x68c2940, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_unix.go:243 +0x1a1
Jul 14 17:45:04 minikube localkube[15262]: net.(*conn).Read(0xc420fef468, 0xc4217833c2, 0x1, 0x1, 0x0, 0x0, 0x0)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/net.go:173 +0x70
Jul 14 17:45:04 minikube localkube[15262]: net/http.(*connReader).closeNotifyAwaitActivityRead(0xc420467040, 0xc42180f020, 0xc4218284c0)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/http/server.go:602 +0x71
Jul 14 17:45:04 minikube localkube[15262]: created by net/http.(*connReader).startBackgroundRead
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/http/server.go:597 +0x98
Jul 14 17:45:04 minikube localkube[15262]: goroutine 623 [IO wait]:
Jul 14 17:45:04 minikube localkube[15262]: net.runtime_pollWait(0x7f440420cce0, 0x72, 0x43)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).wait(0xc4216e8920, 0x72, 0xc4213ef678, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).waitRead(0xc4216e8920, 0x68c2940, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jul 14 17:45:04 minikube localkube[15262]: net.(*netFD).Read(0xc4216e88c0, 0xc421783662, 0x1, 0x1, 0x0, 0x68c2940, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_unix.go:243 +0x1a1
Jul 14 17:45:04 minikube localkube[15262]: net.(*conn).Read(0xc420fef448, 0xc421783662, 0x1, 0x1, 0x0, 0x0, 0x0)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/net.go:173 +0x70
Jul 14 17:45:04 minikube localkube[15262]: net/http.(*connReader).closeNotifyAwaitActivityRead(0xc420467bc0, 0xc42180f3e0, 0xc4218285a0)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/http/server.go:602 +0x71
Jul 14 17:45:04 minikube localkube[15262]: created by net/http.(*connReader).startBackgroundRead
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/http/server.go:597 +0x98
Jul 14 17:45:04 minikube localkube[15262]: goroutine 624 [IO wait]:
Jul 14 17:45:04 minikube localkube[15262]: net.runtime_pollWait(0x7f440420cc20, 0x72, 0x44)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).wait(0xc4216e8990, 0x72, 0xc4203a8e78, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jul 14 17:45:04 minikube localkube[15262]: net.(*pollDesc).waitRead(0xc4216e8990, 0x68c2940, 0xc42001a130)
Jul 14 17:45:04 minikube localkube[15262]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
--More--
```

**Comment by jflory7** [comment]
I just re-tested this with the 0.20.0 release (76c23a605c9d3ef74955afc2c2b0b939113fd5fc), but I hit the same issue with Localkube failing to start.

**Comment by r2d4** [comment]
Are you able to reproduce this on the upstream iso @jflory7?

**Comment by r2d4** [comment]
Maybe attach the full output of `minikube logs` if anything looks suspicious

**Comment by jflory7** [comment]
@r2d4 I was not able to reproduce this on the upstream ISO unfortunately.

But strangely, I switched to a new branch to pull back in all of the latest upstream changes back to 9e8ef22e931f43593597a7089e9f297e459958bf, rebuilt the ISO, and it's magically working. I've been generating the ISO a few times, so my guess is maybe some bad / incompatible data was cached in `out/`, since I deleted that before building the 0.20.0 image. When I rebuilt it just now using the latest upstream commit, I didn't delete the directory, but it seems to be working now…

I'll test it out a bit more and see if I can get any more helpful feedback. Otherwise, maybe we can just close this.

**Comment by jflory7** [comment]
@r2d4 I spoke too soon. Tried interacting with it a few minutes later, and I got the same problem. I'm poking around with the upstream ISO again, just to see if I trigger anything to replicate it, but so far, nothing.

Here's the output from `minikube logs`: [paste.fedoraproject.org/paste/h1f82eDlPJGDKXF7TtJy2w](https://paste.fedoraproject.org/paste/h1f82eDlPJGDKXF7TtJy2w/raw)

I tried trimming it down, although it's still on the longer side. But seems like it's the same issue with Localkube. I'm unable to make sense of what's happening.

**Comment by Lookyan** [comment]
I faced approximately the same problem. 
Under huge load inside minikube VM localkube is going down. Then I can't do anything with cluster. I can only ssh into minikube using `minikube ssh` and then using `ps -ax` or `top` determine that there is no localkube process. But there is still dockerd with empty list of running containers. 
`minikube status` says ```minikube: Running
localkube: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.109```

`minikube logs` says nothing ```-- No entries --```

And what is most interesting there is no even binary with localkube in /usr/local/bin
Systemctl also knows nothing about localkube after fail.

I use minikube 0.20 and kubernetes 1.7, but the same problem was also with 0.18 version with kubernetes 1.5 and on minikube 0.20 with kubernetes 1.6. 

But it appears only when I'm deploying really huge project with 21 pods and approximately 40 containers with 1 cpu usage and 2 Gb ram usage. But I give 2 cpus and 3Gb for minikube VM.

It works for some period of time properly (it can be several minutes or even two days, depending on the load on the host machine) and then fails.

**Comment by Lookyan** [comment]
Some workaround. After this fail I can repair localkube. 
I entered into ssh using `minikube ssh` and after that downloaded the binary of localkube to `/usr/local/bin`. (https://storage.googleapis.com/minikube/k8sReleases/v1.7.0/localkube-linux-amd64) Then I ran it directly without systemctl and now it works even after fail. 

Another interesting thing is everything was saved and eventually all my pods were in running state and everything was ok. I think it's because etcd stored entire state.
May be it's an issue of systemd. I don't know where I can find any information about localkube process killing.

**Comment by r2d4** [comment]
@Lookyan you can achieve the same effect by adding `--kubernetes-version v1.7.0` to `minikube start`
That will be the default in the next version of minikube.  

I'm still not sure why this original issue is happening.

**Comment by Lookyan** [comment]
I already use this flag. But after some period of time localkube exits. I think it's because of load. 
Then I get the same error on kubectl command because kube API doesn't work.

May be jflory7 has smth similar.

**Comment by jflory7** [comment]
I tried downloading the binary and running it directly too, but this didn't work for me. I think @Lookyan might have a different problem than me, since it seems like it's at least starting for him.

I ran it again, it seems to be an issue right as the kubelets try starting…

```
$ sudo ./localkube --dns-domain=cluster.local --node-ip=192.168.99.100 --generate-certs=false --logtostderr=true --enable-dns=false
Starting scheduler...                                                                                                                                                                                                                                                                     
Waiting for scheduler to be healthy...                                                                                                                                                                                                                                                    
E0720 21:52:01.072237   18869 server.go:164] unable to register configz: register config "componentconfig" twice                                                                                                                                                                          
I0720 21:52:01.774742   18869 controller_utils.go:994] Waiting for caches to sync for scheduler controller                                                                                                                                                                                
I0720 21:52:01.875020   18869 controller_utils.go:1001] Caches are synced for scheduler controller                                                                                                                                                                                        
I0720 21:52:01.875101   18869 leaderelection.go:179] attempting to acquire leader lease...                                                                                                                                                                                                
I0720 21:52:01.880854   18869 leaderelection.go:189] successfully acquired lease kube-system/kube-scheduler                                                                                                                                                                               
I0720 21:52:01.880878   18869 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-scheduler", UID:"fe06cbcb-6d8f-11e7-b0f5-0800279b114a", APIVersion:"v1", ResourceVersion:"106", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikub
scheduler is ready!                                                                                                                                                                                                                                                                       
Starting kubelet...                                                                                                                                                                                                                                                                       
Waiting for kubelet to be healthy...                                                                                                                                                                                                                                                      
I0720 21:52:02.072513   18869 feature_gate.go:144] feature gates: map[]                                                                                                                                                                                                                   
E0720 21:52:02.072540   18869 server.go:318] unable to register configz: register config "componentconfig" twice                                                                                                                                                                          
W0720 21:52:02.072633   18869 server.go:825] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config instead.                                                                                
I0720 21:52:02.074131   18869 client.go:72] Connecting to docker on unix:///var/run/docker.sock                                                                                                                                                                                           
I0720 21:52:02.074151   18869 client.go:92] Start docker client with request timeout=2m0s                                                                                                                                                                                                 
I0720 21:52:02.166432   18869 manager.go:143] cAdvisor running in container: "/system.slice/sshd.service"                                                                                                                                                                                 
fatal error: unexpected signal during runtime execution                                                                                                                                                                                                                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fa5f32c31a8]

runtime stack:                                                                                                                                                                                                                                                                            
runtime.throw(0x49d32d7, 0x2a)                                                                                                                                                                                                                                                            
        /usr/local/go/src/runtime/panic.go:596 +0x95                                                                                                                                                                                                                                      
runtime.sigpanic()                                                                                                                                                                                                                                                                        
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                          
goroutine 3491 [syscall, locked to thread]:                                                                                                                                                                                                                                               
runtime.cgocall(0x3ab6360, 0xc429993dd8, 0x49cbb09)                                                                                                                                                                                                                                       
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc429993d98 sp=0xc429993d58                                                                                                                                                                                                    
net._C2func_getaddrinfo(0x7fa36c0008c0, 0x0, 0xc423d9af60, 0xc42013e330, 0x0, 0x0, 0x0)                                                                                                                                                                                                   
        net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc429993dd8 sp=0xc429993d98                                                                                                                                                                                                                 
net.cgoLookupIPCNAME.func2(0x7fa36c0008c0, 0x0, 0xc423d9af60, 0xc42013e330, 0x40ef760, 0xc429993e98, 0x41147c)                                                                                                                                                                            
        /usr/local/go/src/net/cgo_unix.go:151 +0x171 fp=0xc429993e38 sp=0xc429993dd8                                                                                                                                                                                                      
net.cgoLookupIPCNAME(0x49454a5, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                                                                                   
        /usr/local/go/src/net/cgo_unix.go:151 +0x1bd fp=0xc429993f38 sp=0xc429993e38                                                                                                                                                                                                      
net.cgoIPLookup(0xc4210af2c0, 0x49454a5, 0x9)                                                                                                                                                                                                                                             
        /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc429993fc8 sp=0xc429993f38                                                                                                                                                                                                       
runtime.goexit()                                                                                                                                                                                                                                                                          
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc429993fd0 sp=0xc429993fc8                                                                                                                                                                                                   
created by net.cgoLookupIP                                                                                                                                                                                                                                                                
        /usr/local/go/src/net/cgo_unix.go:213 +0xb4

[…]
```

**Comment by LusciousPear** [comment]
I have this same problem on a fresh install. Unable to run the tutorial. Adding the flag does not help me. Running virtualbox on Ubuntu 16.10. 

```
bradford@ubuntu:~$ minikube start --kubernetes-version v1.7.0
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Moving files into cluster...
Downloading localkube binary
 137.48 MB / 137.48 MB [============================================] 100.00% 0s
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
bradford@ubuntu:~$ kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080
Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout
```

**Comment by duncanphillips** [comment]
Any workarounds for this, or perhaps the last known version without this issue?

**Comment by r2d4** [comment]
Are you able to reproduce this with a downloaded version of localkube?  If you're building it yourself, can you try a docker build with  `$ BUILD_IN_DOCKER=y make`?

**Comment by Lookyan** [comment]
Is it possible to ssh into VM after this fail? 
And what's happening with localkube process? Is it running?

**Comment by firekhaya** [comment]
I had this problem on  v0.21.0. I downgraded to v0.19.0 and the error went away.

**Comment by jflory7** [comment]
@r2d4 I hit this on my the ISO that I had built, but I did download Localkube to try using that binary, but the same thing happened. However, I will try to rebuild it using this flag later today and will let you know the result.

@Lookyan For me, Minikube starts up normally in the VM, just not Localkube, so any of the Kubernetes client commands (e.g. `kubectl cluster-info`) results in this error. I was able to get in with `minikube ssh`.

@firekhaya Curious, do you hit this on v0.20.0? I tried downgrading to v0.20.0 and hit the same problem, but I didn't try v0.19.0. Are you building your own ISO or using the Minikube default?

**Comment by firekhaya** [comment]
@jflory7  My upgrade jump was from v0.19.0 to v0.21.0 so I am not sure if the problem exists in  v0.0.20. I am using the Minikube default.

**Comment by jflory7** [comment]
So, I've changed a few things since I last tested it, and have somewhat similar results:

* **Minikube version**: v0.21.0
* **ISO version**: Build on fa04ef7b3744d70e3ac88981d6fc67c7980ffd09

## Localkube crash loop

Per @r2d4's suggestion, I build the `buildroot` and Minikube images with the `BUILD_IN_DOCKER=y` variable. Now, the cluster will respond if I type `kubectl cluster-info`, but looking deeper, Localkube seems to be in a constant crashing state (so it starts up for a few seconds, then instantly crashes). I was able to deploy resources (e.g. deployments and services), but they're stuck in a pending state since Localkube is constantly restarting.

This is a snippet of the logs I have:

```
…
Aug 04 17:06:46 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 04 17:06:46 minikube localkube[16351]: k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x8d2ada0, 0xc430b179d0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /go/src/k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
Aug 04 17:06:46 minikube localkube[16351]: net/http.HandlerFunc.ServeHTTP(0xc423525e60, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Aug 04 17:06:46 minikube localkube[16351]: k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc423525ee0, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /go/src/k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:84 +0x42f
Aug 04 17:06:46 minikube localkube[16351]: k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /go/src/k8s.io/minikube/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:78 +0x292
Aug 04 17:06:46 minikube localkube[16351]: net/http.HandlerFunc.ServeHTTP(0xc42362dfc0, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Aug 04 17:06:46 minikube localkube[16351]: k8s.io/minikube/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /go/src/k8s.io/minikube/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x200
Aug 04 17:06:46 minikube localkube[16351]: net/http.HandlerFunc.ServeHTTP(0xc4239e23c0, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Aug 04 17:06:46 minikube localkube[16351]: k8s.io/minikube/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /go/src/k8s.io/minikube/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
Aug 04 17:06:46 minikube localkube[16351]: net/http.HandlerFunc.ServeHTTP(0xc423525fa0, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Aug 04 17:06:46 minikube localkube[16351]: net/http.serverHandler.ServeHTTP(0xc420823c30, 0x8d3ac20, 0xc4224957a0, 0xc42b754400)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:2568 +0x92
Aug 04 17:06:46 minikube localkube[16351]: net/http.(*conn).serve(0xc42a068640, 0x8d3df20, 0xc4262745c0)
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:1825 +0x612
Aug 04 17:06:46 minikube localkube[16351]: created by net/http.(*Server).Serve
Aug 04 17:06:46 minikube localkube[16351]:         /usr/local/go/src/net/http/server.go:2668 +0x2ce
Aug 04 17:06:46 minikube localkube[16351]: goroutine 3494 [select]:
Aug 04 17:06:46 minikube systemd[1]: localkube.service: Unit entered failed state.
…
```

## Misc. error

While building the buildroot and final ISO, I noticed this output that I haven't seen before when building the ISO. Not sure if related, but I'll leave it here in case…

```
$ BUILD_IN_DOCKER=y make out/minikube.iso
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
	/home/jflory/workspace/go/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/jflory/workspace/go/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/jflory/workspace/go/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/jflory/workspace/go/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/jflory/workspace/go/src/k8s.io/minikube/pkg/provision (from $GOPATH)
docker run --rm --workdir /mnt --volume /home/jflory/git/minikube:/mnt -v /etc/pki/ca-trust/source/anchors/jump-root-sha256.crt:/etc/ssl/certs/jump-root-sha256.pem:ro -v /etc/pki/ca-trust/source/anchors/jump-issuing-sha256.crt:/etc/ssl/certs/jump-issuing-sha256.pem:ro \
	--user 42395:40801 --env HOME=/tmp --env IN_DOCKER=1 \
	gcr.io/k8s-minikube/buildroot-image /usr/bin/make out/minikube.iso
…
```

**Comment by ernstp** [comment]
Also same as #1947  ? getaddrinfo SIGSEGV.

**Comment by dlorenc** [comment]
Yeah, I think this is a dupe. Just sent a PR.

**Comment by jflory7** [comment]
@dlorenc Is this fixed?

**Comment by dlorenc** [comment]
I closed this as a duplicate of #1947, which I just sent a PR for.

**Comment by Pensu** [comment]
Could anyone find a fix for it? I am still getting the "SIGSEGV" error.

**Comment by viteksafronov** [comment]
We have this issue on vbox driver (as posted in this issue). I don't know why it is a duplicate of #1947, because that bug was fixed for vmdriver=none only.
We have the random crashes of localkube in an unpredictable manner. Is there a workaround for the bug with vbox driver?
We use fresh minikube 0.24.1
