### ISSUE TITLE
Panic on minikube start --vm-driver=hyperv

### ISSUE THREAD

**Issue by jebbench** [kubernetes/minikube#1704]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): minikube version: v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): N/A
- **Install tools**:  chocolatey
- **Others**:

**What happened**:
When trying to start Minikube it panics.
```
PS C:\Windows\system32> minikube start --vm-driver=hyperv
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x17498e0, 0xc04200a030)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
k8s.io/minikube/vendor/github.com/docker/machine/drivers/hyperv.hypervAvailable(0xc0423ac520, 0xc042558c18)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/docker/machine/drivers/hyperv/powershell.go:64 +0x10c
k8s.io/minikube/vendor/github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc042194b40, 0x0, 0x0)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/docker/machine/drivers/hyperv/hyperv.go:164 +0x3d
k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers.(Driver).PreCreateCheck-fm(0x0, 0x0)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine/client.go:183 +0x39
k8s.io/minikube/pkg/minikube/machine.(*LocalClient).Create(0xc04215f400, 0xc042194ba0, 0x6, 0xc0420fe480)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine/client.go:217 +0x318
k8s.io/minikube/pkg/minikube/cluster.createHost(0x3b8d2a0, 0xc04215f400, 0xc04244bbc0, 0x40, 0x800, 0x2, 0x4e20, 0xc0420423cc, 0x6, 0x1900e4e, ...)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/cluster/cluster.go:387 +0x4d5
k8s.io/minikube/pkg/minikube/cluster.StartHost(0x3b8d2a0, 0xc04215f400, 0xc04244bbc0, 0x40, 0x800, 0x2, 0x4e20, 0xc0420423cc, 0x6, 0x1900e4e, ...)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/cluster/cluster.go:68 +0x680
k8s.io/minikube/cmd/minikube/cmd.runStart.func1(0x0, 0xc04202ac00)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd/start.go:125 +0x83
k8s.io/minikube/pkg/util.RetryAfter(0x5, 0xc0422a8120, 0x77359400, 0xf, 0x0)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/util/utils.go:88 +0x6b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x3be1860, 0xc0421020c0, 0x0, 0x1)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd/start.go:131 +0x76e
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x3be1860, 0xc0421020a0, 0x1, 0x1, 0x3be1860, 0xc0421020a0)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:603 +0x440
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3be0dc0, 0x3c0ec00, 0xc042559ec8, 0x47ed13)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:689 +0x36e
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x3be0dc0, 0x0, 0x0)
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:648 +0x32
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd/root.go:111 +0x34
main.main()
        /var/lib/jenkins/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/main.go:38 +0x79
```

**What you expected to happen**:
To start Minikube.

**How to reproduce it** (as minimally and precisely as possible):
Run the command `minikube start --vm-driver=hyperv`

**Anything else do we need to know**:
Docker for Windows is installed and running.

**Comment by r2d4** [comment]
Do you have hyper-v installed?  It looks like this panic is coming from an unchecked "parseLines" in this vendored in code from docker/machine https://github.com/kubernetes/minikube/blob/05edfeaf65563776501834942ddb41d96d094e78/vendor/github.com/docker/machine/drivers/hyperv/powershell.go#L64-L66

We should send a patch upstream to add a check there.

**Comment by jebbench** [comment]
Solved by rebooting.

HyperV was installed but I had installed Docker for Windows and not rebooted since which maybe related?

**Comment by aaron-prindle** [comment]
We will need to send a patch upstream with better error messaging for this.
