### ISSUE TITLE
Failed to start Localkube in restarted Minikube

### ISSUE THREAD

**Issue by jstangroome** [kubernetes/minikube#2411]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: 

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release): Windows 10 x64 Version 1709 (OS Build 16299.192)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6
- **Install tools**:
- **Others**: VirtualBox 5.1.30 r118389
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: A Minikube VM existed but was not running due to a previous host system restart (scheduled Windows Updates). `minikube start` succeeded but `minikube dashboard` failed with error:
```
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: dial tcp 192.168.99.100:8443: connectex: No connection could be made because the target machine actively refused it.
```
Inspecting the state of the Minikube guest revealed the localkube service was in a restart loop:
```
$ minikube ssh systemctl status localkube.service
● localkube.service - Localkube
   Loaded: loaded (/etc/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-01-10 03:34:05 UTC; 1s ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
  Process: 30738 ExecStart=/usr/local/bin/localkube --dns-domain=cluster.local --node-ip=192.168.99.100 --generate-certs=false --logtostderr=true --enable-dns=false [0;1;31m(code=exited, status=2)[0m
 Main PID: 30738 (code=exited, status=2)
      CPU: 195ms
```
Querying the localkube logs revealed an issue with the embedded etcd server reading the bolt database:
```
$ minikube ssh journalctl -u localkube.service
Jan 10 01:53:56 minikube systemd[1]: Starting Localkube...
Jan 10 01:53:56 minikube localkube[23215]: panic: invalid page type: 3762814904717228082: 3438
Jan 10 01:53:56 minikube localkube[23215]: goroutine 1 [running]:
Jan 10 01:53:56 minikube localkube[23215]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc421bdc9e0, 0x97b1bbc, 0x7, 0x7, 0x33)
```
(log truncated, full version to follow)

**What you expected to happen**:
I'd like to see Minikube at least recognise that localkube is not running in the guest VM instead of reporting success on `minikube start`. Beyond that it would be nice if Localkube could gracefully recover from this state.

**How to reproduce it** (as minimally and precisely as possible):
I'd guess shutdown the Minikube VM in a way that the bolt database becomes corrupted.

**Output of `minikube logs` (if applicable)**:
```
-- Logs begin at Wed 2018-01-10 01:34:10 UTC, end at Wed 2018-01-10 03:41:37 UTC. --
Jan 10 01:34:37 minikube systemd[1]: Starting Localkube...
Jan 10 01:34:37 minikube localkube[3134]: listening for peers on http://localhost:2380
Jan 10 01:34:37 minikube localkube[3134]: listening for client requests on localhost:2379
Jan 10 01:34:37 minikube localkube[3134]: recovered store from snapshot at index 740075
Jan 10 01:34:37 minikube localkube[3134]: name = default
Jan 10 01:34:37 minikube localkube[3134]: data dir = /var/lib/localkube/etcd
Jan 10 01:34:37 minikube localkube[3134]: member dir = /var/lib/localkube/etcd/member
Jan 10 01:34:37 minikube localkube[3134]: heartbeat = 100ms
Jan 10 01:34:37 minikube localkube[3134]: election = 1000ms
Jan 10 01:34:37 minikube localkube[3134]: snapshot count = 10000
Jan 10 01:34:37 minikube localkube[3134]: advertise client URLs = http://localhost:2379
Jan 10 01:34:37 minikube localkube[3134]: ignored file 000000000000000e-00000000000b40f5.wal.broken in wal
Jan 10 01:34:37 minikube localkube[3134]: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 747075
Jan 10 01:34:37 minikube localkube[3134]: 8e9e05c52164694d became follower at term 4
Jan 10 01:34:37 minikube localkube[3134]: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 4, commit: 747075, applied: 740075, lastindex: 747075, lastterm: 4]
Jan 10 01:34:37 minikube localkube[3134]: panic: invalid page type: 3762814904717228082: 3438
Jan 10 01:34:37 minikube localkube[3134]: goroutine 1 [running]:
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc4219429e0, 0x97b1bbc, 0x7, 0x7, 0x33)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/cursor.go:256 +0x40c
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc4219429e0, 0x97b1bbc, 0x7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/cursor.go:159 +0xb1
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc4206f22b8, 0x97b1bbc, 0x7, 0x7, 0x0, 0x4, 0x3)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/bucket.go:164 +0x118
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Tx).CreateBucket(0xc4206f22a0, 0x97b1bbc, 0x7, 0x7, 0x3c5bd40, 0xc42092dca0, 0x3aa8d60)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/tx.go:108 +0x4f
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc420947de0, 0x97b1bbc, 0x7, 0x7)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:53 +0x6b
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/membership.mustCreateBackendBuckets(0x9805160, 0xc420011140)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/membership/store.go:166 +0xb9
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/membership.(*RaftCluster).SetBackend(0xc4201d8900, 0x9805160, 0xc420011140)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/membership/cluster.go:203 +0x54
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc4206a9080, 0xc4206a9080, 0x0, 0x0)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/server.go:389 +0xb4e
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc4207ba280, 0xc42018edc0, 0x0, 0x0)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/embed/etcd.go:123 +0x6e0
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/pkg/localkube.(*EtcdServer).Start(0xc420a46cd0)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/pkg/localkube/etcd.go:51 +0x44
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/cmd/localkube/cmd.SetupServer(0xc4206a8420)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/start.go:116 +0x2cb
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/cmd/localkube/cmd.StartLocalkube()
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/start.go:51 +0x6e
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/cmd/localkube/cmd.glob..func1(0x97a9760, 0xc420358c30, 0x0, 0x5)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/root.go:31 +0x20
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x97a9760, 0xc4200100d0, 0x5, 0x5, 0x97a9760, 0xc4200100d0)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:603 +0x234
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x97a9760, 0x463af37, 0x2e, 0xc4206a8460)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
Jan 10 01:34:37 minikube localkube[3134]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x97a9760, 0xc420c97f50, 0x35e7339)
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:648 +0x2b
Jan 10 01:34:37 minikube localkube[3134]: main.main()
Jan 10 01:34:37 minikube localkube[3134]:         /go/src/k8s.io/minikube/cmd/localkube/main.go:32 +0x58
Jan 10 01:34:37 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 10 01:34:37 minikube systemd[1]: Failed to start Localkube.
Jan 10 01:34:37 minikube systemd[1]: localkube.service: Unit entered failed state.
Jan 10 01:34:37 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
Jan 10 01:34:40 minikube systemd[1]: localkube.service: Service hold-off time over, scheduling restart.
Jan 10 01:34:40 minikube systemd[1]: Stopped Localkube.
```

**Comment by huguesalary** [comment]
I have the same problem with a similar error, though not exactly the same:

```
Mar 12 19:05:19 minikube systemd[1]: Failed to start Localkube.
Mar 12 19:05:19 minikube systemd[1]: localkube.service: Unit entered failed state.
Mar 12 19:05:19 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
Mar 12 19:05:22 minikube systemd[1]: localkube.service: Service hold-off time over, scheduling restart.
Mar 12 19:05:22 minikube systemd[1]: Stopped Localkube.
Mar 12 19:05:22 minikube systemd[1]: Starting Localkube...
Mar 12 19:05:23 minikube localkube[3381]: listening for peers on http://localhost:2380
Mar 12 19:05:23 minikube localkube[3381]: listening for client requests on localhost:2379
Mar 12 19:05:23 minikube localkube[3381]: recovered store from snapshot at index 1500150
Mar 12 19:05:23 minikube localkube[3381]: name = default
Mar 12 19:05:23 minikube localkube[3381]: data dir = /var/lib/localkube/etcd
Mar 12 19:05:23 minikube localkube[3381]: member dir = /var/lib/localkube/etcd/member
Mar 12 19:05:23 minikube localkube[3381]: heartbeat = 100ms
Mar 12 19:05:23 minikube localkube[3381]: election = 1000ms
Mar 12 19:05:23 minikube localkube[3381]: snapshot count = 10000
Mar 12 19:05:23 minikube localkube[3381]: advertise client URLs = http://localhost:2379
Mar 12 19:05:23 minikube localkube[3381]: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 1508157
Mar 12 19:05:23 minikube localkube[3381]: 8e9e05c52164694d became follower at term 23
Mar 12 19:05:23 minikube localkube[3381]: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 23, commit: 1508157, applied: 1500150, lastindex: 1508157, lastterm: 23]
Mar 12 19:05:23 minikube localkube[3381]: enabled capabilities for version 3.1
Mar 12 19:05:23 minikube localkube[3381]: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
Mar 12 19:05:23 minikube localkube[3381]: set the cluster version to 3.1 from store
Mar 12 19:05:23 minikube localkube[3381]: panic: invalid page allocation: 0
Mar 12 19:05:23 minikube localkube[3381]: goroutine 1 [running]:
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*freelist).allocate(0xc420d18240, 0x3, 0x3000)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/freelist.go:71 +0x306
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*DB).allocate(0xc4208863c0, 0x3, 0xc421b72790, 0xa92abb, 0xc420d18240)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/db.go:838 +0x9c
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Tx).allocate(0xc420862000, 0x3, 0x7f81c80d1000, 0x33a, 0x0)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/tx.go:454 +0x3d
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc420862000, 0x7a844a7, 0xa873600)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/boltdb/bolt/tx.go:177 +0x265
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc42018ff80, 0x4ac5800)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:183 +0x9d
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).Commit(0xc42018ff80)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:140 +0x66
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).ForceCommit(0xc420808a80)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:132 +0x2f
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc4201f3860)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/lease/lessor.go:501 +0x452
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/lease.newLessor(0xa626020, 0xc420808a80, 0x2, 0xc4203bd7e0)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/lease/lessor.go:167 +0x1b3
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/lease.NewLessor(0xa626020, 0xc420808a80, 0x2, 0xc4203573b0, 0x1)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/lease/lessor.go:153 +0x3f
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc4202c38c0, 0xc4202c38c0, 0x0, 0x0)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/etcdserver/server.go:448 +0x1699
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc420844780, 0xc4208af080, 0x0, 0x0)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/coreos/etcd/embed/etcd.go:123 +0x6e0
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/pkg/localkube.(*EtcdServer).Start(0xc420396d30)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/pkg/localkube/etcd.go:51 +0x44
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/cmd/localkube/cmd.SetupServer(0xc4202c3340)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/start.go:116 +0x2cb
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/cmd/localkube/cmd.StartLocalkube()
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/start.go:51 +0x6e
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/cmd/localkube/cmd.glob..func1(0xa5c5fc0, 0xc4204c1cb0, 0x0, 0x9)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/cmd/localkube/cmd/root.go:31 +0x20
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0xa5c5fc0, 0xc4200100b0, 0x9, 0x9, 0xa5c5fc0, 0xc4200100b0)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:603 +0x234
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa5c5fc0, 0x49eff27, 0x2e, 0xc4202c3380)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
Mar 12 19:05:23 minikube localkube[3381]: k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0xa5c5fc0, 0xc420d61f50, 0x389b6f9)
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:648 +0x2b
Mar 12 19:05:23 minikube localkube[3381]: main.main()
Mar 12 19:05:23 minikube localkube[3381]:         /go/src/k8s.io/minikube/cmd/localkube/main.go:32 +0x58
Mar 12 19:05:23 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 12 19:05:23 minikube systemd[1]: Failed to start Localkube.
Mar 12 19:05:23 minikube systemd[1]: localkube.service: Unit entered failed state.
Mar 12 19:05:23 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
```

It started happening today out of nowhere.

I tried starting and stopping minikube a few times, to no avail.

**Comment by huguesalary** [comment]
Removing `/var/lib/localkube/etcd/member` fixes the issue, but of course all pods are lost.
