### ISSUE TITLE
kubectl panic on pod delete

### ISSUE THREAD

**Issue by rednatto** [kubernetes/minikube#2504]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.25.0 (started with --memory 8196 --cpus 4 --kubernetes-version v1.9.0 --bootstrapper kubeadm --vm-driver virtualbox )
- **OS** (e.g. from /etc/os-release): macOS High Sierra (Version 10.13.2)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox",
- **ISO version** (e.g. `minikube ssh cat /etc/VERSION`): v0.25.1
- **Install tools**: brew
- **Others**: Docker for mac running?

**What happened:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x21b8f83]
```

**What you expected to happen**:
No panic.

**How to reproduce it** (as minimally and precisely as possible):
Get ngnix-deployment.yaml from https://raw.githubusercontent.com/kubernetes/website/master/docs/concepts/workloads/controllers/nginx-deployment.yaml .

Start minikube with:
```
minikube delete
minikube start --memory 8196 --cpus 4 --kubernetes-version v1.9.0 --bootstrapper kubeadm --vm-driver virtualbox
```

Create the deployment:
`λ kubectl create -f nginx-deployment.yaml`                                     
```
deployment "nginx-deployment" created
```

Delete a pod from the deployment (either one or all gives the same result):
`λ kubectl delete pod nginx-deployment-6c54bd5869-2lshn`                        
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x21b8f83]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl.ReaperFor(0x0, 0x0, 0x2370237, 0x3, 0x0, 0x0, 0x0, 0xc420a094a0, 0x13fdaa2, 0xbe9284d8ac70ccf0)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/delete.go:82 +0x1373
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc420751200, 0xc4204f79d0, 0x3666b40, 0x1a0003825900, 0xb8, 0xb8)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:295 +0x151
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*factory).Reaper(0xc420751230, 0xc4204f79d0, 0x3825900, 0x3e2b6c8, 0x0, 0x2678340)
        <autogenerated>:1 +0x47
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult.func1(0xc4204f7b20, 0x0, 0x0, 0x3815c00, 0x2853435)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:250 +0xe9
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc4204f7b20, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:396 +0x164
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc4204f7b20, 0x0, 0x0, 0x7, 0xa)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:372 +0xe7
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4204f7b20, 0x0, 0x0, 0xc42096d140, 0x414e798)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:433 +0x4fe
k8s.io/kubernetes/pkg/kubectl/resource.(*Info).Visit(0xc4204f7b20, 0xc42096d140, 0x0, 0x10103e7)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:105 +0x42
k8s.io/kubernetes/pkg/kubectl/resource.VisitorList.Visit(0xc4201f2350, 0x1, 0x1, 0xc42096d140, 0x1, 0xc42096d140)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:234 +0x63
k8s.io/kubernetes/pkg/kubectl/resource.(*VisitorList).Visit(0xc420450900, 0xc42096d140, 0x3e2b6c8, 0x0)
        <autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x365a640, 0xc420450900, 0xc4203516c0, 0xc4207864c0, 0x60000000001, 0xc4207864c0)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:428 +0x9e
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420450920, 0xc4207864c0, 0x28, 0x3825900)
        <autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x365a5c0, 0xc420450920, 0xc4201f2360, 0x2, 0x2, 0xc420450980, 0x1, 0xc420450980)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:363 +0x9b
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc42096d110, 0xc420450980, 0xc4201f2370, 0xc420a09b60)
        <autogenerated>:1 +0x62
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x365a4c0, 0xc42096d110, 0xc4204f7b90, 0x0, 0x2)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:391 +0xe4
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc4201f2370, 0xc4204f7b90, 0x1010b48, 0x70)
        <autogenerated>:1 +0x4f
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc4202ae600, 0xc4204f7b90, 0xc42095bd10, 0x3679b80)```
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:98 +0x62
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult(0xc4202ae600, 0x3686980, 0xc420751230, 0x3659480, 0xc42000c018, 0xc420130001, 0x0, 0xffffffffffffffff, 0xc4209a0000, 0x3679b80, ...)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:245 +0x16c
k8s.io/kubernetes/pkg/kubectl/cmd.(*DeleteOptions).RunDelete(0xc4207104d0, 0xc420290480, 0x0)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:235 +0xd2
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDelete.func1(0xc420290480, 0xc42013d4c0, 0x2, 0x2)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:142 +0x178
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420290480, 0xc42013d300, 0x2, 0x2, 0xc420290480, 0xc42013d300)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420396900, 0x8000104, 0x0, 0xffffffffffffffff)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420396900, 0xc420751230, 0x3659440)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:41 +0xd5
main.main()
        /private/tmp/kubernetes-cli-20180118-36889-kx51hi/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:27 +0x26
```

**Output of `minikube logs` (if applicable)**:
-- Logs begin at Fri 2018-02-02 15:23:59 UTC, end at Fri 2018-02-02 15:32:05 UTC. --
-- No entries --

**Anything else we need to know**:
`kubectl describe pod nginx-deployment-6c54bd5869-2lshn`
Gives correct result.

Any deployment gives the same result.

Also created in https://github.com/kubernetes/kubectl/issues/226  .

**Comment by decoursin** [comment]
It seems there's maybe an authorization issue, here's the log when I try to delete a deployment in debug mode (-v=8)
```
$ kubectl delete deployment hello-minikube -v=8
I0205 09:55:33.157199   29039 loader.go:357] Config loaded from file /home/nick/.kube/config
I0205 09:55:33.158188   29039 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I0205 09:55:33.158693   29039 cached_discovery.go:124] skipped caching discovery info due to Unauthorized
I0205 09:55:33.158772   29039 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I0205 09:55:33.158822   29039 cached_discovery.go:124] skipped caching discovery info due to Unauthorized
I0205 09:55:33.159156   29039 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I0205 09:55:33.159205   29039 cached_discovery.go:124] skipped caching discovery info due to Unauthorized
I0205 09:55:33.159219   29039 factory_object_mapping.go:93] Unable to retrieve API resources, falling back to hardcoded types: Unauthorized
I0205 09:55:33.160706   29039 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I0205 09:55:33.160781   29039 cached_discovery.go:124] skipped caching discovery info due to Unauthorized
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x15b61ca]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl.ReaperFor(0x1c51e7a, 0xa, 0x17a7d2c, 0xa, 0x0, 0x0, 0x0, 0xc4207c14a0, 0x7f58d2, 0xbe9624e149829671)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/delete.go:91 +0xbda
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc4207f2270, 0xc42043f490, 0x2a4f8c0, 0x1a002047a000, 0xb8, 0xb8)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:295 +0x151
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*factory).Reaper(0xc4207f22a0, 0xc42043f490, 0xc42047a000, 0x7fb91faeb000, 0x0, 0x1a75bc0)
	<autogenerated>:1 +0x47
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult.func1(0xc42043f5e0, 0x0, 0x0, 0x2bfe940, 0x1c50a1e)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:250 +0xe9
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc42043f5e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:396 +0x164
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc42043f5e0, 0x0, 0x0, 0x18, 0xa)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:372 +0xe7
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc42043f5e0, 0x0, 0x0, 0xc420a06f60, 0x7fb91faa7c20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:433 +0x4fe
k8s.io/kubernetes/pkg/kubectl/resource.(*Info).Visit(0xc42043f5e0, 0xc420a06f60, 0x0, 0x4105e7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:105 +0x42
k8s.io/kubernetes/pkg/kubectl/resource.VisitorList.Visit(0xc420055d90, 0x1, 0x1, 0xc420a06f60, 0x1, 0xc420a06f60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:234 +0x63
k8s.io/kubernetes/pkg/kubectl/resource.(*VisitorList).Visit(0xc420a0b060, 0xc420a06f60, 0x7fb91faeb000, 0x0)
	<autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2a43400, 0xc420a0b060, 0xc420518a80, 0xc4205198c0, 0x60000000001, 0xc4205198c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:428 +0x9e
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420a0b080, 0xc4205198c0, 0x28, 0xc42047a000)
	<autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2a43380, 0xc420a0b080, 0xc420055da0, 0x2, 0x2, 0xc420a0b0e0, 0xc420055d01, 0xc420a0b0e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:363 +0x9b
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc420a06f30, 0xc420a0b0e0, 0xc420055db0, 0xc4207c1b60)
	<autogenerated>:1 +0x62
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x2a43280, 0xc420a06f30, 0xc42043f650, 0x0, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:391 +0xe4
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc420055db0, 0xc42043f650, 0x410d48, 0x70)
	<autogenerated>:1 +0x4f
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc42023ea80, 0xc42043f650, 0xc4209aa3c0, 0x2a62840)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:98 +0x62
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult(0xc42023ea80, 0x2a6f640, 0xc4207f22a0, 0x2a42480, 0xc42000c018, 0xc4207f0001, 0x0, 0xffffffffffffffff, 0xc420990000, 0x2a62840, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:245 +0x16c
k8s.io/kubernetes/pkg/kubectl/cmd.(*DeleteOptions).RunDelete(0xc42070c160, 0xc4201ac000, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:235 +0xd2
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDelete.func1(0xc4201ac000, 0xc4207f2ed0, 0x2, 0x3)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:142 +0x178
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201ac000, 0xc4207f2e40, 0x3, 0x3, 0xc4201ac000, 0xc4207f2e40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203ae6c0, 0x8000103, 0x0, 0xffffffffffffffff)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203ae6c0, 0xc4207f22a0, 0x2a42440)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:41 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:27 +0x26

```

**Comment by decoursin** [comment]
I tried delete the minikube script, the VM, and the ~/.minikube foder, then reinstalling everything, but the same issue persists.

**Comment by r2d4** [comment]
What kubectl version are you using?

**Comment by decoursin** [comment]
I tried it with different kubectl clients, the last attempt when it wasn't working was v1.9.0. Anyways, I was able to get it working somehow, I don't know what changed, I'm still using v1.9.0; I started minikube with different parameters, maybe I don't know, I think I was after I had deleted everything for a second time.

I thought it might have been because the node-ip changed, because I noticed this last minikube start that the node-ip was different than what it was when it wasn't working; as such, I concluded that the certs were now valid since the node-ip was reset to its original value. (The truth is that the first time I was using minikube it was working, then eventually later it stopped working, so I thought the node-ip was reset to this first value.)

**Comment by rednatto** [comment]
@r2d4 This is the result of `kubectl version`;
```
Kubernetes version (use kubectl version):

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rednatto** [comment]
Possibly related information:

Creating a service, and then trying to fetch it gives different results when using `svc` vs `service`, against the broken cluster, but seems to work against other cluster?


`kubectl create service nodeport nginx --tcp=8080` 

```
service "nginx" created
```
`kubectl get svc nginx`

```
the server doesn't have a resource type "svc"
```

`kubectl get service nginx` 

```
NAME      TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
nginx     NodePort   10.98.56.135   <none>        8080:31786/TCP   18s
```

**Comment by decoursin** [comment]
@rednatto I remember seeing that same exact problem with `svc` not working

**Comment by decoursin** [comment]
Suddenly, the issue started happening to me again. Everything was working fine, then I noticed the `kubectl get svc ..` wasn't working but `kubect get service ..` was, like @rednatto documented, and then a little bit later `kubectl delete pod ..` fails on me too. This is really unfortunate because it's impeding my ability to work

**Comment by rednatto** [comment]
@r2d4 Is more info still needed?

**Comment by decoursin** [comment]
Hello, I noticed that deleting everything, as I described up [above](https://github.com/kubernetes/minikube/issues/2504#issuecomment-363020670), does actually seem to resolve the issue, until it reoccurs.
