### ISSUE TITLE
Mounting host folder is failing

### ISSUE THREAD

**Issue by rahulwa** [kubernetes/minikube#2732]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): `macOS (10.13.4)`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `virtualbox`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `v0.26.0`
- **Install tools**: 
- **Others**:

**What happened**:
minikube is not able to mount host folder. This is the error:
```
~ minikube mount ~/projects/app:/data
Mounting /Users/macbook/projects/app into /data on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
panic: lookup localhost on 192.168.1.1:53: no such host

goroutine 1 [running]:
k8s.io/minikube/cmd/util.GetPort(0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/minikube/cmd/util/util.go:227 +0x250
k8s.io/minikube/cmd/minikube/cmd.glob..func11(0x29c1180, 0xc420448cf0, 0x1, 0x1)
	/go/src/k8s.io/minikube/cmd/minikube/cmd/mount.go:125 +0x6ed
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x29c1180, 0xc420448cb0, 0x1, 0x1, 0x29c1180, 0xc420448cb0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29c13e0, 0x0, 0x29f6c00, 0xc420303f30)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x29c13e0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:105 +0x2d
main.main()
	/go/src/k8s.io/minikube/cmd/minikube/main.go:41 +0x99
```
And minikube is running fine:
```
~ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
```

**What you expected to happen**:
minikube should be able to monunt host folder successfully.

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --vm-driver=virtualbox
minikube mount ~/projects/app:/data
```

**Output of `minikube logs` (if applicable)**

**Anything else do we need to know**:
`VirtualBox Version: 5.2.8 r121009`

I tried with `hyperkit` vm-driver and that also failed.
```
~ minikube start --vm-driver=hyperkit
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
~ 
~ minikube mount ~/projects/app:/data
Mounting /Users/macbook/projects/app into /data on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
panic: lookup localhost on 192.168.1.1:53: no such host

goroutine 1 [running]:
k8s.io/minikube/cmd/util.GetPort(0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/minikube/cmd/util/util.go:227 +0x250
k8s.io/minikube/cmd/minikube/cmd.glob..func11(0x29c1180, 0xc420436580, 0x1, 0x1)
	/go/src/k8s.io/minikube/cmd/minikube/cmd/mount.go:125 +0x6ed
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x29c1180, 0xc420436540, 0x1, 0x1, 0x29c1180, 0xc420436540)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29c13e0, 0x0, 0x29f6c00, 0xc420309f30)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x29c13e0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:105 +0x2d
main.main()
	/go/src/k8s.io/minikube/cmd/minikube/main.go:41 +0x99
```

**Comment by rahulwa** [comment]
`localhost` entry was missing on `/etc/hosts`. It worked like charm after adding it.
