### ISSUE TITLE
Error creating machine: Library/Containers/com.docker.docker/Data/s50: no such file or directory.

### ISSUE THREAD

**Issue by fyuan1316** [kubernetes/minikube#3066]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Please provide the following details:

**Environment**:

```
inikube version: v0.28.2

OS:macOS High Sierra 10.13.5

VM driver:
    "DriverName": "hyperkit",

ISO version
        "Boot2DockerURL": "file:///Users/username/.minikube/cache/iso/minikube-v0.28.1.iso"
```

**What happened**:
execute command : **minikube start --vm-driver hyperkit -v 10 --hyperkit-vpnkit-sock auto**
receive error:
```
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
E0811 22:11:05.580005   21754 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/max/Library/Containers/com.docker.docker/Data/s50: no such file or directory.
```

**What you expected to happen**:

1.  minikube can start successfully
2. i use docker and minikube behind a proxy, and i add flag '--hyperkit-vpnkit-sock auto' in order to use the http proxy settting which set on docker for mac. I am not sure if this is correct.  
Does anyone have the same situation, Can anyone give me some tips? thank you 

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:
```
Aliases:
map[string]string{}
Override:
map[string]interface {}{"v":"10"}
PFlags:
map[string]viper.FlagValue{"bootstrapper":viper.pflagValue{flag:(*pflag.Flag)(0xc4204543c0)}, "mount-string":viper.pflagValue{flag:(*pflag.Flag)(0xc420454f00)}, "registry-mirror":viper.pflagValue{flag:(*pflag.Flag)(0xc420455b80)}, "hyperkit-vsock-ports":viper.pflagValue{flag:(*pflag.Flag)(0xc420040140)}, "keep-context":viper.pflagValue{flag:(*pflag.Flag)(0xc420454dc0)}, "memory":viper.pflagValue{flag:(*pflag.Flag)(0xc420455180)}, "mount":viper.pflagValue{flag:(*pflag.Flag)(0xc420454e60)}, "disable-driver-mounts":viper.pflagValue{flag:(*pflag.Flag)(0xc420454fa0)}, "feature-gates":viper.pflagValue{flag:(*pflag.Flag)(0xc420455e00)}, "hyperv-virtual-switch":viper.pflagValue{flag:(*pflag.Flag)(0xc420455400)}, "iso-url":viper.pflagValue{flag:(*pflag.Flag)(0xc420455040)}, "network-plugin":viper.pflagValue{flag:(*pflag.Flag)(0xc420455d60)}, "vm-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc4204550e0)}, "apiserver-name":viper.pflagValue{flag:(*pflag.Flag)(0xc420455860)}, "disk-size":viper.pflagValue{flag:(*pflag.Flag)(0xc4204552c0)}, "dns-domain":viper.pflagValue{flag:(*pflag.Flag)(0xc420455a40)}, "gpu":viper.pflagValue{flag:(*pflag.Flag)(0xc4200401e0)}, "insecure-registry":viper.pflagValue{flag:(*pflag.Flag)(0xc420455ae0)}, "kvm-network":viper.pflagValue{flag:(*pflag.Flag)(0xc4204554a0)}, "docker-env":viper.pflagValue{flag:(*pflag.Flag)(0xc420455720)}, "container-runtime":viper.pflagValue{flag:(*pflag.Flag)(0xc420455cc0)}, "docker-opt":viper.pflagValue{flag:(*pflag.Flag)(0xc4204557c0)}, "host-only-cidr":viper.pflagValue{flag:(*pflag.Flag)(0xc420455360)}, "kubernetes-version":viper.pflagValue{flag:(*pflag.Flag)(0xc420455c20)}, "nfs-share":viper.pflagValue{flag:(*pflag.Flag)(0xc4204555e0)}, "xhyve-disk-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc420455540)}, "profile":viper.pflagValue{flag:(*pflag.Flag)(0xc420454320)}, "apiserver-names":viper.pflagValue{flag:(*pflag.Flag)(0xc420455900)}, "cache-images":viper.pflagValue{flag:(*pflag.Flag)(0xc420455ea0)}, "cpus":viper.pflagValue{flag:(*pflag.Flag)(0xc420455220)}, "nfs-shares-root":viper.pflagValue{flag:(*pflag.Flag)(0xc420455680)}, "uuid":viper.pflagValue{flag:(*pflag.Flag)(0xc420040000)}, "apiserver-ips":viper.pflagValue{flag:(*pflag.Flag)(0xc4204559a0)}, "extra-config":viper.pflagValue{flag:(*pflag.Flag)(0xc420455f40)}, "hyperkit-vpnkit-sock":viper.pflagValue{flag:(*pflag.Flag)(0xc4200400a0)}}
Env:
map[string]string{}
Key/Value Store:
map[string]interface {}{}
Config:
map[string]interface {}{}
Defaults:
map[string]interface {}{"wantreporterror":false, "wantkubectldownloadmsg":true, "wantnonedriverwarning":true, "showdriverdeprecationnotification":true, "showbootstrapperdeprecationnotification":true, "log_dir":"", "wantupdatenotification":true, "reminderwaitperiodinhours":24, "wantreporterrorprompt":true, "v":"0", "alsologtostderr":"false"}
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 160.27 MB / 160.27 MB [============================================] 100.00% 0s
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:61185
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Creating CA: /Users/max/.minikube/certs/ca.pem
Creating client certificate: /Users/max/.minikube/certs/cert.pem
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading /Users/max/.minikube/cache/boot2docker.iso from file:///Users/max/.minikube/cache/iso/minikube-v0.28.1.iso...
(minikube) DBG | 2018/08/11 22:11:03 [INFO] Creating ssh key...
(minikube) DBG | 2018/08/11 22:11:03 [INFO] Creating raw disk image...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
E0811 22:11:05.580005   21754 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/max/Library/Containers/com.docker.docker/Data/s50: no such file or directory.

 Retrying.
E0811 22:11:05.581311   21754 start.go:180] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/max/Library/Containers/com.docker.docker/Data/s50: no such file or directory
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```
**Anything else do we need to know**:
i execute "minikube start ..." command, after export socket proxy.

**Comment by tstromberg** [comment]
This seems to be representitive of a broken Docker for Mac install. Do you mind running through this and seeing if Docker thinks everything is OK?

https://docs.docker.com/docker-for-mac/troubleshoot/

**Comment by fyuan1316** [comment]
Thanks for your reply, I checked the diagnose information of docker. I found that the check items in the "Logs and troubleshooting" page are somewhat different, and I am not sure if the version is different.

It only prompts for success, does not show the inspection of specific items such as vpnkit, dns, etc.

![image](https://user-images.githubusercontent.com/42265657/45793098-11ea1c00-bcc3-11e8-99a3-4cb6557aa065.png)
![image](https://user-images.githubusercontent.com/42265657/45793105-18789380-bcc3-11e8-94c9-5334dc2c63d0.png)

I can't find docker-diagnose in the installation path.

![image](https://user-images.githubusercontent.com/42265657/45793206-9dfc4380-bcc3-11e8-9544-471856201681.png)

I can't find docker-diagnose in the installation path, but it exists on another computer installed with the edge version "docker for mac". So, maybe it’s a problem caused by different versions of docker, I’ll take the time to try another version.

**Comment by fyuan1316** [comment]
After testing several versions of docker, some of them were able to create "/Users/max/Library/Containers/com.docker.docker/Data/s50" directory, such as this version "Docker Community Edition 18.03.0-ce- Mac59 2018-03-26”.

![image](https://user-images.githubusercontent.com/42265657/45797729-9f386b00-bcd9-11e8-9015-59b71cb73ea1.png)

Unlucky, this has a new error, I posted below. I feel that the docker version has been upgraded to bring the installation file changes, maybe this is a minikube and docker version compatibility issue, I am not too sure.
But fortunately on the other hand, the original intention of my question is that I can do "docker pull" through the proxy in minikube's docker environment. I have found another way, by setting --docker-env to fulfill.
The command is roughly the same: 
```
minikube start --vm-driver hyperkit --docker-env http_proxy=http://$ProxyIP:ProxyPort --docker-env https_proxy=https://$ProxyIP:ProxyPort
```

```
# max ~/gocode/src/github.com/emicklei [13:00:16]
→ minikube start --vm-driver hyperkit -v 10 --hyperkit-vpnkit-sock auto
Aliases:
map[string]string{}
Override:
map[string]interface {}{"v":"10"}
PFlags:
map[string]viper.FlagValue{"disk-size":viper.pflagValue{flag:(*pflag.Flag)(0xc420429d60)}, "hyperkit-vsock-ports":viper.pflagValue{flag:(*pflag.Flag)(0xc42042ebe0)}, "uuid":viper.pflagValue{flag:(*pflag.Flag)(0xc42042eaa0)}, "vm-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc420429b80)}, "extra-config":viper.pflagValue{flag:(*pflag.Flag)(0xc42042ea00)}, "host-only-cidr":viper.pflagValue{flag:(*pflag.Flag)(0xc420429e00)}, "iso-url":viper.pflagValue{flag:(*pflag.Flag)(0xc420429ae0)}, "nfs-shares-root":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e140)}, "registry-mirror":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e640)}, "apiserver-names":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e3c0)}, "cpus":viper.pflagValue{flag:(*pflag.Flag)(0xc420429cc0)}, "keep-context":viper.pflagValue{flag:(*pflag.Flag)(0xc420429860)}, "disable-driver-mounts":viper.pflagValue{flag:(*pflag.Flag)(0xc420429a40)}, "dns-domain":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e500)}, "kubernetes-version":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e6e0)}, "profile":viper.pflagValue{flag:(*pflag.Flag)(0xc420428dc0)}, "apiserver-ips":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e460)}, "container-runtime":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e780)}, "gpu":viper.pflagValue{flag:(*pflag.Flag)(0xc42042ec80)}, "hyperv-virtual-switch":viper.pflagValue{flag:(*pflag.Flag)(0xc420429ea0)}, "mount":viper.pflagValue{flag:(*pflag.Flag)(0xc420429900)}, "mount-string":viper.pflagValue{flag:(*pflag.Flag)(0xc4204299a0)}, "bootstrapper":viper.pflagValue{flag:(*pflag.Flag)(0xc420428e60)}, "cache-images":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e960)}, "nfs-share":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e0a0)}, "docker-env":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e1e0)}, "kvm-network":viper.pflagValue{flag:(*pflag.Flag)(0xc420429f40)}, "memory":viper.pflagValue{flag:(*pflag.Flag)(0xc420429c20)}, "xhyve-disk-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e000)}, "apiserver-name":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e320)}, "docker-opt":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e280)}, "feature-gates":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e8c0)}, "hyperkit-vpnkit-sock":viper.pflagValue{flag:(*pflag.Flag)(0xc42042eb40)}, "insecure-registry":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e5a0)}, "network-plugin":viper.pflagValue{flag:(*pflag.Flag)(0xc42042e820)}}
Env:
map[string]string{}
Key/Value Store:
map[string]interface {}{}
Config:
map[string]interface {}{}
Defaults:
map[string]interface {}{"log_dir":"", "wantupdatenotification":true, "wantreporterrorprompt":true, "showbootstrapperdeprecationnotification":true, "wantnonedriverwarning":true, "showdriverdeprecationnotification":true, "v":"0", "alsologtostderr":"false", "reminderwaitperiodinhours":24, "wantreporterror":false, "wantkubectldownloadmsg":true}
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 160.27 MB / 160.27 MB [============================================] 100.00% 0s
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:52095
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Creating CA: /Users/max/.minikube/certs/ca.pem
Creating client certificate: /Users/max/.minikube/certs/cert.pem
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading /Users/max/.minikube/cache/boot2docker.iso from file:///Users/max/.minikube/cache/iso/minikube-v0.28.1.iso...
(minikube) DBG | 2018/09/20 13:01:25 [INFO] Creating ssh key...
(minikube) DBG | 2018/09/20 13:01:25 [INFO] Creating raw disk image...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
(minikube) Using UUID 38a8b04e-bc92-11e8-a6cb-186590d3186d
(minikube) Generated MAC 82:5d:91:8:96:ff
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) DBG | unexpected fault address 0xb01dfacedebac1e
(minikube) DBG | fatal error: fault
(minikube) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x406edf2]
(minikube) DBG |
(minikube) DBG | goroutine 44 [running]:
(minikube) DBG | runtime.throw(0x4d11b6e, 0x5)
(minikube) DBG | 	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4202f3518 sp=0xc4202f34f8
(minikube) DBG | runtime.sigpanic()
(minikube) DBG | 	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4202f3568 sp=0xc4202f3518
(minikube) DBG | syscall.ByteSliceFromString(0x36393a38303a3139, 0x66663a, 0x4c782c0, 0x300000002, 0xc420065520, 0x38, 0xc8)
(minikube) DBG | 	/usr/local/go/src/syscall/syscall.go:51 +0x32 fp=0xc4202f35c8 sp=0xc4202f3568
(minikube) DBG | syscall.BytePtrFromString(0x36393a38303a3139, 0x66663a, 0x5b004b0, 0x0, 0x4075b75)
(minikube) DBG | 	/usr/local/go/src/syscall/syscall.go:71 +0x39 fp=0xc4202f3610 sp=0xc4202f35c8
(minikube) DBG | syscall.Stat(0x36393a38303a3139, 0x66663a, 0xc4202d1628, 0x100, 0xb0)
(minikube) DBG | 	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1220 +0x3f fp=0xc4202f3690 sp=0xc4202f3610
(minikube) DBG | os.Stat(0x36393a38303a3139, 0x66663a, 0x1, 0x0, 0xc4202f3778, 0x4068b32)
(minikube) DBG | 	/usr/local/go/src/os/stat_unix.go:32 +0x5c fp=0xc4202f36e8 sp=0xc4202f3690
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).execute(0xc42026f980, 0xc4201c92c0, 0x98, 0x1, 0x1)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:233 +0xc0 fp=0xc4202f38c0 sp=0xc4202f36e8
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).Start(0xc42026f980, 0xc4201c92c0, 0x98, 0x1, 0x1)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:220 +0x46 fp=0xc4202f38f8 sp=0xc4202f38c0
(minikube) DBG | k8s.io/minikube/pkg/drivers/hyperkit.(*Driver).Start(0xc420192370, 0xc4202ad480, 0x36)
(minikube) DBG | 	/go/src/k8s.io/minikube/pkg/drivers/hyperkit/driver.go:209 +0x681 fp=0xc4202f3a60 sp=0xc4202f38f8
(minikube) DBG | k8s.io/minikube/pkg/drivers/hyperkit.(*Driver).Create(0xc420192370, 0x4d8aac8, 0xc420032ae0)
(minikube) DBG | 	/go/src/k8s.io/minikube/pkg/drivers/hyperkit/driver.go:101 +0x106 fp=0xc4202f3aa0 sp=0xc4202f3a60
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc4202a8300, 0x5437948, 0x5437948, 0x0, 0x0)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x78 fp=0xc4202f3ac8 sp=0xc4202f3aa0
(minikube) DBG | runtime.call64(0xc4202b10e0, 0xc420122550, 0xc4202b12c0, 0x1800000028)
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc4202f3b18 sp=0xc4202f3ac8
(minikube) DBG | reflect.Value.call(0xc4202a6180, 0xc420122550, 0x13, 0x4d10c2a, 0x4, 0xc420032f20, 0x3, 0x3, 0x2, 0x400d954, ...)
(minikube) DBG | 	/usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc4202f3e60 sp=0xc4202f3b18
(minikube) DBG | reflect.Value.Call(0xc4202a6180, 0xc420122550, 0x13, 0xc420021720, 0x3, 0x3, 0xc420021718, 0x403c661, 0xc420065380)
(minikube) DBG | 	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc4202f3ec8 sp=0xc4202f3e60
(minikube) DBG | net/rpc.(*service).call(0xc4202ac240, 0xc42011c080, 0xc4202a4880, 0xc4202ab200, 0xc4202a8a20, 0x4b738a0, 0x5437948, 0x16, 0x4b738a0, 0x5437948, ...)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:387 +0x144 fp=0xc4202f3f78 sp=0xc4202f3ec8
(minikube) DBG | runtime.goexit()
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4202f3f80 sp=0xc4202f3f78
(minikube) DBG | created by net/rpc.(*Server).ServeCodec
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:481 +0x404
(minikube) DBG |
(minikube) DBG | goroutine 1 [select]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver(0x53ca1e0, 0xc420192370)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:52 +0x61c
(minikube) DBG | main.main()
(minikube) DBG | 	/go/src/k8s.io/minikube/cmd/drivers/hyperkit/main.go:25 +0xcf
(minikube) DBG |
(minikube) DBG | goroutine 17 [syscall, locked to thread]:
(minikube) DBG | runtime.goexit()
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
(minikube) DBG |
(minikube) DBG | goroutine 34 [syscall]:
(minikube) DBG | os/signal.signal_recv(0x42c82db)
(minikube) DBG | 	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
(minikube) DBG | os/signal.loop()
(minikube) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
(minikube) DBG | created by os/signal.init.1
(minikube) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
(minikube) DBG |
(minikube) DBG | goroutine 35 [chan receive]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x541a860)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d
(minikube) DBG |
(minikube) DBG | goroutine 36 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5bc92e0, 0x72, 0x0)
(minikube) DBG | 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc4202a18e8, 0x72, 0x0, 0xc4200d0de0)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc4202a18e8, 0xffffffffffffffff, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).accept(0xc4202a1880, 0x0, 0x53b0e00, 0xc4200d0de0)
(minikube) DBG | 	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
(minikube) DBG | net.(*TCPListener).accept(0xc420122600, 0xc42014ae90, 0x427e57e, 0x40527c0)
(minikube) DBG | 	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
(minikube) DBG | net.(*TCPListener).Accept(0xc420122600, 0x4d8bc50, 0xc4200e0b40, 0x53c6040, 0xc4200779e0)
(minikube) DBG | 	/usr/local/go/src/net/tcpsock.go:228 +0x49
(minikube) DBG | net/http.(*Server).Serve(0xc4200ab3f0, 0x53c52c0, 0xc420122600, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2643 +0x228
(minikube) DBG | net/http.Serve(0x53c52c0, 0xc420122600, 0x0, 0x0, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2307 +0x78
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:49 +0x42a
(minikube) DBG |
(minikube) DBG | goroutine 20 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5bc9220, 0x72, 0x6)
(minikube) DBG | 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc4200ea1b8, 0x72, 0x53b2900, 0x53ac740)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc4200ea1b8, 0xc4202cc000, 0x1000)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).Read(0xc4200ea150, 0xc4202cc000, 0x1000, 0x1000, 0x0, 0x53b2900, 0x53ac740)
(minikube) DBG | 	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
(minikube) DBG | net.(*conn).Read(0xc4200820b8, 0xc4202cc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/net.go:181 +0x70
(minikube) DBG | bufio.(*Reader).Read(0xc4202a7320, 0xc4202a4860, 0x1, 0x9, 0xc420113680, 0xc420113690, 0x4029a01)
(minikube) DBG | 	/usr/local/go/src/bufio/bufio.go:213 +0x312
(minikube) DBG | io.ReadAtLeast(0x53ade40, 0xc4202a7320, 0xc4202a4860, 0x1, 0x9, 0x1, 0x4b738a0, 0x42a9201, 0x3)
(minikube) DBG | 	/usr/local/go/src/io/io.go:307 +0xa9
(minikube) DBG | io.ReadFull(0x53ade40, 0xc4202a7320, 0xc4202a4860, 0x1, 0x9, 0x40297b6, 0x0, 0x7)
(minikube) DBG | 	/usr/local/go/src/io/io.go:325 +0x58
(minikube) DBG | encoding/gob.decodeUintReader(0x53ade40, 0xc4202a7320, 0xc4202a4860, 0x9, 0x9, 0xc420113790, 0x40290ee, 0xc400000008, 0xc4200796c0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decode.go:119 +0x63
(minikube) DBG | encoding/gob.(*Decoder).recvMessage(0xc4202abe00, 0xc4201137a0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:76 +0x57
(minikube) DBG | encoding/gob.(*Decoder).decodeTypeSequence(0xc4202abe00, 0x4d8c300, 0xc4202abe00)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:140 +0x167
(minikube) DBG | encoding/gob.(*Decoder).DecodeValue(0xc4202abe00, 0x4b6e6e0, 0xc4202a84a0, 0x16, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:208 +0xe8
(minikube) DBG | encoding/gob.(*Decoder).Decode(0xc4202abe00, 0x4b6e6e0, 0xc4202a84a0, 0x0, 0xc42011c0a0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:185 +0x16d
(minikube) DBG | net/rpc.(*gobServerCodec).ReadRequestHeader(0xc4202b0330, 0xc4202a84a0, 0x4bd2140, 0x5437948)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:407 +0x45
(minikube) DBG | net/rpc.(*Server).readRequestHeader(0xc42011c080, 0x53c6400, 0xc4202b0330, 0x5437948, 0x16, 0xc4202a8a20, 0x541b401, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:580 +0x6c
(minikube) DBG | net/rpc.(*Server).readRequest(0xc42011c080, 0x53c6400, 0xc4202b0330, 0xc42011c080, 0xc4202a4880, 0xc4202ab200, 0xc4202a8a20, 0x4b738a0, 0x5437948, 0x16, ...)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:547 +0x5a
(minikube) DBG | net/rpc.(*Server).ServeCodec(0xc42011c080, 0x53c6400, 0xc4202b0330)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:466 +0x77
(minikube) DBG | net/rpc.(*Server).ServeConn(0xc42011c080, 0x5bc94a0, 0xc4200820b8)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:458 +0x373
(minikube) DBG | net/rpc.(*Server).ServeHTTP(0xc42011c080, 0x53c54c0, 0xc4202be000, 0xc42006e600)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:700 +0x42a
(minikube) DBG | net/http.(*ServeMux).ServeHTTP(0x541a000, 0x53c54c0, 0xc4202be000, 0xc42006e600)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2238 +0x130
(minikube) DBG | net/http.serverHandler.ServeHTTP(0xc4200ab3f0, 0x53c54c0, 0xc4202be000, 0xc42006e600)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2568 +0x92
(minikube) DBG | net/http.(*conn).serve(0xc4200e0b40, 0x53c5f80, 0xc420079700)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:1825 +0x612
(minikube) DBG | created by net/http.(*Server).Serve
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
E0920 13:01:28.062658   11273 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF.

 Retrying.
E0920 13:01:28.063656   11273 start.go:180] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```

**Comment by m0ppers** [comment]
got the exact same problem. I can workaround the issue by creating a new minikube like so:

`minikube start --cpus 4 --disk-size 60g --memory 8192 -v=7 --vm-driver=hyperkit --hyperkit-vpnkit-sock=/Users/mop/Library/Containers/com.docker.docker/Data/vpnkit.eth.sock`

This way my vpn connection also works within minikube

**Comment by tstromberg** [comment]
> E0920 13:01:28.062658   11273 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF.

This separate bug is #3096, and seems to be due to the hyperkit driver crashing.

**Comment by braderhart** [comment]
I was able to get this working by using the Docker for Mac hyperkit. However, I still cannot use Minikube behind corporate VPN, but Docker for Mac Kubernetes works.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
