### ISSUE TITLE
Error in driver during machine creation: unexpected EOF (hyperkit SIGSEGV)

### ISSUE THREAD

**Issue by jerneyio** [kubernetes/minikube#3096]
BUG REPORT

Please provide the following details:

**Environment**: Mid-2015 MBP

**Minikube version** (use `minikube version`): v0.28.2
- **OS** (e.g. from /etc/os-release): OS X 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.28.1.iso
- **Install tools**: `brew`
- **Others**: N/A

**What happened**:
When running `minikube start --vm-driver=hyperkit --disk-size=10g` I get the following output:

```
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 160.27 MB / 160.27 MB [============================================] 100.00% 0s
E0827 12:49:10.980153   55310 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF.
```
Initial, when running this command, I received an error that there wasn't enough space on my device, hence the `disk-size` flag. That got me past the storage space issue. Then I ran `rm -rf ~/.minikube` and tried again (`minikube start...`, but received the above error instead.

I've tried what was prescribed here: https://github.com/kubernetes/minikube/issues/867

**What you expected to happen**: I expected the command to start Minikube

**How to reproduce it** (as minimally and precisely as possible):
For me, it was just a matter of following these instructions: https://kubernetes.io/docs/tutorials/hello-minikube/

**Output of `minikube logs` (if applicable)**:
```
F0828 07:37:16.948685   99692 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Thanks in advance for your time!

**Comment by davidnewman** [comment]
Just to add to this, some of the folks I work with are also getting this issue. Here is the output when running minikube 0.28.0 on a MPB 15:

```
[someuser in ~/envy on ]$ ^G^G^G^Gminikube start --vm-driver=hyperkit -v 100
Aliases:
map[string]string{}
Override:
map[string]interface {}{"v":"100"}
PFlags:
map[string]viper.FlagValue{"hyperkit-vpnkit-sock":viper.pflagValue{flag:(*pflag.Flag)(0xc42041aaa0)}, "hyperv-virtual-switch":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9a40)}, "network-plugin":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a780)}, "apiserver-ips":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a000)}, "disk-size":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9860)}, "docker-opt":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9e00)}, "iso-url":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c94a0)}, "uuid":viper.pflagValue{flag:(*pflag.Flag)(0xc42041aa00)}, "keep-context":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c90e0)}, "memory":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9720)}, "hyperkit-vsock-ports":viper.pflagValue{flag:(*pflag.Flag)(0xc42041ab40)}, "mount-string":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9360)}, "apiserver-names":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9f40)}, "cache-images":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a8c0)}, "container-runtime":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a640)}, "vm-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c95e0)}, "bootstrapper":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c86e0)}, "apiserver-name":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9ea0)}, "mount":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9220)}, "host-only-cidr":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c99a0)}, "insecure-registry":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a280)}, "nfs-shares-root":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9cc0)}, "cpus":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c97c0)}, "dns-domain":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a140)}, "extra-config":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a960)}, "nfs-share":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9c20)}, "profile":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c8640)}, "disable-driver-mounts":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9400)}, "kvm-network":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9ae0)}, "registry-mirror":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a3c0)}, "xhyve-disk-driver":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9b80)}, "docker-env":viper.pflagValue{flag:(*pflag.Flag)(0xc4204c9d60)}, "feature-gates":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a820)}, "kubernetes-version":viper.pflagValue{flag:(*pflag.Flag)(0xc42041a500)}}
Env:
map[string]string{}
Key/Value Store:
map[string]interface {}{}
Config:
map[string]interface {}{}
Defaults:
map[string]interface {}{"wantreporterror":false, "wantnonedriverwarning":true, "showdriverdeprecationnotification":true, "v":"0", "alsologtostderr":"false", "reminderwaitperiodinhours":24, "wantreporterrorprompt":true, "wantkubectldownloadmsg":true, "showbootstrapperdeprecationnotification":true, "log_dir":"", "wantupdatenotification":true}
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO

<removing download output>

Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:50785
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Creating CA: /Users/someuser/.minikube/certs/ca.pem
Creating client certificate: /Users/someuser/.minikube/certs/cert.pem
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading /Users/someuser/.minikube/cache/boot2docker.iso from file:///Users/pventuri/.minikube/cache/iso/minikube-v0.28.0.iso...
(minikube) DBG | 2018/09/10 13:45:51 [INFO] Creating ssh key...
(minikube) DBG | 2018/09/10 13:45:51 [INFO] Creating raw disk image...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
(minikube) Using UUID 5baab2a4-b521-11e8-a314-34363bccc346
(minikube) Generated MAC 7e:c8:4c:1c:c8:71
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) DBG | unexpected fault address 0xb01dfacedebac1e
(minikube) DBG | fatal error: fault
(minikube) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x406edf2]
(minikube) DBG |
(minikube) DBG | goroutine 22 [running]:
(minikube) DBG | runtime.throw(0x4d11b6e, 0x5)
(minikube) DBG |        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4202c7518 sp=0xc4202c74f8
(minikube) DBG | runtime.sigpanic()
(minikube) DBG |        /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4202c7568 sp=0xc4202c7518
(minikube) DBG | syscall.ByteSliceFromString(0x373a38633a63313a, 0x31, 0x4c782c0, 0x300000002, 0xc4201181a0, 0x38, 0xc8)
(minikube) DBG |        /usr/local/go/src/syscall/syscall.go:51 +0x32 fp=0xc4202c75c8 sp=0xc4202c7568
(minikube) DBG | syscall.BytePtrFromString(0x373a38633a63313a, 0x31, 0x5c00960, 0x0, 0x4075b75)
(minikube) DBG |        /usr/local/go/src/syscall/syscall.go:71 +0x39 fp=0xc4202c7610 sp=0xc4202c75c8
(minikube) DBG | syscall.Stat(0x373a38633a63313a, 0x31, 0xc42028d488, 0x100, 0xb0)
(minikube) DBG |        /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1220 +0x3f fp=0xc4202c7690 sp=0xc4202c7610
(minikube) DBG | os.Stat(0x373a38633a63313a, 0x31, 0x2, 0x0, 0xc4202c7778, 0x4068b32)
(minikube) DBG |        /usr/local/go/src/os/stat_unix.go:32 +0x5c fp=0xc4202c76e8 sp=0xc4202c7690
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).execute(0xc4203d0000, 0xc42016ff40, 0x98, 0x1, 0x1)
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:233 +0xc0 fp=0xc4202c78c0 sp=0xc4202c76e8
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).Start(0xc4203d0000, 0xc42016ff40, 0x98, 0x1, 0x1)
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:220 +0x46 fp=0xc4202c78f8 sp=0xc4202c78c0
(minikube) DBG | k8s.io/minikube/pkg/drivers/hyperkit.(*Driver).Start(0xc42001b550, 0xc420114d40, 0x3b)
(minikube) DBG |        /go/src/k8s.io/minikube/pkg/drivers/hyperkit/driver.go:209 +0x681 fp=0xc4202c7a60 sp=0xc4202c78f8
(minikube) DBG | k8s.io/minikube/pkg/drivers/hyperkit.(*Driver).Create(0xc42001b550, 0x4d8aac8, 0xc42003cae0)
(minikube) DBG |        /go/src/k8s.io/minikube/pkg/drivers/hyperkit/driver.go:101 +0x106 fp=0xc4202c7aa0 sp=0xc4202c7a60
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc4201d7320, 0x5437948, 0x5437948, 0x0, 0x0)
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x78 fp=0xc4202c7ac8 sp=0xc4202c7aa0
(minikube) DBG | runtime.call64(0xc420288030, 0xc42000e640, 0xc420288210, 0x1800000028)
(minikube) DBG |        /usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc4202c7b18 sp=0xc4202c7ac8
(minikube) DBG | reflect.Value.call(0xc4202643c0, 0xc42000e640, 0x13, 0x4d10c2a, 0x4, 0xc42003cf20, 0x3, 0x3, 0x0, 0x0, ...)
(minikube) DBG |        /usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc4202c7e60 sp=0xc4202c7b18
(minikube) DBG | reflect.Value.Call(0xc4202643c0, 0xc42000e640, 0x13, 0xc42002af20, 0x3, 0x3, 0x0, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc4202c7ec8 sp=0xc4202c7e60
(minikube) DBG | net/rpc.(*service).call(0xc420239b80, 0xc4200159c0, 0xc420257ee0, 0xc42025f580, 0xc4201d7b00, 0x4b738a0, 0x5437948, 0x16, 0x4b738a0, 0x5437948, ...)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:387 +0x144 fp=0xc4202c7f78 sp=0xc4202c7ec8
(minikube) DBG | runtime.goexit()
(minikube) DBG |        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4202c7f80 sp=0xc4202c7f78
(minikube) DBG | created by net/rpc.(*Server).ServeCodec
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:481 +0x404
(minikube) DBG |
(minikube) DBG | goroutine 1 [select]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver(0x53ca1e0, 0xc42001b550)
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:52 +0x61c
(minikube) DBG | main.main()
(minikube) DBG |        /go/src/k8s.io/minikube/cmd/drivers/hyperkit/main.go:25 +0xcf
(minikube) DBG |
(minikube) DBG | goroutine 17 [syscall, locked to thread]:
(minikube) DBG | runtime.goexit()
(minikube) DBG |        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
(minikube) DBG |
(minikube) DBG | goroutine 6 [syscall]:
(minikube) DBG | os/signal.signal_recv(0x42c82db)
(minikube) DBG |        /usr/local/go/src/runtime/sigqueue.go:116 +0xff
(minikube) DBG | os/signal.loop()
(minikube) DBG |        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
(minikube) DBG | created by os/signal.init.1
(minikube) DBG |        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
(minikube) DBG |
(minikube) DBG | goroutine 7 [chan receive]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x541a860)
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d
(minikube) DBG |
(minikube) DBG | goroutine 8 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5c48f98, 0x72, 0x0)
(minikube) DBG |        /usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc42025da38, 0x72, 0x0, 0xc4201d7520)
(minikube) DBG |        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc42025da38, 0xffffffffffffffff, 0x0)
(minikube) DBG |        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).accept(0xc42025d9d0, 0x0, 0x53b0e00, 0xc4201d7520)
(minikube) DBG |        /usr/local/go/src/net/fd_unix.go:430 +0x1e5
(minikube) DBG | net.(*TCPListener).accept(0xc42000e6f0, 0xc420030e90, 0x427e57e, 0x40527c0)
(minikube) DBG |        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
(minikube) DBG | net.(*TCPListener).Accept(0xc42000e6f0, 0x4d8bc50, 0xc42016fd60, 0x53c6040, 0xc42026a210)
(minikube) DBG |        /usr/local/go/src/net/tcpsock.go:228 +0x49
(minikube) DBG | net/http.(*Server).Serve(0xc42001b600, 0x53c52c0, 0xc42000e6f0, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/net/http/server.go:2643 +0x228
(minikube) DBG | net/http.Serve(0x53c52c0, 0xc42000e6f0, 0x0, 0x0, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/net/http/server.go:2307 +0x78
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver
(minikube) DBG |        /go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:49 +0x42a
(minikube) DBG |
(minikube) DBG | goroutine 9 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5c48ed8, 0x72, 0x6)
(minikube) DBG |        /usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc42025daa8, 0x72, 0x53b2900, 0x53ac740)
(minikube) DBG |        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc42025daa8, 0xc42027c000, 0x1000)
(minikube) DBG |        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).Read(0xc42025da40, 0xc42027c000, 0x1000, 0x1000, 0x0, 0x53b2900, 0x53ac740)
(minikube) DBG |        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
(minikube) DBG | net.(*conn).Read(0xc42000e6f8, 0xc42027c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/net/net.go:181 +0x70
(minikube) DBG | bufio.(*Reader).Read(0xc420265680, 0xc420257e75, 0x1, 0x9, 0xc4200ff680, 0xc4200ff690, 0x4029a01)
(minikube) DBG |        /usr/local/go/src/bufio/bufio.go:213 +0x312
(minikube) DBG | io.ReadAtLeast(0x53ade40, 0xc420265680, 0xc420257e75, 0x1, 0x9, 0x1, 0x4b738a0, 0x42a9201, 0x3)
(minikube) DBG |        /usr/local/go/src/io/io.go:307 +0xa9
(minikube) DBG | io.ReadFull(0x53ade40, 0xc420265680, 0xc420257e75, 0x1, 0x9, 0x40297b6, 0x0, 0x4)
(minikube) DBG |        /usr/local/go/src/io/io.go:325 +0x58
(minikube) DBG | encoding/gob.decodeUintReader(0x53ade40, 0xc420265680, 0xc420257e75, 0x9, 0x9, 0xc4200ff790, 0x40290ee, 0xc400000008, 0xc4200157c0)
(minikube) DBG |        /usr/local/go/src/encoding/gob/decode.go:119 +0x63
(minikube) DBG | encoding/gob.(*Decoder).recvMessage(0xc42026c200, 0xc4200ff7a0)
(minikube) DBG |        /usr/local/go/src/encoding/gob/decoder.go:76 +0x57
(minikube) DBG | encoding/gob.(*Decoder).decodeTypeSequence(0xc42026c200, 0x4d8c300, 0xc42026c200)
(minikube) DBG |        /usr/local/go/src/encoding/gob/decoder.go:140 +0x167
(minikube) DBG | encoding/gob.(*Decoder).DecodeValue(0xc42026c200, 0x4b6e6e0, 0xc4201d7580, 0x16, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/encoding/gob/decoder.go:208 +0xe8
(minikube) DBG | encoding/gob.(*Decoder).Decode(0xc42026c200, 0x4b6e6e0, 0xc4201d7580, 0x0, 0xc4200159e0)
(minikube) DBG |        /usr/local/go/src/encoding/gob/decoder.go:185 +0x16d
(minikube) DBG | net/rpc.(*gobServerCodec).ReadRequestHeader(0xc42026a4e0, 0xc4201d7580, 0x4bd2140, 0x5437948)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:407 +0x45
(minikube) DBG | net/rpc.(*Server).readRequestHeader(0xc4200159c0, 0x53c6400, 0xc42026a4e0, 0x5437948, 0x16, 0xc4201d7b00, 0xc420032c01, 0x0, 0x0)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:580 +0x6c
(minikube) DBG | net/rpc.(*Server).readRequest(0xc4200159c0, 0x53c6400, 0xc42026a4e0, 0xc4200159c0, 0xc420257ee0, 0xc42025f580, 0xc4201d7b00, 0x4b738a0, 0x5437948, 0x16, ...)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:547 +0x5a
(minikube) DBG | net/rpc.(*Server).ServeCodec(0xc4200159c0, 0x53c6400, 0xc42026a4e0)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:466 +0x77
(minikube) DBG | net/rpc.(*Server).ServeConn(0xc4200159c0, 0x5c4d180, 0xc42000e6f8)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:458 +0x373
(minikube) DBG | net/rpc.(*Server).ServeHTTP(0xc4200159c0, 0x53c54c0, 0xc420144a80, 0xc4201be800)
(minikube) DBG |        /usr/local/go/src/net/rpc/server.go:700 +0x42a
(minikube) DBG | net/http.(*ServeMux).ServeHTTP(0x541a000, 0x53c54c0, 0xc420144a80, 0xc4201be800)
(minikube) DBG |        /usr/local/go/src/net/http/server.go:2238 +0x130
(minikube) DBG | net/http.serverHandler.ServeHTTP(0xc42001b600, 0x53c54c0, 0xc420144a80, 0xc4201be800)
(minikube) DBG |        /usr/local/go/src/net/http/server.go:2568 +0x92
(minikube) DBG | net/http.(*conn).serve(0xc42016fd60, 0x53c5f80, 0xc420239c00)
(minikube) DBG |        /usr/local/go/src/net/http/server.go:1825 +0x612
(minikube) DBG | created by net/http.(*Server).Serve
(minikube) DBG |        /usr/local/go/src/net/http/server.go:2668 +0x2ce
E0910 13:45:54.095656    7497 start.go:168] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF.

 Retrying.
E0910 13:45:54.097122    7497 start.go:174] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: unexpected EOF
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
```

**Comment by vxavictor513** [comment]
I'm getting the exact same error here, but I didn't get the storage space issue beforehand.
It was still working few days ago, then it stopped working out of sudden.

Has anyone successfully resolved it? If not, what are the information that you need? Maybe I can help to provide more logs.

**Comment by vxavictor513** [comment]
Turned out it was because I included a Python bin folder in my system path.

Not sure which Python package is interfering with Hyperkit, but it is now working after commenting out the following command in `~/.bash_profile`.
```
export PATH=~/Library/Python/2.7/bin:$PATH
```

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release, so long as the hyperkit driver has been updated as well using:

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
&& sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/
```

Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!

**Comment by kiranbaddi** [comment]
I am using minikube version: v1.5.2 and yet I get the same error when I am trying to start minikube.
I have also updated the hyperkit drivers as suggested by @tstromberg

**Comment by technolingo** [comment]
Me too, tried updating hyperkit as above. Didn't work. :(

**Comment by technolingo** [comment]
Update: The issue seems unrelated to hyperkit as it also occurred with virtualbox:

```
~ $ minikube start --vm-driver=virtualbox
😄  minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1ec130f]

goroutine 78 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc000236300, 0xa, 0xc00023630b, 0x17, 0xc000236323, 0x7, 0x0, 0x0, 0xc000469c68, ...)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc000236300, 0x2a, 0xc00002c9c0, 0x51, 0x0, 0x0)
	/app/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc00012ef68, 0x0)
	/app/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006a0510, 0xc0006a05a0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

**Comment by js00070** [comment]
> Update: The issue seems unrelated to hyperkit as it also occurred with virtualbox:
> 
> ```
> ~ $ minikube start --vm-driver=virtualbox
> 😄  minikube v1.6.2 on Darwin 10.15.2
> ✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
> 💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> 🏃  Using the running virtualbox "minikube" VM ...
> ⌛  Waiting for the host to be provisioned ...
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1ec130f]
> 
> goroutine 78 [running]:
> github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc000236300, 0xa, 0xc00023630b, 0x17, 0xc000236323, 0x7, 0x0, 0x0, 0xc000469c68, ...)
> 	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
> k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc000236300, 0x2a, 0xc00002c9c0, 0x51, 0x0, 0x0)
> 	/app/pkg/minikube/machine/cache_images.go:395 +0x5df
> k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc00012ef68, 0x0)
> 	/app/pkg/minikube/machine/cache_images.go:85 +0x124
> golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006a0510, 0xc0006a05a0)
> 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
> created by golang.org/x/sync/errgroup.(*Group).Go
> 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
> ```

I have the same problem on debian9
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

```
$ minikube start
😄  Debian 9.0 上的 minikube v1.6.2
✨  Automatically selected the 'virtualbox' driver (alternates: [none])
🔥  正在创建 virtualbox 虚拟机（CPUs=2，Memory=2000MB, Disk=20000MB）...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12b4e4f]

goroutine 49 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc0007d01e0, 0xa, 0xc0007d01eb, 0xe, 0xc0007d01fa, 0x7, 0x0, 0x0, 0xc000449c68, ...)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc0007d01e0, 0x21, 0xc00082a0a0, 0x42, 0x0, 0x0)
	/app/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0002cdf68, 0x1)
	/app/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006e1c20, 0xc0006e1c80)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```
