### ISSUE TITLE
panic from kubeconfig/config.go decode: convertToVersion: assignment to entry in nil map

### ISSUE THREAD

**Issue by RameshRM** [kubernetes/minikube#3146]
Installed `minikube` with brew and followed all possible directions , still wont start. Any pointers?

```
minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
panic: assignment to entry in nil map
```

```
goroutine 1 [running]:
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func17(0xc4200985a8, 0xc420545ca8, 0x2823b80, 0xc42044f8b0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:201 +0x195
reflect.Value.call(0x1e3baa0, 0x205dd20, 0x13, 0x1fbff7f, 0x4, 0xc4205e27a8, 0x3, 0x3, 0x10c0166, 0x1f0f480, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x1e3baa0, 0x205dd20, 0x13, 0xc4205e27a8, 0x3, 0x3, 0xc4205e27a8, 0x148e22c, 0x282bf20)
	/usr/local/go/src/reflect/value.go:302 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc42015cd90, 0x1d97a80, 0xc4200985a8, 0x16, 0x1daf340, 0xc420545ca8, 0x16, 0x1e3baa0, 0x205dd20, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x29f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc42015cd90, 0x1dc2640, 0xc4200985a8, 0x197, 0x1e48160, 0xc420545ca8, 0x195, 0xc42044f8b0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x4ae
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convertKV(0xc42015cd90, 0x2821780, 0xc420087b20, 0x2821780, 0xc420087b40, 0xc42044f8b0, 0x1, 0x2)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:836 +0x67f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert(0xc42015cd90, 0x1ea5120, 0xc4200985a0, 0x199, 0x1ea4cc0, 0xc420545ca0, 0x199, 0xc42044f8b0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:621 +0xed9
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).(k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.defaultConvert)-fm(0x1ea5120, 0xc4200985a0, 0x199, 0x1ea4cc0, 0xc420545ca0, 0x199, 0xc42044f8b0, 0x1, 0x103b6a3)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:492 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc42015cd90, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x4, 0xc420087a80, 0xc4205e2f40, 0x0, 0x2823b80)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2c3
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).DefaultConvert(0xc42015cd90, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x4, 0xc420087a80, 0x0, 0xc4205e3048)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:492 +0x95
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*scope).DefaultConvert(0xc42044f860, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x4, 0xc4205e3020, 0x1011acc)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:280 +0x70
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func3(0xc4200985a0, 0xc420545ca0, 0x2823b80, 0xc42044f860, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:36 +0x66
reflect.Value.call(0x1e3d6c0, 0x205dd40, 0x13, 0x1fbff7f, 0x4, 0xc4205e33f8, 0x3, 0x3, 0x10c0166, 0x1f0f480, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x1e3d6c0, 0x205dd40, 0x13, 0xc4205e33f8, 0x3, 0x3, 0xc4205e33f8, 0x148e22c, 0x282bf20)
	/usr/local/go/src/reflect/value.go:302 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc42015cd90, 0x1e5a100, 0xc4200985a0, 0x16, 0x1e59b80, 0xc420545ca0, 0x16, 0x1e3d6c0, 0x205dd40, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x29f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc42015cd90, 0x1ea5120, 0xc4200985a0, 0x199, 0x1ea4cc0, 0xc420545ca0, 0x199, 0xc42044f860, 0xc420055340, 0xc42044f860)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x4ae
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).(k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.convert)-fm(0x1ea5120, 0xc4200985a0, 0x199, 0x1ea4cc0, 0xc420545ca0, 0x199, 0xc42044f860, 0x1, 0x1ea8fa0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc42015cd90, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x0, 0xc420087a80, 0xc4205e37a0, 0x1d26f9b, 0x1f0f4c8)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2c3
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc42015cd90, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x0, 0xc420087a80, 0xc42044f810, 0x2823b80)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0xb6
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*scope).Convert(0xc42044f810, 0x1e5a100, 0xc4200985a0, 0x1e59b80, 0xc420545ca0, 0x0, 0xc4203288b0, 0x1f0f480)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:274 +0x70
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func9(0xc420098580, 0xc420545c80, 0x2823b80, 0xc42044f810, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:56 +0xa0
reflect.Value.call(0x1e3d600, 0x205dd70, 0x13, 0x1fbff7f, 0x4, 0xc4205e3c78, 0x3, 0x3, 0x10c0166, 0x1f0f480, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x1e3d600, 0x205dd70, 0x13, 0xc4205e3c78, 0x3, 0x3, 0xc4205e3c78, 0x148e22c, 0x282bf20)
	/usr/local/go/src/reflect/value.go:302 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc42015cd90, 0x1ebfa00, 0xc420098580, 0x16, 0x1ebf940, 0xc420545c80, 0x16, 0x1e3d600, 0x205dd70, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x29f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc42015cd90, 0x1f41940, 0xc420098580, 0x199, 0x1f41820, 0xc420545c80, 0x199, 0xc42044f810, 0xc420055280, 0xc42044f810)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x4ae
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).(k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.convert)-fm(0x1f41940, 0xc420098580, 0x199, 0x1f41820, 0xc420545c80, 0x199, 0xc42044f810, 0x1, 0x1f41820)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc42015cd90, 0x1ebfa00, 0xc420098580, 0x1ebf940, 0xc420545c80, 0x0, 0xc420087a80, 0xc4205e4020, 0x1008223, 0xc4205e41f0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2c3
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc42015cd90, 0x1ebfa00, 0xc420098580, 0x1ebf940, 0xc420545c80, 0x0, 0xc420087a80, 0x2811980, 0xc420545c80)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0xb6
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc420054f00, 0x2cb3500, 0x2811a00, 0xc420098580, 0x280b580, 0x28b1e60, 0xc4202cac7a, 0x200, 0x200, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:572 +0xb1a
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).UnsafeConvertToVersion(0xc420054f00, 0x2811a00, 0xc420098580, 0x280b580, 0x28b1e60, 0x1ebfa00, 0xc420098580, 0x282bf20, 0x1ebfa00)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:499 +0x5f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.unsafeObjectConvertor.ConvertToVersion(0xc420054f00, 0x2811a00, 0xc420098580, 0x280b580, 0x28b1e60, 0x0, 0x0, 0x2811a00, 0xc420098580)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/helper.go:39 +0x57
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc420108b80, 0xc4202ca000, 0xc7a, 0xe7a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x205e160, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:153 +0x7ca
k8s.io/minikube/pkg/util/kubeconfig.decode(0xc4202ca000, 0xc7a, 0xe7a, 0xc7a, 0xe7a, 0x0)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:188 +0x315
k8s.io/minikube/pkg/util/kubeconfig.ReadConfigOrNew(0xc420011220, 0x1f, 0x2, 0xc4201d0460, 0x1df1140)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:129 +0xcd
k8s.io/minikube/pkg/util/kubeconfig.SetupKubeConfig(0xc4201402a0, 0xc420011220, 0x1f)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:104 +0x1a3
k8s.io/minikube/cmd/minikube/cmd.runStart(0x28817a0, 0x28b22e0, 0x0, 0x0)
	/go/src/k8s.io/minikube/cmd/minikube/cmd/start.go:291 +0x1b55
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x28817a0, 0x28b22e0, 0x0, 0x0, 0x28817a0, 0x28b22e0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2880bc0, 0x0, 0x28b2200, 0xc420113f30)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x2880bc0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:105 +0x2d
main.main()
	/go/src/k8s.io/minikube/cmd/minikube/main.go:41 +0x99

```

**Comment by tstromberg** [comment]
Hey Ramesh! Sorry to hear that minikube crashed, and thank you for the backtrace. This seems to be a new crash for us, so it would be nice to get additional debugging information. Do you mind attaching the output of:

```minikube logs```

If possible, it would be nice to get more verbose logs:

```minikube start --v=7 --alsologtostderr"

Hopefully that will provide us enough information to duplicate the issue. 

I assume from the command line you provided, that Virtual Box is your VM driver. Is that correct? Did you provide any additional flags to the "minikube start" command?

**Comment by RameshRM** [comment]
[minikube2.log](https://github.com/kubernetes/minikube/files/2403806/minikube2.log)
Uploaded verbose log

**Comment by tstromberg** [comment]
Excellent. I believe the problem is that we are unable to parse an entry out of your  /Users/ramahadevan/.kube/config file. Do you mind attaching this file to the issue so that we can replicate the bug locally?

(Please check first that there is no confidential information in the file!)

**Comment by RameshRM** [comment]
would exixsting `kube` config conflict w/`minikube` ?

**Comment by RameshRM** [comment]
[config.txt](https://github.com/kubernetes/minikube/files/2403828/config.txt)

**Comment by tstromberg** [comment]
minikube does add entries to ~/.kube/config, but it isn't supposed to conflict otherwise. Clearly we may have an example here where it does though, but that is definitely a bug.

**Comment by RameshRM** [comment]
> Excellent. I believe the problem is that we are unable to parse an entry listed in /Users/ramahadevan/.kube/config. Do you mind attaching this file to the issue so that we can replicate the bug locally?
> 
> (Please check first that there is no confidential information in the file!).
> 
> In the mean time, one possible workaround might be to temporarily rename this file to config.old, and reset the minikube environment:
> 
> ```shell
> mv /Users/ramahadevan/.kube/config{,.old}
> minikube delete
> minikube start
> ```

+1 This worked

**Comment by tstromberg** [comment]
Thanks @RameshRM - I can confirm that copying your config.txt attachment to ~/.kube/config still results in a panic with minikube v0.33.1:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func17(0xc000508188, 0xc0000bd468, 0x1531fe0, 0xc0000c1090, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:215 +0x1f3
reflect.Value.call(0x1201180, 0x142af78, 0x13, 0x1387050, 0x4, 0xc000958c30, 0x3, 0x3, 0x4c3b8a, 0x11ef7e0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x1201180, 0x142af78, 0x13, 0xc000958c30, 0x3, 0x3, 0x1b, 0x8, 0xc000958c30)
	/usr/local/go/src/reflect/value.go:308 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc000169650, 0x11534e0, 0xc000508188, 0x16, 0x11ef7e0, 0xc0000bd468, 0x195, 0x1201180, 0x142af78, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x2ad
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc000169650, 0x117b540, 0xc000508188, 0x197, 0x11ef7e0, 0xc0000bd468, 0x195, 0xc0000c1090, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x45b
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convertKV(0xc000169650, 0x152c640, 0xc0000e06c0, 0x152c640, 0xc0000e06e0, 0xc0000c1090, 0x1, 0x2)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:836 +0x664
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert(0xc000169650, 0x126af80, 0xc000508180, 0x199, 0x126ab20, 0xc0000bd460, 0x199, 0xc0000c1090, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:621 +0x176c
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert-fm(0x126af80, 0xc000508180, 0x199, 0x126ab20, 0xc0000bd460, 0x199, 0xc0000c1090, 0x1, 0x12676a0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:492 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc000169650, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x4, 0xc0000e0620, 0xc0009592a8, 0x12676a0, 0x12d9800)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2cf
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).DefaultConvert(0xc000169650, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x4, 0xc0000e0620, 0x12676a0, 0x12d9800)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:492 +0x9d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*scope).DefaultConvert(0xc0000c1040, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x4, 0x7f4549c45d80, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:280 +0x70
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func3(0xc000508180, 0xc0000bd460, 0x1531fe0, 0xc0000c1040, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:37 +0x66
reflect.Value.call(0x12031c0, 0x142af98, 0x13, 0x1387050, 0x4, 0xc000959760, 0x3, 0x3, 0x4c3b8a, 0x126ab20, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x12031c0, 0x142af98, 0x13, 0xc000959760, 0x3, 0x3, 0xc8, 0xc8, 0xc000959760)
	/usr/local/go/src/reflect/value.go:308 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc000169650, 0x121cfc0, 0xc000508180, 0x16, 0x126ab20, 0xc0000bd460, 0x199, 0x12031c0, 0x142af98, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x2ad
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc000169650, 0x126af80, 0xc000508180, 0x199, 0x126ab20, 0xc0000bd460, 0x199, 0xc0000c1040, 0xc000627680, 0xc0000c1040)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x45b
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert-fm(0x126af80, 0xc000508180, 0x199, 0x126ab20, 0xc0000bd460, 0x199, 0xc0000c1040, 0x1, 0xba900)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc000169650, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x0, 0xc0000e0620, 0xc000959aa8, 0x6, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2cf
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc000169650, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x0, 0xc0000e0620, 0x12676a0, 0x12d9800)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0xbc
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*scope).Convert(0xc0000c0ff0, 0x121cfc0, 0xc000508180, 0x121ca40, 0xc0000bd460, 0x0, 0x7f4549c45d80, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:274 +0x70
k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1.addConversionFuncs.func9(0xc000508160, 0xc0000bd440, 0x1531fe0, 0xc0000c0ff0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:57 +0x95
reflect.Value.call(0x1203100, 0x142afc8, 0x13, 0x1387050, 0x4, 0xc000959f60, 0x3, 0x3, 0x4c3b8a, 0x130b760, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x1203100, 0x142afc8, 0x13, 0xc000959f60, 0x3, 0x3, 0x2b, 0x7f4549c45d80, 0xc000959f60)
	/usr/local/go/src/reflect/value.go:308 +0xa4
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).callCustom(0xc000169650, 0x1286f20, 0xc000508160, 0x16, 0x130b760, 0xc0000bd440, 0x199, 0x1203100, 0x142afc8, 0x13, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:540 +0x2ad
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc000169650, 0x130b880, 0xc000508160, 0x199, 0x130b760, 0xc0000bd440, 0x199, 0xc0000c0ff0, 0xc000627600, 0xc0000c0ff0)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:568 +0x45b
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert-fm(0x130b880, 0xc000508160, 0x199, 0x130b760, 0xc0000bd440, 0x199, 0xc0000c0ff0, 0x1, 0x8)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0x7d
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc000169650, 0x1286f20, 0xc000508160, 0x1286e60, 0xc0000bd440, 0x0, 0xc0000e0620, 0xc00095a2a8, 0x40f3f1, 0xc00095a458)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2cf
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc000169650, 0x1286f20, 0xc000508160, 0x1286e60, 0xc0000bd440, 0x0, 0xc0000e0620, 0x151ac60, 0xc0000bd440)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0xbc
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc000088fc0, 0x1111400, 0x151ace0, 0xc000508160, 0x15134e0, 0x202be20, 0x40ab45, 0x202c1a8, 0x11110c1, 0x13)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:586 +0xa10
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).UnsafeConvertToVersion(0xc000088fc0, 0x151ace0, 0xc000508160, 0x15134e0, 0x202be20, 0x1286f20, 0xc000508160, 0x1548660, 0x1286f20)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:513 +0x5f
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime.unsafeObjectConvertor.ConvertToVersion(0xc000088fc0, 0x151ace0, 0xc000508160, 0x15134e0, 0x202be20, 0x0, 0x0, 0x151ace0, 0xc000508160)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/helper.go:39 +0x57
k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc000130900, 0xc00039c000, 0x710, 0x910, 0x0, 0x0, 0x0, 0xc000884918, 0xc000884908, 0x496243, ...)
	/go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:154 +0x69a
k8s.io/minikube/pkg/util/kubeconfig.decode(0xc00039c000, 0x710, 0x910, 0x710, 0x910, 0x0)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:215 +0x1c7
k8s.io/minikube/pkg/util/kubeconfig.ReadConfigOrNew(0xc000047b60, 0x2e, 0x2, 0xc0003c0b00, 0x11ac000)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:156 +0xcb
k8s.io/minikube/pkg/util/kubeconfig.SetupKubeConfig(0xc00013bc00, 0xc000047b60, 0x2e)
	/go/src/k8s.io/minikube/pkg/util/kubeconfig/config.go:128 +0x155
k8s.io/minikube/cmd/minikube/cmd.runStart(0x1ffc9a0, 0xc0002b1380, 0x0, 0x1)
	/go/src/k8s.io/minikube/cmd/minikube/cmd/start.go:336 +0x212a
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x1ffc9a0, 0xc0002b1360, 0x1, 0x1, 0x1ffc9a0, 0xc0002b1360)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2cc
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ffbdc0, 0x0, 0x202c200, 0xc00048bf48)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x2fd
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ffbdc0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:103 +0x2d
main.main()
	/go/src/k8s.io/minikube/cmd/minikube/main.go:41 +0x92

**Comment by tstromberg** [comment]
Still an issue in minikube v1.1.0. Workaround is to manually edit or remove ~/.kube/config.

**Comment by peterkuria** [comment]
I had similar issue" yaml: control characters are not allowed". Thanks, at last, I am able to use Kubectl on my windows 10. I had almost given up using it and was considering using a VM for Kubectl tool. This is what I was experiencing when trying to start minikube or kubernetes on my PC.
"PS C:\Program Files (x86)\Google\Cloud SDK> minikube start
There is a newer version of minikube available (v1.1.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.1.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
o   minikube v0.35.0 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.100
o   Found network options:
    - NO_PROXY=192.168.99.100,192.168.99.101
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
!   Failed to setup kubeconfig: could not read config: Error decoding config from data:                                                                                                                                                                                                                                                                                                                                                                                                                                               : yaml: control characters are not allowed
""
I renamed my .kube/config file and removed it from the folder, and as an Admin on Powershell, I deleted, reinstalled and restarted minikube as instructed above and surprisingly kubectl and minikube are both working again on my Windows 10 for now. I would add that I had to update VirtualBox since Kubectl had initially refused to kickstart the minikube VM but later succeeded on upgrading the host Virtualbox plus its extensions. I suspect that this issue was caused by corrupt Java installation(which I did reinstall), or deprecated minikube kubelet functionalities as hinted by " minikube logs" or my Windows corrupted NTFS hard drive since I experienced the same issue of invalid characters while trying to run javascript's npm "expo start" and still outputting Error: Invalid Character, Code: 800A03F6 even after updating my Windows 10 Java installation. Maybe someone would come to my rescue again. Thanks to the Kubernetes maintainers and everyone for the support of this amazing Kubernetes tool.

**Comment by tstromberg** [comment]
There isn't much we can do about this issue, but we'll leave it open in case others come by with corrupt KUBECONFIG files.

**Comment by sharifelgamal** [comment]
A good way to detect whether your kubeconfig file is corrupt is running `kubectl config view`. If that comes back with an error, then it's safe bet that minikube won't be able to use it.

This particular config file resulted in the following error message:
```kubectl config view
error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.```

If you see something like that, delete or edit your config and try again.
