### ISSUE TITLE
OSX-Virtualbox: TestStartStop: test timed out after 30m0s

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3200]
Failed for a doc-only change:

https://storage.googleapis.com/minikube-builds/logs/3191/OSX-Virtualbox.txt

```shell
=== RUN   TestStartStop
panic: test timed out after 30m0s

goroutine 726 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1023 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 25 minutes]:
testing.(*T).Run(0xc420191040, 0x1e1005b, 0xd, 0x1e8ae48, 0x1059c01)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc420191040)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc420191040, 0xc4200dbde0)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4204861c0, 0x25a2940, 0x4, 0x4, 0xc4200dbe78)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc4203eff20, 0xc4200dbf20)
	/usr/local/go/src/testing/testing.go:822 +0xfc
main.main()
	k8s.io/minikube/test/integration/_test/_testmain.go:48 +0xf7

goroutine 19 [chan receive]:
k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x25ae340)
	/var/lib/jenkins/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
	/var/lib/jenkins/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 20 [syscall, 30 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 709 [syscall, 25 minutes]:
syscall.Syscall6(0xad, 0x1, 0x1768, 0xc4202e6a48, 0x24, 0x0, 0x0, 0x28d8960, 0x0, 0xc4205a2ce0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:41 +0x5
os.(*Process).blockUntilWaitable(0xc420562a80, 0xc42033d600, 0xc4205a2d20, 0x7)
	/usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc420562a80, 0x100f542, 0xc4202897e0, 0xc4200b1490)
	/usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc420562a80, 0x0, 0x0, 0x1e8c318)
	/usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc42033d600, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:435 +0x62
os/exec.(*Cmd).Run(0xc42033d600, 0xc4200c8c80, 0x6)
	/usr/local/go/src/os/exec/exec.go:280 +0x5c
os/exec.(*Cmd).Output(0xc42033d600, 0x32, 0xc42058e780, 0x6, 0x6, 0xc42033d600)
	/usr/local/go/src/os/exec/exec.go:474 +0x11c
k8s.io/minikube/test/integration/util.(*MinikubeRunner).RunCommand(0xc4200799c0, 0xc4200c8c30, 0x49, 0x1, 0x2, 0xc4200c8c30)
	/var/lib/jenkins/go/src/k8s.io/minikube/test/integration/util/util.go:72 +0xe5
k8s.io/minikube/test/integration/util.(*MinikubeRunner).Start(0xc4200799c0)
	/var/lib/jenkins/go/src/k8s.io/minikube/test/integration/util/util.go:107 +0x109
k8s.io/minikube/test/integration.TestStartStop(0xc4203316c0)
	/var/lib/jenkins/go/src/k8s.io/minikube/test/integration/start_stop_delete_test.go:38 +0x23c
testing.tRunner(0xc4203316c0, 0x1e8ae48)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca

goroutine 714 [syscall, 25 minutes]:
syscall.Syscall(0x3, 0x6, 0xc420748ddf, 0x1021, 0x1f, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x6, 0xc420748ddf, 0x1021, 0x1021, 0x1f, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:973 +0x55
syscall.Read(0x6, 0xc420748ddf, 0x1021, 0x1021, 0x1f, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
os.(*File).read(0xc4204e25b8, 0xc420748ddf, 0x1021, 0x1021, 0x1f, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:165 +0x6a
os.(*File).Read(0xc4204e25b8, 0xc420748ddf, 0x1021, 0x1021, 0x1f, 0x0, 0x0)
	/usr/local/go/src/os/file.go:101 +0x76
bytes.(*Buffer).ReadFrom(0xc4200b1570, 0x25436a0, 0xc4204e25b8, 0x2948ad8, 0xc4200b1570, 0xc42048af01)
	/usr/local/go/src/bytes/buffer.go:179 +0x160
io.copyBuffer(0x2540a20, 0xc4200b1570, 0x25436a0, 0xc4204e25b8, 0x0, 0x0, 0x0, 0xc4206587d8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0x2540a20, 0xc4200b1570, 0x25436a0, 0xc4204e25b8, 0x1c54760, 0xc420658780, 0xc42048afb0)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x1c54760, 0xc420658780)
	/usr/local/go/src/os/exec/exec.go:254 +0x4d
os/exec.(*Cmd).Start.func1(0xc42033d600, 0xc4205a2ca0)
	/usr/local/go/src/os/exec/exec.go:371 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:372 +0x4e4

goroutine 715 [syscall, 25 minutes]:
syscall.Syscall(0x3, 0x8, 0xc4203ca000, 0x8000, 0x2e2, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x8, 0xc4203ca000, 0x8000, 0x8000, 0x2e2, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:973 +0x55
syscall.Read(0x8, 0xc4203ca000, 0x8000, 0x8000, 0x2e2, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
os.(*File).read(0xc4204e25d0, 0xc4203ca000, 0x8000, 0x8000, 0x2e2, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:165 +0x6a
os.(*File).Read(0xc4204e25d0, 0xc4203ca000, 0x8000, 0x8000, 0x2e2, 0x0, 0x0)
	/usr/local/go/src/os/file.go:101 +0x76
io.copyBuffer(0x2543860, 0xc4200c8c80, 0x25436a0, 0xc4204e25d0, 0xc4203ca000, 0x8000, 0x8000, 0xc4206587d8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:390 +0x100
io.Copy(0x2543860, 0xc4200c8c80, 0x25436a0, 0xc4204e25d0, 0x1c54760, 0xc420658780, 0xc4204f07b0)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x1c54760, 0xc420658780)
	/usr/local/go/src/os/exec/exec.go:254 +0x4d
os/exec.(*Cmd).Start.func1(0xc42033d600, 0xc4205a2d20)
	/usr/local/go/src/os/exec/exec.go:371 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:372 +0x4e4
++ result=2
```

I suspect something killed the VM:

```shell
+++ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
+++ MINIKUBE=out/minikube-darwin-amd64
+++ out/minikube-darwin-amd64 status
minikube: 
cluster: 
kubectl: 
+++ out/minikube-darwin-amd64 ip
E0930 07:23:42.398693    6129 ip.go:43] Error getting IP:  Error loading host from store: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```

**Comment by tstromberg** [comment]
Temporary workaround has been submitted.
