### ISSUE TITLE
dashboard: User "system:serviceaccount:kube-system:default" cannot create secrets in the namespace "kube-system" 

### ISSUE THREAD

**Issue by Strange-Account** [kubernetes/minikube#3281]
**BUG REPORT**:

**Environment**:

- **Minikube version**: v0.30.0
- **OS**: Ubuntu 18.10
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.30.0.iso
- **Install tools**:
- **Others**:

**What happened**:
Dashboard not starting

**What you expected to happen**:
Minikube installation without error

**How to reproduce it** (as minimally and precisely as possible):
`minikube start --kubernetes-version v1.10.9 --docker-env=HTTP_PROXY=http://proxy:8080 --docker-env=HTTPS_PROXY=http://proxy:8080`
```
Starting local Kubernetes v1.10.9 cluster...
Starting VM...
Downloading Minikube ISO
 170.78 MB / 170.78 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.9
Downloading kubelet v1.10.9
Finished Downloading kubelet v1.10.9
Finished Downloading kubeadm v1.10.9
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E1030 13:30:59.479801   15569 start.go:297] Error starting cluster:  kubeadm init error 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
`kubectl -n kube-system get pods`
```
NAME                                    READY     STATUS             RESTARTS   AGE
coredns-c4cffd6dc-fkdr9                 1/1       Running            0          1h
etcd-minikube                           1/1       Running            0          1h
kube-addon-manager-minikube             1/1       Running            0          1h
kube-apiserver-minikube                 1/1       Running            0          1h
kube-controller-manager-minikube        1/1       Running            0          1h
kube-dns-86f4d74b45-jg7lx               3/3       Running            0          1h
kube-proxy-nv64z                        1/1       Running            0          1h
kube-scheduler-minikube                 1/1       Running            0          1h
kubernetes-dashboard-6f4cfc5d87-d87qq   0/1       CrashLoopBackOff   27         1h
storage-provisioner                     1/1       Running            0          1h
```

`kubectl -n kube-system logs kubernetes-dashboard-6f4cfc5d87-d87qq `
```
2018/10/30 14:22:37 Starting overwatch
2018/10/30 14:22:37 Using in-cluster config to connect to apiserver
2018/10/30 14:22:37 Using service account token for csrf signing
2018/10/30 14:22:37 No request provided. Skipping authorization
2018/10/30 14:22:37 Successful initial request to the apiserver, version: v1.10.9
2018/10/30 14:22:37 Generating JWE encryption key
2018/10/30 14:22:37 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/10/30 14:22:37 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/10/30 14:22:37 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2018/10/30 14:22:37 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:kube-system:default" cannot create secrets in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc4203e48c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1b13180, 0xc4203bdf80, 0xc4203bdf80, 0x12e0aca)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x83
main.initAuthManager(0x1b12400, 0xc420203f20, 0xc420285c68, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:185 +0x12f
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:103 +0x28c
```

**Comment by N4rm0** [comment]
I have exactly the same error here on Windows 8 and virtualbox VM driver.
dashboard pod fails to start with same panic message on secret creation.
I can say this is a corporate proxy related problem, as I also use the docker-env HTTP_PROXY variables.
On the same laptop, I tested at home (without the proxy), minikube starts just fine.

**Comment by tstromberg** [comment]
Similar to: https://github.com/kubernetes/dashboard/issues/2797

**Comment by tstromberg** [comment]
I believe this is obsolete in v0.33 now that we've re-architected how the dashboard is started. Please re-open if this is not the case.
