### ISSUE TITLE
Linux/VirtualBox CI:

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3333]
For example: Linux_Integration_Tests_Virtualbox/builds/2074

```shell
++ set +e
++ out/e2e-linux-amd64 '-minikube-start-args=--vm-driver=virtualbox ' '-minikube-args=--v=10 --logtostderr ' -test.v -test.timeout=30m -binary=out/minikube-linux-amd64
=== RUN   TestDocker
panic: test timed out after 30m0s

goroutine 16 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1023 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 30 minutes]:
testing.(*T).Run(0xc4201b7790, 0x13565fd, 0xa, 0x13de690, 0xc4200cbd20)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc4201b7790)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc4201b7790, 0xc4200cbde0)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc42047d200, 0x1b893a0, 0x4, 0x4, 0xc4200cbe78)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc42004ff20, 0xc4200cbf20)
	/usr/local/go/src/testing/testing.go:822 +0xfc
main.main()
	k8s.io/minikube/test/integration/_test/_testmain.go:48 +0xf7

goroutine 17 [syscall, 30 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive]:
k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1b95ba0)
	/var/lib/jenkins/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
	/var/lib/jenkins/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 7 [syscall, 30 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 11 [syscall, 30 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x1143, 0xc42003d948, 0x1000004, 0x0, 0x0, 0x7ff885785000, 0x0, 0xc42047d780)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420292330, 0xc4200aeb00, 0xc42047d7c0, 0xb)
	/usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc420292330, 0x4110a2, 0xc420458f20, 0xc420021600)
	/usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc420292330, 0x0, 0x0, 0x13dfd80)
	/usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc4200aeb00, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:435 +0x62
os/exec.(*Cmd).Run(0xc4200aeb00, 0xc42001ea50, 0xa)
	/usr/local/go/src/os/exec/exec.go:280 +0x5c
os/exec.(*Cmd).Output(0xc4200aeb00, 0x53, 0xc420489360, 0xa, 0xa, 0xc4200aeb00)
	/usr/local/go/src/os/exec/exec.go:474 +0x11c
k8s.io/minikube/test/integration/util.(*MinikubeRunner).RunCommand(0xc42003df28, 0xc42001a240, 0x86, 0x1, 0x3, 0xc42001a240)
	/var/lib/jenkins/go/src/k8s.io/minikube/test/integration/util/util.go:72 +0xe5
k8s.io/minikube/test/integration.TestDocker(0xc4201b7860)
	/var/lib/jenkins/go/src/k8s.io/minikube/test/integration/docker_test.go:36 +0x30a
testing.tRunner(0xc4201b7860, 0x13de690)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca

goroutine 14 [syscall, 30 minutes]:
syscall.Syscall(0x0, 0x4, 0xc4202f8e16, 0xfea, 0x15, 0xfff, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc4202f8e16, 0xfea, 0xfea, 0x15, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x4, 0xc4202f8e16, 0xfea, 0xfea, 0x15, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
os.(*File).read(0xc42000e218, 0xc4202f8e16, 0xfea, 0xfea, 0x15, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:165 +0x4f
os.(*File).Read(0xc42000e218, 0xc4202f8e16, 0xfea, 0xfea, 0x15, 0x0, 0x0)
	/usr/local/go/src/os/file.go:101 +0x76
bytes.(*Buffer).ReadFrom(0xc4200152d0, 0x1b20280, 0xc42000e218, 0x7ff885731248, 0xc4200152d0, 0x1)
	/usr/local/go/src/bytes/buffer.go:179 +0x160
io.copyBuffer(0x1b1ce00, 0xc4200152d0, 0x1b20280, 0xc42000e218, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0x1b1ce00, 0xc4200152d0, 0x1b20280, 0xc42000e218, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:254 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200aeb00, 0xc42047d740)
	/usr/local/go/src/os/exec/exec.go:371 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:372 +0x4e4

goroutine 15 [syscall, 3 minutes]:
syscall.Syscall(0x0, 0x6, 0xc4203d2000, 0x8000, 0x74, 0x8000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x6, 0xc4203d2000, 0x8000, 0x8000, 0x74, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x6, 0xc4203d2000, 0x8000, 0x8000, 0x74, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
os.(*File).read(0xc42000e230, 0xc4203d2000, 0x8000, 0x8000, 0x74, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:165 +0x4f
os.(*File).Read(0xc42000e230, 0xc4203d2000, 0x8000, 0x8000, 0x74, 0x0, 0x0)
	/usr/local/go/src/os/file.go:101 +0x76
io.copyBuffer(0x1b20440, 0xc42001ea50, 0x1b20280, 0xc42000e230, 0xc4203d2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:390 +0x100
io.Copy(0x1b20440, 0xc42001ea50, 0x1b20280, 0xc42000e230, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:254 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200aeb00, 0xc42047d7c0)
	/usr/local/go/src/os/exec/exec.go:371 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:372 +0x4e4
++ result=2
++ set -e
++ sudo cat
++ MINIKUBE_WANTREPORTERRORPROMPT=False
++ sudo ./out/minikube-linux-amd64 delete
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  Error deleting host: minikube: Error loading host from store: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
++ MINIKUBE_WANTREPORTERRORPROMPT=False
++ ./out/minikube-linux-amd64 delete
```

**Comment by tstromberg** [comment]
Stuck on:

```
startCmd := fmt.Sprintf("start %s %s %s", minikubeRunner.StartArgs, minikubeRunner.Args,
		"--docker-env=FOO=BAR --docker-env=BAZ=BAT --docker-opt=debug --docker-opt=icc=true")
minikubeRunner.RunCommand(startCmd, true)
```
One obvious issue to address is that our test timeout panics before our minikube start timeout. If we allowed start to timeout, we would be able to see the logs.

**Comment by tstromberg** [comment]
kvm host is running virtualbox 5.1.38-122592~Debian~stretch  - we should upgrade once we work out the cause of this issue. Poking around the logs, this backtrace has happened once every week or so, but switched to becoming commonplace Nov 8 - Nov 10.  Specifically between 2067 (Nov 8 05:28) and 2068 (Nov 8 20:24).

```
-rw-r--r-- 1 jenkins jenkins  23345 Sep 24 22:57 ./1923/log
-rw-r--r-- 1 jenkins jenkins  22718 Sep 27 22:11 ./1933/log
-rw-r--r-- 1 jenkins jenkins  25365 Nov  8 20:24 ./2068/log
-rw-r--r-- 1 jenkins jenkins  25602 Nov  8 21:19 ./2069/log
-rw-r--r-- 1 jenkins jenkins  25569 Nov  8 22:00 ./2070/log
-rw-r--r-- 1 jenkins jenkins  22675 Nov 10 00:00 ./2072/log                                                                                          
-rw-r--r-- 1 jenkins jenkins  22507 Nov 10 08:10 ./2073/log
-rw-r--r-- 1 jenkins jenkins  22439 Nov 13 00:12 ./2074/log
-rw-r--r-- 1 jenkins jenkins  22536 Nov 13 00:53 ./2075/log
-rw-r--r-- 1 jenkins jenkins  21731 Nov 13 01:34 ./2076/log
-rw-r--r-- 1 jenkins jenkins  21727 Nov 13 02:14 ./2077/log
```

apt.log shows no updates between Nov 4 and Nov 11.  I've enabled auditd execve logging. It's been sitting here for the last 20 minutes:

```shell
time->Sat Nov 17 00:39:21 2018
type=PROCTITLE msg=audit(1542415161.319:6209): proctitle=2F7573722F6C69622F7669727475616C626F782F56426F784E657444484350002D2D69702D61646472657373003139322E3136382E39392E3130002D2D6C6F7765722D6970003139322E3136382E39392E313030002D2D6D61632D616464726573730030383A30303A32373A39343A36343A3831002D2D6E65746D61736B0032
type=PATH msg=audit(1542415161.319:6209): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=144244 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1542415161.319:6209): item=0 name="/usr/lib/virtualbox/VBoxNetDHCP" inode=918213 dev=08:01 mode=0104511 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=CWD msg=audit(1542415161.319:6209): cwd="/home/jenkins/workspace/Linux_Integration_Tests_Virtualbox"
type=EXECVE msg=audit(1542415161.319:6209): argc=17 a0="/usr/lib/virtualbox/VBoxNetDHCP" a1="--ip-address" a2="192.168.99.10" a3="--lower-ip" a4="192.168.99.100" a5="--mac-address" a6="08:00:27:94:64:81" a7="--netmask" a8="255.255.255.0" a9="--network" a10="HostInterfaceNetworking-vboxnet0" a11="--trunk-name" a12="vboxnet0" a13="--trunk-type" a14="netflt" a15="--upper-ip" a16="192.168.99.254"
type=BPRM_FCAPS msg=audit(1542415161.319:6209): fver=0 fp=0000000000000000 fi=0000000000000000 fe=0 old_pp=0000000000000000 old_pi=0000000000000000 old_pe=0000000000000000 new_pp=0000003fffffffff new_pi=0000000000000000 new_pe=0000003fffffffff
type=SYSCALL msg=audit(1542415161.319:6209): arch=c000003e syscall=59 success=yes exit=0 a0=7f077e03a960 a1=7f077e03a8c0 a2=7fff6dedbd20 a3=8 items=2 ppid=1358 pid=1699 auid=1004 uid=1004 gid=1005 euid=0 suid=0 fsuid=0 egid=1005 sgid=1005 fsgid=1005 tty=(none) ses=1 comm="VBoxNetDHCP" exe="/usr/lib/virtualbox/VBoxNetDHCP" key="root-commands"
```

I'm not really sure what's up here.

**Comment by balopat** [comment]
I took a screenshot of the box with `vboxmanage controlvm minikube screenshotpng screen.png`:  

![image](https://user-images.githubusercontent.com/635073/48655603-dff8eb80-e9cd-11e8-95d8-23ce70c0e9de.png)

**Comment by balopat** [comment]
interestingly on the GPU node the Linux-VBox TestDocker passes, the VBox version there is 5.2.18 not 5.2.22 - not sure what else is different.
