### ISSUE TITLE
brew cask install minikube: Permission denied: '/Library/Python/2.7/site-packages/protobuf-3.2.0-py2.7.egg/EGG-INFO/namespace_packages.txt'

### ISSUE THREAD

**Issue by anhtv08** [kubernetes/minikube#3461]
Hi all,

I have tried to install latest version of minikube on Mac OS  - the latest OS version Mojave

1 Run following command to install .

`brew cask install minkuke`
But got following issue:

```
anhs-MBP:bin anhtrang$ brew cask install minikube
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.31.0/minikube-darwin-amd64
Already downloaded: /Users/anhtrang/Library/Caches/Homebrew/downloads/4af93b9850e95845010ea0a17aa7db1d5433f5a19c925e9cc8300c3ac6f33a6d--minikube-darwin-amd64
==> Verifying SHA-256 checksum for Cask 'minikube'.
==> Installing Cask minikube
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
==> Purging files for version 0.31.0 of Cask minikube
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"minikube\"\) /usr/local/Caskroom/minikube/0.31.0/minikube-darwin-amd64` exited with 1. Here's the output:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3120, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 972, in subscribe
    callback(dist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3120, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2641, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2631, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1640, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1632, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1743, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/protobuf-3.2.0-py2.7.egg/EGG-INFO/namespace_packages.txt'


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:65:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:52:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

```
 
 it used to work before Mac OS 12 . but since I updated my Mac OS then it stopped working..

Any advice?

**Comment by tstromberg** [comment]
This should be solvable by:

`brew update && brew upgrade`

Please let me know if it doesn't work out for you.

**Comment by somard** [comment]
due to changes or new requirements from git, please run the following commands:
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
