### ISSUE TITLE
head: "minikube delete" on empty directory causes panic

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3662]
From head - appears related to #3656

```
% ./out/minikube delete
🔄  Reverting Kubernetes  using kubeadm ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12af3ba]

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func6(0x23e1720, 0x2412b40, 0x0, 0x0)
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/cmd/minikube/cmd/delete.go:63 +0xaaa
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x23e1720, 0x2412b40, 0x0, 0x0, 0x23e1720, 0x2412b40)
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2ae
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x23e2300, 0x1, 0x138ef40, 0xc00046c528)
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x2c0
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:103 +0x2e
main.main()
	/usr/local/google/home/tstromberg/go/src/k8s.io/minikube/cmd/minikube/main.go:43 +0xca
```

**Comment by u5surf** [comment]
https://github.com/kubernetes/minikube/blob/414b8ab9f848515998b3850ff7af2b21fe8f8869/cmd/minikube/cmd/delete.go#L61-L63

GetClusterBootstrapper returns nil, err when it's error.
L62 is true, then it excutes clusterBootstrapper.delete(), but clusterBootstrapper is nil from the above.

**Comment by afbjorklund** [comment]
Oops, think that code went in too fast
