### ISSUE TITLE
hyperkit: signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x406edf2

### ISSUE THREAD

**Issue by derekwyatt** [kubernetes/minikube#3902]
After running `minikube stop` I am not able to start it again.  I've had this issue for many releases of minikube and was hoping something "magic" would fix it in version `v0.35.0` but no luck.  Colleagues of mine do not have this problem so there's something messed up in my little world.

I've also tried doing a full `minikube delete; rm -rf ~/.minikube` but that makes no difference.

- On a MacBook Pro, Mid 2015, 16 GB RAM running High Sierra 10.13.6
- v0.35.0 of minikube
- v1.12.6 of kubectl
- Sequence of commands:
```
>>>>> minikube start --kubernetes-version v1.12.6 --cpus 8 --memory 10240 --vm-driver hyperkit --v=9

😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating hyperkit VM (CPUs=8, Memory=10240MB, Disk=20000MB) ...
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:51431
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Reading certificate data from $HOME/.minikube/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from $HOME/.minikube/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading $HOME/.minikube/cache/boot2docker.iso from file://$HOME/.minikube/cache/iso/minikube-v0.35.0.iso...
(minikube) DBG | 2019/03/18 16:30:35 [INFO] Creating ssh key...
(minikube) DBG | 2019/03/18 16:30:35 [INFO] Creating raw disk image...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
(minikube) Using UUID aeef4da0-49bc-11e9-9661-a45e60c65951
(minikube) Generated MAC a6:4d:aa:2:88:f6
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) Calling .GetConfigRaw
(minikube) Calling .DriverName
(minikube) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(minikube) Calling .GetState
Detecting operating system of created instance...
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting the provisioner...
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"

found compatible host: buildroot
Provisioning with buildroot...
(minikube) Calling .GetMachineName
setting hostname "minikube"
(minikube) Calling .GetMachineName
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
SSH cmd err, output: <nil>: minikube

(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:

		if ! grep -xq '.*\sminikube' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 minikube/g' /etc/hosts;
			else
				echo '127.0.1.1 minikube' | sudo tee -a /etc/hosts;
			fi
		fi
SSH cmd err, output: <nil>:
set auth options {CertDir:$HOME/.minikube CaCertPath:$HOME/.minikube/certs/ca.pem CaPrivateKeyPath:$HOME/.minikube/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:$HOME/.minikube/machines/server.pem ServerKeyPath:$HOME/.minikube/machines/server-key.pem ClientKeyPath:$HOME/.minikube/certs/key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:$HOME/.minikube/certs/cert.pem ServerCertSANs:[] StorePath:$HOME/.minikube}
setting up certificates
(minikube) Calling .GetMachineName
(minikube) Calling .GetIP
generating server cert: $HOME/.minikube/machines/server.pem ca-key=$HOME/.minikube/certs/ca.pem private-key=$HOME/.minikube/certs/ca-key.pem org=dwyatt.minikube san=[192.168.64.183 localhost]
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
(minikube) Calling .DriverName
Setting Docker configuration on the remote daemon...
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
sudo mkdir -p /lib/systemd/system && printf %s "[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket

[Service]
Type=notify

# DOCKER_RAMDISK disables pivot_root in Docker, using MS_MOVE instead.
Environment=DOCKER_RAMDISK=yes


# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperkit --insecure-registry 10.96.0.0/12
ExecReload=/bin/kill -s HUP $MAINPID

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
" | sudo tee /lib/systemd/system/docker.service
SSH cmd err, output: <nil>: [Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket

[Service]
Type=notify

# DOCKER_RAMDISK disables pivot_root in Docker, using MS_MOVE instead.
Environment=DOCKER_RAMDISK=yes


# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperkit --insecure-registry 10.96.0.0/12
ExecReload=/bin/kill -s HUP

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target

setting minikube options for container-runtime
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
sudo mkdir -p /etc/sysconfig && printf %s "
CRIO_MINIKUBE_OPTIONS='--insecure-registry 10.96.0.0/12 '
" | sudo tee /etc/sysconfig/crio.minikube
SSH cmd err, output: <nil>:
CRIO_MINIKUBE_OPTIONS='--insecure-registry 10.96.0.0/12 '

(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
sudo systemctl daemon-reload
SSH cmd err, output: <nil>:
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x143d0e0] 0x143d0b0  [] 0s} 192.168.64.183 22 <nil> <nil>}
About to run SSH command:
sudo systemctl -f restart crio
SSH cmd err, output: <nil>:
Checking connection to Docker...
(minikube) Calling .GetURL
Docker is up and running!
Reticulating splines...
(minikube) Calling .GetConfigRaw
(minikube) Calling .GetIP
📶  "minikube" IP address is 192.168.64.183
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
🐳  Configuring Docker as the container runtime ...
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:51503
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
✨  Preparing Kubernetes environment ...
(minikube) Calling .GetURL
🚜  Pulling images required by Kubernetes v1.12.6 ...
🚀  Launching Kubernetes v1.12.6 using kubeadm ...
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```

```
>>>>> minikube stop
✋  Stopping "minikube" in hyperkit ...
🛑  "minikube" stopped.
```

```
>>>>> minikube start --kubernetes-version v1.12.6 --cpus 8 --memory 10240 --vm-driver hyperkit --v=9
😄  minikube v0.35.0 on darwin (amd64)
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:51829
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .DriverName
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
(minikube) Calling .GetState
(minikube) Calling .DriverName
🔄  Restarting existing hyperkit VM for "minikube" ...
(minikube) Calling .Start
(minikube) Using UUID aeef4da0-49bc-11e9-9661-a45e60c65951
(minikube) Generated MAC a6:4d:aa:2:88:f6
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) DBG | unexpected fault address 0xb01dfacedebac1e
(minikube) DBG | fatal error: fault
(minikube) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x406edf2]
(minikube) DBG |
(minikube) DBG | goroutine 31 [running]:
(minikube) DBG | runtime.throw(0x4d11b6e, 0x5)
(minikube) DBG | 	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420051558 sp=0xc420051538
(minikube) DBG | runtime.sigpanic()
(minikube) DBG | 	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4200515a8 sp=0xc420051558
(minikube) DBG | syscall.ByteSliceFromString(0x3a38383a32303a61, 0x3666, 0x4c782c0, 0x300000002, 0xc4201d4ea0, 0x38, 0xc8)
(minikube) DBG | 	/usr/local/go/src/syscall/syscall.go:51 +0x32 fp=0xc420051608 sp=0xc4200515a8
(minikube) DBG | syscall.BytePtrFromString(0x3a38383a32303a61, 0x3666, 0x5e00960, 0x0, 0x4075b75)
(minikube) DBG | 	/usr/local/go/src/syscall/syscall.go:71 +0x39 fp=0xc420051650 sp=0xc420051608
(minikube) DBG | syscall.Stat(0x3a38383a32303a61, 0x3666, 0xc4202b0858, 0x100, 0xb0)
(minikube) DBG | 	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1220 +0x3f fp=0xc4200516d0 sp=0xc420051650
(minikube) DBG | os.Stat(0x3a38383a32303a61, 0x3666, 0x2, 0x0, 0xc4200517b8, 0x4068b32)
(minikube) DBG | 	/usr/local/go/src/os/stat_unix.go:32 +0x5c fp=0xc420051728 sp=0xc4200516d0
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).execute(0xc420257c80, 0xc420199e00, 0x98, 0x1, 0x1)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:233 +0xc0 fp=0xc420051900 sp=0xc420051728
(minikube) DBG | k8s.io/minikube/vendor/github.com/moby/hyperkit/go.(*HyperKit).Start(0xc420257c80, 0xc420199e00, 0x98, 0x1, 0x1)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/moby/hyperkit/go/hyperkit.go:220 +0x46 fp=0xc420051938 sp=0xc420051900
(minikube) DBG | k8s.io/minikube/pkg/drivers/hyperkit.(*Driver).Start(0xc4200b9340, 0x0, 0x0)
(minikube) DBG | 	/go/src/k8s.io/minikube/pkg/drivers/hyperkit/driver.go:209 +0x681 fp=0xc420051aa0 sp=0xc420051938
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Start(0xc4201f50a0, 0x5437948, 0x5437948, 0x0, 0x0)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:217 +0x36 fp=0xc420051ac8 sp=0xc420051aa0
(minikube) DBG | runtime.call64(0xc4202a52c0, 0xc42008e6b8, 0xc4202a52f0, 0x1800000028)
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:515 +0x48 fp=0xc420051b18 sp=0xc420051ac8
(minikube) DBG | reflect.Value.call(0xc42028e360, 0xc42008e6b8, 0x13, 0x4d10c2a, 0x4, 0xc42003cf20, 0x3, 0x3, 0x2, 0x400d954, ...)
(minikube) DBG | 	/usr/local/go/src/reflect/value.go:434 +0x91f fp=0xc420051e60 sp=0xc420051b18
(minikube) DBG | reflect.Value.Call(0xc42028e360, 0xc42008e6b8, 0x13, 0xc42002c720, 0x3, 0x3, 0xc42002c718, 0x403c661, 0xc4201d4d00)
(minikube) DBG | 	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420051ec8 sp=0xc420051e60
(minikube) DBG | net/rpc.(*service).call(0xc420271940, 0xc42007f780, 0xc420283d10, 0xc420287f00, 0xc4201f5300, 0x4b738a0, 0x5437948, 0x16, 0x4b738a0, 0x5437948, ...)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:387 +0x144 fp=0xc420051f78 sp=0xc420051ec8
(minikube) DBG | runtime.goexit()
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051f80 sp=0xc420051f78
(minikube) DBG | created by net/rpc.(*Server).ServeCodec
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:481 +0x404
(minikube) DBG |
(minikube) DBG | goroutine 1 [select]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver(0x53ca1e0, 0xc4200b9340)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:52 +0x61c
(minikube) DBG | main.main()
(minikube) DBG | 	/go/src/k8s.io/minikube/cmd/drivers/hyperkit/main.go:25 +0xcf
(minikube) DBG |
(minikube) DBG | goroutine 17 [syscall, locked to thread]:
(minikube) DBG | runtime.goexit()
(minikube) DBG | 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
(minikube) DBG |
(minikube) DBG | goroutine 20 [syscall]:
(minikube) DBG | os/signal.signal_recv(0x42c82db)
(minikube) DBG | 	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
(minikube) DBG | os/signal.loop()
(minikube) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
(minikube) DBG | created by os/signal.init.1
(minikube) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
(minikube) DBG |
(minikube) DBG | goroutine 21 [chan receive]:
(minikube) DBG | k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x541a860)
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d
(minikube) DBG |
(minikube) DBG | goroutine 22 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5e512d8, 0x72, 0x0)
(minikube) DBG | 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc420285a38, 0x72, 0x0, 0xc4201f52a0)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc420285a38, 0xffffffffffffffff, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).accept(0xc4202859d0, 0x0, 0x53b0e00, 0xc4201f52a0)
(minikube) DBG | 	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
(minikube) DBG | net.(*TCPListener).accept(0xc42008e6c8, 0xc42002be90, 0x427e57e, 0x40527c0)
(minikube) DBG | 	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
(minikube) DBG | net.(*TCPListener).Accept(0xc42008e6c8, 0x4d8bc50, 0xc420199c20, 0x53c6040, 0xc42026fdd0)
(minikube) DBG | 	/usr/local/go/src/net/tcpsock.go:228 +0x49
(minikube) DBG | net/http.(*Server).Serve(0xc4200b93f0, 0x53c52c0, 0xc42008e6c8, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2643 +0x228
(minikube) DBG | net/http.Serve(0x53c52c0, 0xc42008e6c8, 0x0, 0x0, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2307 +0x78
(minikube) DBG | created by k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver
(minikube) DBG | 	/go/src/k8s.io/minikube/vendor/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:49 +0x42a
(minikube) DBG |
(minikube) DBG | goroutine 23 [IO wait]:
(minikube) DBG | net.runtime_pollWait(0x5e51218, 0x72, 0x6)
(minikube) DBG | 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
(minikube) DBG | net.(*pollDesc).wait(0xc420285aa8, 0x72, 0x53b2900, 0x53ac740)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
(minikube) DBG | net.(*pollDesc).waitRead(0xc420285aa8, 0xc4202a2000, 0x1000)
(minikube) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
(minikube) DBG | net.(*netFD).Read(0xc420285a40, 0xc4202a2000, 0x1000, 0x1000, 0x0, 0x53b2900, 0x53ac740)
(minikube) DBG | 	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
(minikube) DBG | net.(*conn).Read(0xc42008e6d0, 0xc4202a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/net.go:181 +0x70
(minikube) DBG | bufio.(*Reader).Read(0xc42028f620, 0xc420283ca5, 0x1, 0x9, 0xc42011f680, 0xc42011f690, 0x4029a01)
(minikube) DBG | 	/usr/local/go/src/bufio/bufio.go:213 +0x312
(minikube) DBG | io.ReadAtLeast(0x53ade40, 0xc42028f620, 0xc420283ca5, 0x1, 0x9, 0x1, 0x4b738a0, 0x42a9201, 0x3)
(minikube) DBG | 	/usr/local/go/src/io/io.go:307 +0xa9
(minikube) DBG | io.ReadFull(0x53ade40, 0xc42028f620, 0xc420283ca5, 0x1, 0x9, 0x40297b6, 0x0, 0x7)
(minikube) DBG | 	/usr/local/go/src/io/io.go:325 +0x58
(minikube) DBG | encoding/gob.decodeUintReader(0x53ade40, 0xc42028f620, 0xc420283ca5, 0x9, 0x9, 0xc42011f790, 0x40290ee, 0xc400000008, 0xc42007f640)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decode.go:119 +0x63
(minikube) DBG | encoding/gob.(*Decoder).recvMessage(0xc420292180, 0xc42011f7a0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:76 +0x57
(minikube) DBG | encoding/gob.(*Decoder).decodeTypeSequence(0xc420292180, 0x4d8c300, 0xc420292180)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:140 +0x167
(minikube) DBG | encoding/gob.(*Decoder).DecodeValue(0xc420292180, 0x4b6e6e0, 0xc4201f5880, 0x16, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:208 +0xe8
(minikube) DBG | encoding/gob.(*Decoder).Decode(0xc420292180, 0x4b6e6e0, 0xc4201f5880, 0x0, 0xc42007f7a0)
(minikube) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:185 +0x16d
(minikube) DBG | net/rpc.(*gobServerCodec).ReadRequestHeader(0xc4202a40c0, 0xc4201f5880, 0x4bd2140, 0x5437948)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:407 +0x45
(minikube) DBG | net/rpc.(*Server).readRequestHeader(0xc42007f780, 0x53c6400, 0xc4202a40c0, 0x5437948, 0x16, 0xc4201f5300, 0xc420066001, 0x0, 0x0)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:580 +0x6c
(minikube) DBG | net/rpc.(*Server).readRequest(0xc42007f780, 0x53c6400, 0xc4202a40c0, 0xc42007f780, 0xc420283d10, 0xc420287f00, 0xc4201f5300, 0x4b738a0, 0x5437948, 0x16, ...)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:547 +0x5a
(minikube) DBG | net/rpc.(*Server).ServeCodec(0xc42007f780, 0x53c6400, 0xc4202a40c0)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:466 +0x77
(minikube) DBG | net/rpc.(*Server).ServeConn(0xc42007f780, 0x5e514c0, 0xc42008e6d0)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:458 +0x373
(minikube) DBG | net/rpc.(*Server).ServeHTTP(0xc42007f780, 0x53c54c0, 0xc420170a80, 0xc42028c200)
(minikube) DBG | 	/usr/local/go/src/net/rpc/server.go:700 +0x42a
(minikube) DBG | net/http.(*ServeMux).ServeHTTP(0x541a000, 0x53c54c0, 0xc420170a80, 0xc42028c200)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2238 +0x130
(minikube) DBG | net/http.serverHandler.ServeHTTP(0xc4200b93f0, 0x53c54c0, 0xc420170a80, 0xc42028c200)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2568 +0x92
(minikube) DBG | net/http.(*conn).serve(0xc420199c20, 0x53c5f80, 0xc4202719c0)
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:1825 +0x612
(minikube) DBG | created by net/http.(*Server).Serve
(minikube) DBG | 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
💣  Unable to start VM: start: unexpected EOF

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by tstromberg** [comment]
Can you run this for me:

`ls -la /usr/local/bin/docker-machine-driver-hyperkit`

Also, can you try installing the latest minikube hyperkit driver - it may help:

`curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
&& sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/`

Thanks!

**Comment by derekwyatt** [comment]
```
> ls -la /usr/local/bin/docker-machine-driver-hyperkit
-rwsr-xr-x 1 root wheel 26811748 Jun 22  2018 /usr/local/bin/docker-machine-driver-hyperkit
```

The upgrade seems to have fixed the problem. Thanks @tstromberg!

**Comment by tstromberg** [comment]
Excellent! In a future release, minikube will be doing a better job of managing the hyperkit binary, because this sort of interaction tends to happen.

 It doesn't help that there are 3 providers of this binary who all share a common path. :(
