### ISSUE TITLE
CI: golangci-lint out of memory 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4851]
we had this issue yesterday, for two PRs but it was flaky and not consistant error:

today I saw it in travis again : here https://travis-ci.org/kubernetes/minikube/jobs/562528986 
```

goroutine 11121 [runnable]:
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll.func1(0xc0a63ed400)
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:290
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:297 +0x11b
goroutine 11206 [semacquire]:
sync.runtime_SemacquireMutex(0xc0a63ed404, 0xc001d0f000)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0a63ed400)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/sync/mutex.go:134 +0x109
sync.(*Once).Do(0xc0a63ed400, 0xc0a6500790)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/sync/once.go:40 +0x3b
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.(*action).exec(0xc0a63ed400)
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:303 +0x50
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll.func1(0xc0a63ed400)
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:291 +0x34
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:297 +0x11b

```

the error is reported in: it seems to be the root cause of the problem:
https://github.com/golangci/golangci-lint/issues/483

**Comment by medyagh** [comment]
The work arround for this issue is setting the "GOGC" env variable
 https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint

**Comment by medyagh** [comment]
given that it has direct coronation between number of lint files, it could be related to the new files for site and translation.

we probably need to exclude more not-lintable files to be more efficient.

**Comment by afbjorklund** [comment]
Could run it on `v1.2.0` to compare ?

Someone bored could make a matrix:
- minikube version
- golangci-lint version
- jobs (default: nproc)
- gogc (default: 100)

And note runtime and cpu/ram usage. It used to run in 30 secs
