### ISSUE TITLE
Enable alpha resources

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/minikube#653]
In order to create a `ScheduledJob`, http://kubernetes.io/docs/user-guide/scheduled-jobs/ explains how `--runtime-config=batch/v2alpha1` needs to be passed to the API server. 

`minikube start` or `minikube --help` does not show any such option to configure this runtime accordingly.

**Comment by jimmidyson** [comment]
This is already enabled by default. minikube enables all known APIs via the [`api/all=true` runtme config](https://github.com/kubernetes/minikube/blob/master/cmd/localkube/cmd/options.go#L46).

`batch/v2alpha1` API will only be enabled if you're running with latest kubernetes, 1.4.0. The latest minikube release runs Kubernetes v1.3.5 by default so you you will need to either run with a local build of master, or specify Kubernetes version 1.4.0 when you start up minikube via:

`minikube start --kubernetes-version=v1.4.0`

I've just checked & the API group is available as expected:

```
$ curl --cert ~/.minikube/apiserver.crt --key ~/.minikube/apiserver.key -k https://$(minikube ip):8443/apis/batch

{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "batch",
  "versions": [
    {
      "groupVersion": "batch/v1",
      "version": "v1"
    },
    {
      "groupVersion": "batch/v2alpha1",
      "version": "v2alpha1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "batch/v1",
    "version": "v1"
  },
  "serverAddressByClientCIDRs": null
}

$ curl --cert ~/.minikube/apiserver.crt --key ~/.minikube/apiserver.key -k https://$(minikube ip):8443/apis/batch/v2alpha1

{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "batch/v2alpha1",
  "resources": [
    {
      "name": "jobs",
      "namespaced": true,
      "kind": "Job"
    },
    {
      "name": "jobs/status",
      "namespaced": true,
      "kind": "Job"
    },
    {
      "name": "scheduledjobs",
      "namespaced": true,
      "kind": "ScheduledJob"
    },
    {
      "name": "scheduledjobs/status",
      "namespaced": true,
      "kind": "ScheduledJob"
    }
  ]
}

$ curl --cert ~/.minikube/apiserver.crt --key ~/.minikube/apiserver.key -k https://$(minikube ip):8443/apis/batch/v2alpha1/jobs

{
  "kind": "JobList",
  "apiVersion": "batch/v2alpha1",
  "metadata": {
    "selfLink": "/apis/batch/v2alpha1/jobs",
    "resourceVersion": "245"
  },
  "items": []
}
```

**Comment by arun-gupta** [comment]
@jimmidyson Started the cluster as `minikube start --kubernetes-version=v1.4.0`. It shows the output as:

```
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
```

Trying to create a pod now gives:

```
kubectl create -f wildfly-pod.yml 
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
```

What is missing?

**Comment by jimmidyson** [comment]
Check `minikube logs` & see if `kubectl get pods` works. Might be just being too impatient :-b

**Comment by arun-gupta** [comment]
Got the following error:

```
==> /var/lib/localkube/localkube.err <==
Starting etcd...

==> /var/lib/localkube/localkube.out <==
I1004 14:11:18.103179    1766 server.go:203] Using iptables Proxier.
W1004 14:11:18.103546    1766 server.go:417] Failed to retrieve node info: Get http://127.0.0.1:8080/api/v1/nodes/minikube: dial tcp 127.0.0.1:8080: getsockopt: connection refused
W1004 14:11:18.103612    1766 proxier.go:226] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
I1004 14:11:18.103624    1766 server.go:215] Tearing down userspace rules.
E1004 14:11:18.142383    1766 reflector.go:203] pkg/proxy/config/api.go:30: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1004 14:11:18.162809    1766 reflector.go:203] pkg/proxy/config/api.go:33: Failed to list *api.Endpoints: Get http://127.0.0.1:8080/api/v1/endpoints?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
2016-10-04 14:11:18.212574 I | etcdserver: recovered store from snapshot at index 40004
2016-10-04 14:11:18.212617 I | etcdserver: name = kubeetcd
2016-10-04 14:11:18.212623 I | etcdserver: data dir = /var/lib/localkube/etcd
2016-10-04 14:11:18.212629 I | etcdserver: member dir = /var/lib/localkube/etcd/member
2016-10-04 14:11:18.212633 I | etcdserver: heartbeat = 100ms
2016-10-04 14:11:18.212637 I | etcdserver: election = 1000ms
2016-10-04 14:11:18.212641 I | etcdserver: snapshot count = 10000
2016-10-04 14:11:18.212655 I | etcdserver: advertise client URLs = http://localhost:2379
2016-10-04 14:11:18.321512 I | etcdserver: restarting member 37807cb0bf7500f6 in cluster 2c833ae9c7555b5e at commit index 44370
2016-10-04 14:11:18.321704 I | raft: 37807cb0bf7500f6 became follower at term 4
2016-10-04 14:11:18.321717 I | raft: newRaft 37807cb0bf7500f6 [peers: [37807cb0bf7500f6], term: 4, commit: 44370, applied: 40004, lastindex: 44370, lastterm: 4]
2016-10-04 14:11:18.321816 I | api: enabled capabilities for version 2.3
2016-10-04 14:11:18.321830 I | membership: added member 37807cb0bf7500f6 [http://localhost:2380] to cluster 2c833ae9c7555b5e from store
2016-10-04 14:11:18.321835 I | membership: set the cluster version to 2.3 from store
panic: Etcd config error: database file (/var/lib/localkube/etcd/member/snap/db index 0) does not match with snapshot (index 40004).

goroutine 1 [running]:
panic(0x2fa7d80, 0xc42053fb00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/minikube/pkg/localkube.(*EtcdServer).Start(0xc4206e1e00)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/localkube/etcd.go:94 +0x2ba
k8s.io/minikube/pkg/localkube.Servers.StartAll(0xc420653200, 0x7, 0x8)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/localkube/servers.go:41 +0x11d
k8s.io/minikube/cmd/localkube/cmd.StartLocalkube()
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd/start.go:49 +0xb9
k8s.io/minikube/cmd/localkube/cmd.glob..func1(0x52bd260, 0xc4206e1c80, 0x0, 0x3)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd/root.go:31 +0x14
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x52bd260, 0xc42000c190, 0x3, 0x3, 0x52bd260, 0xc42000c190)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x52bd260, 0x4, 0x376f103, 0x2e)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x52bd260, 0x0, 0x0)
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/var/lib/jenkins/jobs/localkube/workspace/src/k8s.io/minikube/cmd/localkube/main.go:32 +0x5f
```

Deleted `.minikube` directory and starting all over again.

**Comment by arun-gupta** [comment]
@jimmidyson Deleting the directory, starting the cluster, and creating the resource worked. But being an alpha resource, shouldn't this resource be explicitly enabled as opposed to by default? At least that's what is listed at http://kubernetes.io/docs/api/.

**Comment by jimmidyson** [comment]
As I explained above, we use the special api/all=true to enable all available apis. That's documented on the original link you sent through. Try it & see if the API is available (it is).

**Comment by arun-gupta** [comment]
API is available. But that makes the experience inconsistent with Kubernetes on the cloud.

**Comment by jimmidyson** [comment]
Minikube's purpose is to provide an easy getting started ux for a local single node cluster, plus enabling users to try out new features such as new APIs. Enabling the api/all in kubernetes config is documented & supported & makes the whole ux much simpler. We could require users to configure APIs individually but that just complicates things for little to no value IMO.
