### ISSUE TITLE
kubectl randomly fails

### ISSUE THREAD

**Issue by PierrickI3** [kubernetes/minikube#677]
OS: Mac OS Sierra
minikube: 0.11.0

When running `kubectl get po`, the command randomly fails. Here is an example where the first try fails and running the same command again succeeds:

```
pl190016ml:kafka pierrick.lozach$ kubectl get po
failed MSpanList_Insert 0x1c96db8 0x3cce16066d9d 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x1a566d8, 0x1c96db8)
	/usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x1a56600, 0x1, 0x1000000000a, 0xcf29)
	/usr/src/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x1a5da78, 0x1c98b60)
	/usr/src/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x1c7e000, 0xa, 0x1c98b60)
	/usr/src/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc2081fb4e0 sp=0xc2081fb4d8
runtime.mallocgc(0x90, 0xd80380, 0xc200000001, 0xc2082e7ef0)
	/usr/src/go/src/runtime/malloc.go:178 +0x849 fp=0xc2081fb590 sp=0xc2081fb4e0
runtime.newarray(0xd80380, 0x11, 0xc2082e7ef0)
	/usr/src/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2081fb5c8 sp=0xc2081fb590
runtime.makeslice(0x11c5320, 0x11, 0x11, 0x0, 0x0, 0x0)
	/usr/src/go/src/runtime/slice.go:32 +0x15c fp=0xc2081fb610 sp=0xc2081fb5c8
math/big.nat.divLarge(0xc208206640, 0x10, 0x25, 0xc20828a7e0, 0x20, 0x24, 0xc2081beea0, 0x20, 0x24, 0xc208083290, ...)
	/usr/src/go/src/math/big/nat.go:541 +0x2d0 fp=0xc2081fb7a8 sp=0xc2081fb610
math/big.nat.div(0xc208206640, 0x10, 0x25, 0xc20828a7e0, 0x20, 0x24, 0xc2081beea0, 0x20, 0x24, 0xc208083290, ...)
	/usr/src/go/src/math/big/nat.go:519 +0x35a fp=0xc2081fb850 sp=0xc2081fb7a8
math/big.nat.expNNWindowed(0xc2081beea0, 0x20, 0x24, 0xc208038dc0, 0x10, 0x14, 0xc2080c05a0, 0x10, 0x14, 0xc208083290, ...)
	/usr/src/go/src/math/big/nat.go:1372 +0x82a fp=0xc2081fbae0 sp=0xc2081fb850
math/big.nat.expNN(0xc20828a7e0, 0x10, 0x24, 0xc208038dc0, 0x10, 0x14, 0xc2080c05a0, 0x10, 0x14, 0xc208083290, ...)
	/usr/src/go/src/math/big/nat.go:1260 +0x4b0 fp=0xc2081fbc78 sp=0xc2081fbae0
math/big.nat.probablyPrime(0xc208083290, 0x10, 0x15, 0x14, 0x1)
	/usr/src/go/src/math/big/nat.go:1445 +0x887 fp=0xc2081fbdf0 sp=0xc2081fbc78
math/big.(*Int).ProbablyPrime(0xc208205940, 0x14, 0xc207fed901)
	/usr/src/go/src/math/big/int.go:741 +0x4a fp=0xc2081fbe20 sp=0xc2081fbdf0
crypto/rsa.(*PrivateKey).Validate(0xc208048d80, 0x0, 0x0)
	/usr/src/go/src/crypto/rsa/rsa.go:110 +0x108 fp=0xc2081fbf20 sp=0xc2081fbe20
crypto/x509.ParsePKCS1PrivateKey(0xc208220000, 0x4a7, 0x4a7, 0xc208048d80, 0x0, 0x0)
	/usr/src/go/src/crypto/x509/pkcs1.go:77 +0x702 fp=0xc2081fc0a8 sp=0xc2081fbf20
crypto/tls.parsePrivateKey(0xc208220000, 0x4a7, 0x4a7, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/tls.go:259 +0x7d fp=0xc2081fc198 sp=0xc2081fc0a8
crypto/tls.X509KeyPair(0xc2081c14c4, 0x0, 0x200, 0xc20818788b, 0x0, 0x200, 0xc2082058c0, 0x1, 0x1, 0x0, ...)
	/usr/src/go/src/crypto/tls/tls.go:213 +0x394 fp=0xc2081fc390 sp=0xc2081fc198
k8s.io/kubernetes/pkg/client/transport.TLSConfigFor(0xc2080a20e0, 0xc2080a0990, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:76 +0x2c0 fp=0xc2081fc4f0 sp=0xc2081fc390
k8s.io/kubernetes/pkg/client/transport.(*tlsTransportCache).get(0x1a3de60, 0xc2080a20e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/cache.go:53 +0x1f9 fp=0xc2081fc588 sp=0xc2081fc4f0
k8s.io/kubernetes/pkg/client/transport.New(0xc2080a20e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:43 +0x149 fp=0xc2081fc5e8 sp=0xc2081fc588
k8s.io/kubernetes/pkg/client/restclient.TransportFor(0xc208206000, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/transport.go:36 +0x5a fp=0xc2081fc618 sp=0xc2081fc5e8
k8s.io/kubernetes/pkg/client/restclient.RESTClientFor(0xc208206000, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/config.go:145 +0x19b fp=0xc2081fc6c8 sp=0xc2081fc618
k8s.io/kubernetes/pkg/client/unversioned.New(0xc208085e00, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:49 +0xe2 fp=0xc2081fc7b8 sp=0xc2081fc6c8
k8s.io/kubernetes/pkg/client/unversioned.NegotiateVersion(0x0, 0xc208085e00, 0xc208204f80, 0xc208066a00, 0x7, 0x8, 0xc2081bc3c0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:125 +0x75 fp=0xc2081fca30 sp=0xc2081fc7b8
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientConfigForVersion(0xc208035fc0, 0xc2081dc360, 0xc2081dc360, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:76 +0x2f1 fp=0xc2081fcc48 sp=0xc2081fca30
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientForVersion(0xc208035fc0, 0xc2081dc360, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:103 +0xbc fp=0xc2081fccb8 sp=0xc2081fcc48
k8s.io/kubernetes/pkg/kubectl/cmd/util.func·004(0xc208011730, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:237 +0x150 fp=0xc2081fcdd8 sp=0xc2081fccb8
k8s.io/kubernetes/pkg/kubectl/resource.ClientMapperFunc.ClientForMapping(0xc20813cde0, 0xc208011730, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/interfaces.go:45 +0x51 fp=0xc2081fce08 sp=0xc2081fcdd8
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).visitorResult(0xc20818f5f0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:528 +0x8e9 fp=0xc2081fd538 sp=0xc2081fce08
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).Do(0xc20818f5f0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:686 +0x33 fp=0xc2081fd630 sp=0xc2081fd538
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc20814ab40, 0x1c8fff0, 0xc20804e008, 0xc20800dc00, 0xc2080c4a40, 0x1, 0x1, 0xc2080ac8e0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:235 +0xead fp=0xc2081fdc38 sp=0xc2081fd630
k8s.io/kubernetes/pkg/kubectl/cmd.func·034(0xc20800dc00, 0xc2080c4a40, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:89 +0x6f fp=0xc2081fdca0 sp=0xc2081fdc38
github.com/spf13/cobra.(*Command).execute(0xc20800dc00, 0xc2080c49c0, 0x1, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f fp=0xc2081fddb8 sp=0xc2081fdca0
github.com/spf13/cobra.(*Command).ExecuteC(0xc20800d800, 0xc20800dc00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db fp=0xc2081fdec8 sp=0xc2081fddb8
github.com/spf13/cobra.(*Command).Execute(0xc20800d800, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a fp=0xc2081fdef0 sp=0xc2081fdec8
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101 fp=0xc2081fdf70 sp=0xc2081fdef0
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f fp=0xc2081fdf98 sp=0xc2081fdf70
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc2081fdfe0 sp=0xc2081fdf98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2081fdfe8 sp=0xc2081fdfe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a3f640)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35


pl190016ml:kafka pierrick.lozach$ kubectl get po
NAME                           READY     STATUS             RESTARTS   AGE
busybox                        1/1       Running            2          2h
cassandra-1377689329-zk36w     1/1       Running            1          4h
kafka-2293503293-9okb0         0/1       CrashLoopBackOff   25         1h
kong-1098704074-cqfbh          0/1       CrashLoopBackOff   6          2h
ping-2469725947-ecis8          1/1       Running            1          2h
zookeeper-1-492281529-f4cko    1/1       Running            1          2h
zookeeper-2-865181371-scxv8    1/1       Running            1          2h
zookeeper-3-1238081213-kq9z0   1/1       Running            1          2h
pl190016ml:kafka pierrick.lozach$
```

**Comment by r2d4** [comment]
Similar to the issue with minikube - go binaries built with go 1.6 have been segfaulting on macOS Sierra because of this issue https://github.com/golang/go/issues/16570

Minikube releases v0.11.0 and above are built with go 1.7, so this shouldnt be an issue.  

However, for kubectl, you will also need to grab a precompiled binary with go 1.7, which it seems like you can get here.
https://github.com/kubernetes/kubernetes/issues/33801#issuecomment-250890436

**Comment by PierrickI3** [comment]
@r2d4 Thank you! Works perfectly now
