### ISSUE TITLE
run `minikube start` with --image-mirror-country=cn failed

### ISSUE THREAD

**Issue by billtian** [kubernetes/minikube#7052]
When i use the **minikube 1.8.2** to start , it failed, But the 1.8.1 can work.

**The exact command to reproduce the issue**:

```
minikube start --cpus=4 --memory=4g --download-only=true --driver=kvm2 --image-mirror-country=cn --alsologtostderr -v=7
```
**The full output of the command that failed**:<details>
```

panic: semver: Parse(v1.17.3): Invalid character(s) found in major number "v1"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0xc0007ee036, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/blang/semver@v3.5.0+incompatible/semver.go:319 +0x1c1
k8s.io/minikube/cmd/minikube/cmd.generateCfgFromFlags(0x2a45e60, 0xc0007ee036, 0x7, 0x1a6b53a, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/app/cmd/minikube/cmd/start.go:825 +0x335
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2a45e60, 0xc000148a80, 0x0, 0x8)
	/app/cmd/minikube/cmd/start.go:315 +0x3be
github.com/spf13/cobra.(*Command).execute(0x2a45e60, 0xc000148900, 0x8, 0x8, 0x2a45e60, 0xc000148900)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x2a44f60, 0x0, 0x1, 0xc000637bc0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:108 +0x6a4
main.main()
	/app/cmd/minikube/main.go:66 +0xea

```

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

Ubuntu 18.04.4 LTS

**Comment by afbjorklund** [comment]
Thanks for reporting, this bug was introduced by mistake in 71a22787c3ba69198471f1d440f393beebcf70ad

It needs to strip the silent `v` character, before feeding it to semver...
