### ISSUE TITLE
Problems getting minikube to start with CNI and rkt

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes/minikube#724]
_From @Mierdin on October 20, 2016 2:11_

Sitting in the excellent Intro to Kubernetes workshop by @ryanj and just wanted to post my logs to help troubleshoot. I managed to get this working by omitting the extra flags and going with the canonical `minikube start` command on it's own

He mentioned that he had mixed results with running minikube with the additional flags to run CNI and `rkt`, and I had issues as well, though my +1 did not have issues.

(Running iTerm2 with zsh, with VirtualBox 5.0.12)

Here's how I started

```
~$ minikube start \                                                                                                                                                  
>     --network-plugin=cni \
>     --container-runtime=rkt \ --iso-url=https://github.com/coreos/minikube-iso/releases/download/v0.0.5/minikube-v0.0.5.iso
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.

~$ kubectl get nodes                                                                                                                                                 
The connection to the server 192.168.99.103:8443 was refused - did you specify the right host or port?
```

Here are the minikube logs:

```
~$ minikube logs                                                                                                                                                     [17:52:29]
==> /var/lib/localkube/localkube.err <==
I1020 00:48:25.095618    2812 server.go:203] Using iptables Proxier.
W1020 00:48:25.095986    2812 server.go:417] Failed to retrieve node info: Get http://127.0.0.1:8080/api/v1/nodes/minikube: dial tcp 127.0.0.1:8080: getsockopt: connection refused
W1020 00:48:25.096039    2812 proxier.go:226] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
I1020 00:48:25.096050    2812 server.go:215] Tearing down userspace rules.
2016-10-20 00:48:25.110700 I | etcdserver: name = kubeetcd
2016-10-20 00:48:25.110718 I | etcdserver: data dir = /var/lib/localkube/etcd
2016-10-20 00:48:25.110723 I | etcdserver: member dir = /var/lib/localkube/etcd/member
2016-10-20 00:48:25.110726 I | etcdserver: heartbeat = 100ms
2016-10-20 00:48:25.110729 I | etcdserver: election = 1000ms
2016-10-20 00:48:25.110733 I | etcdserver: snapshot count = 10000
2016-10-20 00:48:25.110743 I | etcdserver: advertise client URLs = http://localhost:2379
2016-10-20 00:48:25.110748 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2016-10-20 00:48:25.110758 I | etcdserver: initial cluster = kubeetcd=http://localhost:2380
2016-10-20 00:48:25.111465 I | etcdserver: starting member 37807cb0bf7500f6 in cluster 2c833ae9c7555b5e
2016-10-20 00:48:25.111523 I | raft: 37807cb0bf7500f6 became follower at term 0
2016-10-20 00:48:25.111546 I | raft: newRaft 37807cb0bf7500f6 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-10-20 00:48:25.111552 I | raft: 37807cb0bf7500f6 became follower at term 1
2016-10-20 00:48:25.113838 I | etcdserver: starting server... [version: 3.0.6, cluster version: to_be_decided]
2016-10-20 00:48:25.119818 I | etcdserver: name = dns
2016-10-20 00:48:25.119835 I | etcdserver: data dir = /var/lib/localkube/dns
2016-10-20 00:48:25.119841 I | etcdserver: member dir = /var/lib/localkube/dns/member
2016-10-20 00:48:25.119844 I | etcdserver: heartbeat = 100ms
2016-10-20 00:48:25.119847 I | etcdserver: election = 1000ms
2016-10-20 00:48:25.119851 I | etcdserver: snapshot count = 10000
2016-10-20 00:48:25.119857 I | etcdserver: advertise client URLs = http://localhost:49090
2016-10-20 00:48:25.119861 I | etcdserver: initial advertise peer URLs = http://localhost:9256
2016-10-20 00:48:25.119866 I | etcdserver: initial cluster = dns=http://localhost:9256
2016-10-20 00:48:25.121389 I | etcdserver: starting member 6429d4ab4d8a33da in cluster d3c354cfe77b0b70
2016-10-20 00:48:25.121426 I | raft: 6429d4ab4d8a33da became follower at term 0
2016-10-20 00:48:25.121435 I | raft: newRaft 6429d4ab4d8a33da [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-10-20 00:48:25.121440 I | raft: 6429d4ab4d8a33da became follower at term 1
2016-10-20 00:48:25.124623 I | etcdserver: starting server... [version: 3.0.6, cluster version: to_be_decided]
I1020 00:48:25.125383    2812 genericapiserver.go:630] Will report 10.0.2.15 as public IP address.
W1020 00:48:25.143810    2812 cacher.go:469] Terminating all watchers from cacher *storage.StorageClass
E1020 00:48:25.144066    2812 controllermanager.go:125] unable to register configz: register config "componentconfig" twice
E1020 00:48:25.144456    2812 server.go:75] unable to register configz: register config "componentconfig" twice
E1020 00:48:25.144902    2812 server.go:294] unable to register configz: register config "componentconfig" twice
W1020 00:48:25.144934    2812 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config instead.
I1020 00:48:25.164548    2812 conntrack.go:40] Setting nf_conntrack_max to 32768
I1020 00:48:25.164825    2812 conntrack.go:57] Setting conntrack hashsize to 8192
I1020 00:48:25.164906    2812 conntrack.go:62] Setting nf_conntrack_tcp_timeout_established to 86400
2016-10-20 00:48:25.165567 I | skydns: ready for queries on cluster.local. for tcp://10.0.2.15:53 [rcache 0]
2016-10-20 00:48:25.165582 I | skydns: ready for queries on cluster.local. for udp://10.0.2.15:53 [rcache 0]
2016-10-20 00:48:25.166037 I | membership: added member 37807cb0bf7500f6 [http://localhost:2380] to cluster 2c833ae9c7555b5e
2016-10-20 00:48:25.166065 W | etcdserver: apply entries took too long [40.938451ms for 1 entries]
2016-10-20 00:48:25.166071 W | etcdserver: avoid queries with large range/delete range!
W1020 00:48:25.166677    2812 cacher.go:469] Terminating all watchers from cacher *api.PodTemplate
W1020 00:48:25.166853    2812 cacher.go:469] Terminating all watchers from cacher *api.LimitRange
W1020 00:48:25.167034    2812 cacher.go:469] Terminating all watchers from cacher *api.ResourceQuota
W1020 00:48:25.167151    2812 cacher.go:469] Terminating all watchers from cacher *api.Secret
W1020 00:48:25.167288    2812 cacher.go:469] Terminating all watchers from cacher *api.ServiceAccount
W1020 00:48:25.167405    2812 cacher.go:469] Terminating all watchers from cacher *api.PersistentVolume
W1020 00:48:25.167537    2812 cacher.go:469] Terminating all watchers from cacher *api.PersistentVolumeClaim
W1020 00:48:25.167648    2812 cacher.go:469] Terminating all watchers from cacher *api.ConfigMap
W1020 00:48:25.167802    2812 cacher.go:469] Terminating all watchers from cacher *api.Namespace
W1020 00:48:25.167926    2812 cacher.go:469] Terminating all watchers from cacher *api.Endpoints
W1020 00:48:25.168048    2812 cacher.go:469] Terminating all watchers from cacher *api.Node
W1020 00:48:25.168171    2812 cacher.go:469] Terminating all watchers from cacher *api.Pod
W1020 00:48:25.168285    2812 cacher.go:469] Terminating all watchers from cacher *api.Service
W1020 00:48:25.168458    2812 cacher.go:469] Terminating all watchers from cacher *api.ReplicationController
W1020 00:48:25.176365    2812 cacher.go:469] Terminating all watchers from cacher *apps.PetSet
W1020 00:48:25.176647    2812 cacher.go:469] Terminating all watchers from cacher *autoscaling.HorizontalPodAutoscaler
W1020 00:48:25.176787    2812 cacher.go:469] Terminating all watchers from cacher *batch.Job
W1020 00:48:25.176919    2812 cacher.go:469] Terminating all watchers from cacher *batch.ScheduledJob
W1020 00:48:25.177060    2812 cacher.go:469] Terminating all watchers from cacher *batch.Job
W1020 00:48:25.177175    2812 cacher.go:469] Terminating all watchers from cacher *certificates.CertificateSigningRequest
W1020 00:48:25.177290    2812 cacher.go:469] Terminating all watchers from cacher *autoscaling.HorizontalPodAutoscaler
W1020 00:48:25.177395    2812 cacher.go:469] Terminating all watchers from cacher *api.ReplicationController
W1020 00:48:25.177642    2812 cacher.go:469] Terminating all watchers from cacher *extensions.DaemonSet
W1020 00:48:25.177779    2812 cacher.go:469] Terminating all watchers from cacher *extensions.Deployment
W1020 00:48:25.177882    2812 cacher.go:469] Terminating all watchers from cacher *batch.Job
W1020 00:48:25.177981    2812 cacher.go:469] Terminating all watchers from cacher *extensions.Ingress
W1020 00:48:25.178082    2812 cacher.go:469] Terminating all watchers from cacher *extensions.ReplicaSet
W1020 00:48:25.178229    2812 cacher.go:469] Terminating all watchers from cacher *extensions.NetworkPolicy
W1020 00:48:25.178342    2812 cacher.go:469] Terminating all watchers from cacher *policy.PodDisruptionBudget
W1020 00:48:25.178472    2812 cacher.go:469] Terminating all watchers from cacher *rbac.Role
W1020 00:48:25.178581    2812 cacher.go:469] Terminating all watchers from cacher *rbac.Role
W1020 00:48:25.178679    2812 cacher.go:469] Terminating all watchers from cacher *rbac.RoleBinding
W1020 00:48:25.178783    2812 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRole
W1020 00:48:25.178882    2812 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRoleBinding
W1020 00:48:25.178984    2812 cacher.go:469] Terminating all watchers from cacher *rbac.RoleBinding
W1020 00:48:25.179079    2812 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRole
W1020 00:48:25.179181    2812 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRoleBinding
E1020 00:48:25.179423    2812 reflector.go:203] pkg/proxy/config/api.go:33: Failed to list *api.Endpoints: Get http://127.0.0.1:8080/api/v1/endpoints?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
2016-10-20 00:48:25.181768 I | membership: added member 6429d4ab4d8a33da [http://localhost:9256] to cluster d3c354cfe77b0b70
E1020 00:48:25.181856    2812 reflector.go:203] pkg/proxy/config/api.go:30: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.197055    2812 leaderelection.go:252] error retrieving endpoint: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.197112    2812 leaderelection.go:252] error retrieving endpoint: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.219693    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go:83: Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1/resourcequotas?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.219772    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://127.0.0.1:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.219814    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1/serviceaccounts?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.219849    2812 reflector.go:203] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go:154: Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1/limitranges?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
I1020 00:48:25.219883    2812 dns.go:156] Failed to check for kube-system namespace existence: Get http://localhost:8080/api/v1/namespaces/kube-system: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221118    2812 event.go:208] Unable to write event: 'Post http://127.0.0.1:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry after sleeping)
E1020 00:48:25.221277    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:415: Failed to list *extensions.ReplicaSet: Get http://127.0.0.1:8080/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221322    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:410: Failed to list *api.ReplicationController: Get http://127.0.0.1:8080/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221355    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:405: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221394    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:400: Failed to list *api.PersistentVolumeClaim: Get http://127.0.0.1:8080/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221426    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:399: Failed to list *api.PersistentVolume: Get http://127.0.0.1:8080/api/v1/persistentvolumes?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221459    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:395: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221495    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:392: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.221526    2812 reflector.go:214] k8s.io/minikube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:389: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
I1020 00:48:25.282910    2812 kube2sky.go:486] Etcd server found: http://localhost:49090
E1020 00:48:25.500104    2812 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
I1020 00:48:25.502248    2812 manager.go:140] cAdvisor running in container: "/"
2016-10-20 00:48:25.522071 I | raft: 6429d4ab4d8a33da is starting a new election at term 1
2016-10-20 00:48:25.522106 I | raft: 6429d4ab4d8a33da became candidate at term 2
2016-10-20 00:48:25.522144 I | raft: 6429d4ab4d8a33da received vote from 6429d4ab4d8a33da at term 2
2016-10-20 00:48:25.522160 I | raft: 6429d4ab4d8a33da became leader at term 2
2016-10-20 00:48:25.522169 I | raft: raft.node: 6429d4ab4d8a33da elected leader 6429d4ab4d8a33da at term 2
2016-10-20 00:48:25.522726 I | etcdserver: setting up the initial cluster version to 3.0
2016-10-20 00:48:25.522778 I | etcdserver: published {Name:dns ClientURLs:[http://localhost:49090]} to cluster d3c354cfe77b0b70
2016-10-20 00:48:25.523042 N | membership: set the initial cluster version to 3.0
2016-10-20 00:48:25.523079 I | api: enabled capabilities for version 3.0
W1020 00:48:25.527363    2812 manager.go:148] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I1020 00:48:25.528467    2812 fs.go:116] Filesystem partitions: map[/dev/sda1:{mountpoint:/mnt/sda1/var/lib/docker/aufs major:8 minor:1 fsType:ext4 blockSize:0}]
I1020 00:48:25.529779    2812 info.go:47] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I1020 00:48:25.529816    2812 manager.go:195] Machine: {NumCores:1 CpuFrequency:2294688 MemoryCapacity:1044250624 MachineID: SystemUUID:49EA73B3-A078-410E-A0D5-B0265CBF793C BootID:fd971d46-b399-4945-a461-02b773e11208 Filesystems:[{Device:/dev/sda1 Capacity:19195224064 Type:vfs Inodes:2436448 HasInodes:true} {Device:tmpfs Capacity:939827200 Type:vfs Inodes:127472 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:20971520000 Scheduler:deadline} 251:0:{Name:zram0 Major:251 Minor:0 Size:208752640 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:22:23:07:b5:a5:7a Speed:0 Mtu:1500} {Name:eth0 MacAddress:08:00:27:2a:cf:f6 Speed:1000 Mtu:1500} {Name:eth1 MacAddress:08:00:27:7f:b7:54 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:6291456 Type:Unified Level:3} {Size:134217728 Type:Unified Level:4}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1020 00:48:25.530389    2812 manager.go:201] Version: {KernelVersion:4.4.14-boot2docker ContainerOsVersion:Boot2Docker 1.11.1 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016 DockerVersion:1.11.1 CadvisorVersion: CadvisorRevision:}
I1020 00:48:25.530979    2812 kubelet.go:255] Adding manifest file: /etc/kubernetes/manifests
I1020 00:48:25.530999    2812 kubelet.go:265] Watching apiserver
E1020 00:48:25.534149    2812 reflector.go:203] pkg/kubelet/kubelet.go:406: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.534233    2812 reflector.go:203] pkg/kubelet/kubelet.go:387: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1020 00:48:25.534300    2812 reflector.go:203] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
I1020 00:48:25.535008    2812 kubelet.go:506] Using node IP: "192.168.99.103"
W1020 00:48:25.535024    2812 kubelet_network.go:64] Hairpin mode set to "promiscuous-bridge" but container runtime is "rkt", ignoring
I1020 00:48:25.535036    2812 kubelet.go:516] Hairpin mode set to "none"
E1020 00:48:25.535128    2812 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
E1020 00:48:25.735208    2812 server.go:294] unable to register configz: register config "componentconfig" twice
W1020 00:48:25.735271    2812 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config instead.
E1020 00:48:25.735612    2812 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
I1020 00:48:25.738516    2812 manager.go:140] cAdvisor running in container: "/"
W1020 00:48:25.739750    2812 manager.go:148] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I1020 00:48:25.740030    2812 fs.go:116] Filesystem partitions: map[/dev/sda1:{mountpoint:/mnt/sda1/var/lib/docker/aufs major:8 minor:1 fsType:ext4 blockSize:0}]
I1020 00:48:25.740774    2812 info.go:47] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I1020 00:48:25.740795    2812 manager.go:195] Machine: {NumCores:1 CpuFrequency:2294688 MemoryCapacity:1044250624 MachineID: SystemUUID:49EA73B3-A078-410E-A0D5-B0265CBF793C BootID:fd971d46-b399-4945-a461-02b773e11208 Filesystems:[{Device:/dev/sda1 Capacity:19195224064 Type:vfs Inodes:2436448 HasInodes:true} {Device:tmpfs Capacity:939827200 Type:vfs Inodes:127472 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:20971520000 Scheduler:deadline} 251:0:{Name:zram0 Major:251 Minor:0 Size:208752640 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:22:23:07:b5:a5:7a Speed:0 Mtu:1500} {Name:eth0 MacAddress:08:00:27:2a:cf:f6 Speed:1000 Mtu:1500} {Name:eth1 MacAddress:08:00:27:7f:b7:54 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:6291456 Type:Unified Level:3} {Size:134217728 Type:Unified Level:4}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1020 00:48:25.741094    2812 manager.go:201] Version: {KernelVersion:4.4.14-boot2docker ContainerOsVersion:Boot2Docker 1.11.1 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016 DockerVersion:1.11.1 CadvisorVersion: CadvisorRevision:}
panic: duplicate metrics collector registration attempted

goroutine 133 [running]:
panic(0x3052920, 0xc420440500)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/minikube/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0x524fd40, 0xc421d17640)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/prometheus/client_golang/prometheus/registry.go:120 +0x74
k8s.io/minikube/vendor/github.com/google/cadvisor/http.RegisterPrometheusHandler(0x5265a80, 0xc421d37920, 0x527cd60, 0xc421d2f0a0, 0x3686a32, 0x8, 0x38db4a8)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/google/cadvisor/http/handlers.go:97 +0x81
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).exportHTTP(0xc421d2f0a0, 0x1062, 0x546adc8, 0x37e11d600)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:133 +0x12c
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor.New(0x1062, 0x7ffedce9fd60, 0x3, 0x0, 0xc42007fa01, 0x0, 0xc421cb8000)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:113 +0x276
k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kubelet/app.run(0xc42057e500, 0xc421c99c20, 0x5441d00, 0x368235d)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:398 +0x791
k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kubelet/app.Run(0xc42057e500, 0x0, 0x0, 0xc421cd0000)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:267 +0x39
k8s.io/minikube/pkg/localkube.StartKubeletServer.func1(0x2f37940, 0x0)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/localkube/kubelet.go:64 +0x36
k8s.io/minikube/pkg/util.Until(0xc420744580, 0x5248980, 0xc420024010, 0x3685ac9, 0x7, 0xbebc200, 0xc4203529c0)
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/util/utils.go:44 +0x87
created by k8s.io/minikube/pkg/localkube.(*SimpleServer).Start
    /var/lib/jenkins/go2/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/pkg/localkube/server.go:60 +0x7e

==> /var/lib/localkube/localkube.out <==
Starting etcd...
Starting apiserver...
Starting controller-manager...
Starting scheduler...
Starting kubelet...
Starting proxy...
Starting dns...

kubelet: Exit with error: failed to run Kubelet: failed to create kubelet: rkt: cannot create systemd interface: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
```

_Copied from original issue: coreos/minikube-iso#31_

**Comment by s-urbaniak** [comment]
@Mierdin Thanks for reporting! I see in the output:

```
error updating cni config: No networks found in /etc/cni/net.d
```

Apparently the localkube cannot find the CNI configuration. Do you mind to paste the result of the following command?

```
$ minikube ssh
$ cd /etc/cni/net.d
$ ls -l
$ cat k8s.conf
```

**Comment by s-urbaniak** [comment]
@Mierdin I think it is also worth mentioning, that if you used the canonical `minikube start` before, it will cache the previously used (boot2docker based) ISO image. Please delete the old minikube folder `rm -rf ~/.minikube` before starting with `--iso-url=https://github.com/coreos/minikube-iso/releases/download/v0.0.5/minikube-v0.0.5.iso`.

**Comment by s-urbaniak** [comment]
_From @jonboulle on October 20, 2016 9:53_

@s-urbaniak shouldn't we close this repository in favour of the upstream
minikube one now?

**Comment by s-urbaniak** [comment]
@jonboulle ack, I was just about to push a plain README, and disable the Issues here.

**Comment by Mierdin** [comment]
Thanks for the quick response! FYI this was my first-ever experience with minikube, so the very first minikube commands I ever ran on my system were with those extra flags to enable CNI and rkt.
