### ISSUE TITLE
TestNewSSHClient: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#7284]
https://github.com/kubernetes/minikube/pull/7282/checks?check_run_id=538693321

```
--- FAIL: TestNewSSHClient (0.25s)
    ssh_mock.go:176: Listening on 127.0.0.1:35513
    ssh_mock.go:83: Accepting...
    ssh_mock.go:83: Accepting...
    ssh_mock.go:135: exec request received: &{Type:exec WantReply:true Payload:[0 0 0 3 102 111 111] ch:0xc0001ec6c0 mux:<nil>}
    sshutil_test.go:67: Error running "foo": wait: remote command exited without exit status or exit signal
    ssh_mock.go:192: Stopping
panic: Fail in goroutine after TestNewSSHClient has completed

goroutine 5 [running]:
testing.(*common).Fail(0xc0001cf320)
	/usr/local/go1.14/src/testing/testing.go:613 +0x11a
testing.(*common).Errorf(0xc0001cf320, 0xc32961, 0x16, 0xc000187f00, 0x1, 0x1)
	/usr/local/go1.14/src/testing/testing.go:712 +0x90
k8s.io/minikube/pkg/minikube/tests.(*SSHServer).handleRequest(0xc0001217a0, 0xd49840, 0xc0001ec6c0, 0xc000159f80)
	/home/runner/work/minikube/minikube/pkg/minikube/tests/ssh_mock.go:154 +0x381
k8s.io/minikube/pkg/minikube/tests.(*SSHServer).handleIncomingConnection(0xc0001217a0, 0xd4c9c0, 0xc000010018)
	/home/runner/work/minikube/minikube/pkg/minikube/tests/ssh_mock.go:118 +0x15f
created by k8s.io/minikube/pkg/minikube/tests.(*SSHServer).serve
	/home/runner/work/minikube/minikube/pkg/minikube/tests/ssh_mock.go:92 +0x4a
FAIL	k8s.io/minikube/pkg/minikube/sshutil	0.261s
```

Travis:
`ok  	k8s.io/minikube/pkg/minikube/sshutil	0.525s	coverage: 100.0% of statements`

**Comment by tstromberg** [comment]
Still happens:

```
--- FAIL: TestNewSSHClient (0.44s)
    ssh_mock.go:193: Listening on 127.0.0.1:38547
    ssh_mock.go:83: Serving ...
    ssh_mock.go:87: [loop 1] Accepting for &{0xc000129ee0 map[] false  0 {map[]} false 0xc00000e160 0xc00013d200}...
    ssh_mock.go:87: [loop 2] Accepting for &{0xc000129ee0 map[] false  0 {map[]} false 0xc00000e160 0xc00013d200}...
    ssh_mock.go:149: exec request received: &{Type:exec WantReply:true Payload:[0 0 0 3 102 111 111] ch:0xc0001ae000 mux:<nil>}
    ssh_mock.go:161: returning output for foo ...
    ssh_mock.go:169: setting exit-status for foo ...
    ssh_mock.go:171: SendRequest failed: EOF
    sshutil_test.go:69: Error running "foo": wait: remote command exited without exit status or exit signal
    ssh_mock.go:209: Stopping
```
