### ISSUE TITLE
update-context with missing entry: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#7437]
minikube 1.9.2, ubuntu 16.04, virtualbox

```console
$ minikube status
E0405 16:02:32.312506   22446 status.go:233] kubeconfig endpoint: extract IP: "minikube" does not appear in /home/anders/.kube/config
m01
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Misconfigured


WARNING: Your kubectl is pointing to stale minikube-vm.
To fix the kubectl context, run `minikube update-context`
$ minikube update-context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x148ecb0]

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x1a823d1, 0x8, 0xc00050a1b0, 0xe, 0x20fb, 0xc0000437e0, 0x19, 0x1d82160, 0xc00012c060, 0xc00050a1b0)
	/app/pkg/minikube/kubeconfig/kubeconfig.go:122 +0x290
k8s.io/minikube/cmd/minikube/cmd.glob..func30(0x2a6e180, 0x2aa53b0, 0x0, 0x0)
	/app/cmd/minikube/cmd/update-context.go:37 +0x10a
github.com/spf13/cobra.(*Command).execute(0x2a6e180, 0x2aa53b0, 0x0, 0x0, 0x2a6e180, 0x2aa53b0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x2a6c380, 0x0, 0x1, 0xc00040f500)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:108 +0x6a4
main.main()
	/app/cmd/minikube/main.go:66 +0xea

```

**Comment by govargo** [comment]
I'm interested in this issue.

/assign

**Comment by tstromberg** [comment]
any update?

**Comment by govargo** [comment]
I'm working on this. I will send PR as soon as it is over.

**Comment by govargo** [comment]
I send PR https://github.com/kubernetes/minikube/pull/7717
