### ISSUE TITLE
Docker_Linux: TestDockerFlags: docker.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7520]
https://storage.googleapis.com/minikube-builds/logs/7516/5110da9/Docker_Linux.html#fail_TestDockerFlags

```
	I0408 09:46:25.294022    2650 kic_runner.go:91] Run: sudo systemctl start docker
	goroutine 1 [running]:
	runtime/debug.Stack(0x17b9f20, 0x1a87240, 0x9)
		/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
	runtime/debug.PrintStack()
		/usr/local/go/src/runtime/debug/stack.go:16 +0x22
	k8s.io/minikube/pkg/minikube/node.configureRuntimes(0x7ff392b9dd78, 0xc00056b700, 0x7fff172be4fd, 0x2b, 0x0, 0x0, 0x0, 0x708, 0x2, 0x4e20, ...)
		/app/pkg/minikube/node/start.go:235 +0x238
	k8s.io/minikube/pkg/minikube/node.Start(0x7fff172be4fd, 0x2b, 0x0, 0x0, 0x0, 0x708, 0x2, 0x4e20, 0x1a81946, 0x6, ...)
		/app/pkg/minikube/node/start.go:102 +0x662
	k8s.io/minikube/cmd/minikube/cmd.runStart(0x2a73300, 0xc0001920e0, 0x1, 0xe)
		/app/cmd/minikube/cmd/start.go:204 +0x6f4
	github.com/spf13/cobra.(*Command).execute(0x2a73300, 0xc000192000, 0xe, 0xe, 0x2a73300, 0xc000192000)
		/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
	github.com/spf13/cobra.(*Command).ExecuteC(0x2a72400, 0x0, 0x1, 0xc000048680)
		/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
	github.com/spf13/cobra.(*Command).Execute(...)
		/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
	k8s.io/minikube/cmd/minikube/cmd.Execute()
		/app/cmd/minikube/cmd/root.go:108 +0x6a4
	main.main()
		/app/cmd/minikube/main.go:66 +0xe

	* [NONE_DOCKER_EXIT_1] Failed to enable container runtime enable docker.: sudo systemctl start docker: exit status 1

	stdout:
	
	stderr:
	Job for docker.service failed because the control process exited with error code.
	See "systemctl status docker.service" and "journalctl -xe" for details.

	* Suggestion: Either systemctl is not installed, or Docker is broken. Run 'sudo systemctl start docker' and 'journalctl -u docker'
	* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
	* Related issue: https://github.com/kubernetes/minikube/issues/4498

** /stderr **

docker_test.go:42: failed to start minikube with args: "out/minikube-linux-amd64 start -p docker-flags-20200408T094531.467587102-5291 --cache-images=false --memory=1800 --install-addons=false --wait=false --docker-env=FOO=BAR --docker-env=BAZ=BAT --docker-opt=debug --docker-opt=icc=true --alsologtostderr -v=5 --driver=docker " : exit status 78
```

**Comment by medyagh** [comment]
I think this one is fixed I havent seen it in a while
