### ISSUE TITLE
v1.9.2 minikube status > nil pointer

### ISSUE THREAD

**Issue by kempy007** [kubernetes/minikube#8068]
1. Installed version was v1.6.2, upgraded to v1.9.2
2. run `minikube status`
3. issue goes after `minikube start` and fetching updated iso etc.

<details>

```
PS C:\WINDOWS\system32> minikube status
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x16dc55a]

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.exitCode(0x0, 0x8)
        /app/cmd/minikube/cmd/status.go:141 +0x4a
k8s.io/minikube/cmd/minikube/cmd.glob..func25(0x2ad3600, 0x2b10f08, 0x0, 0x0)
        /app/cmd/minikube/cmd/status.go:135 +0x611
github.com/spf13/cobra.(*Command).execute(0x2ad3600, 0x2b10f08, 0x0, 0x0, 0x2ad3600, 0x2b10f08)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2ad2480, 0x0, 0x20, 0xc000119580)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:108 +0x64f
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
```
</details>

**Comment by medyagh** [comment]
@kempy007 sorry to hear that. I noticed u upgraded form v1.6.2 since that version we have added a new driver, "docker" which will be much faster than virtualbox.

do u mind trying with our docker driver and the latest version ?
minikube start --driver=docker

**Comment by medyagh** [comment]
@kempy007 I haven't heared from you, have you had chance to try latest verison of minikube ?
