### ISSUE TITLE
v1.10.0 initialization issue, nil pointer [WINDOWS]

### ISSUE THREAD

**Issue by kristapsstrals** [kubernetes/minikube#8080]
**Steps to reproduce the issue:** 

1.Update minikube from 1.9.2 to 1.10.0 and run `minikube start`
```
�🔥  minikube v1.10.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
✨  Using the hyperv driver based on user configuration
�🔥  Downloading VM boot image ...
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.10.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 59.77 MiB p/s 3s
�🏄  Starting control plane node minikube in cluster minikube
�🔥  Downloading Kubernetes v1.18.1 preload ...
    > preloaded-images-k8s-v3-v1.18.1-docker-overlay2-amd64.tar.lz4: 525.47 MiB
�🌟  Creating hyperv VM (CPUs=2, Memory=6144MB, Disk=51200MB) ...
�🏄  Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/cluster.HostIP(0xc00010ce40, 0x7, 0x1e7e200, 0xc0223c9410, 0x0, 0xc000788690)
        /app/pkg/minikube/cluster/ip.go:45 +0xce8
k8s.io/minikube/pkg/minikube/node.Start(0x1e3a7e0, 0xc0007cf4e0, 0x0, 0x1e65d80, 0xc00048e080, 0xc00010ce40, 0xc00012e380, 0xc00028d580, 0xc00075d590, 0xc801, ...)
        /app/pkg/minikube/node/start.go:93 +0x201
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1e3a7e0, 0xc0007cf4e0, 0x0, 0x1e65d80, 0xc00048e080, 0xc00010ce40, 0xc00012e380, 0xc00028d580, 0xc00075d590, 0x0, ...)      
        /app/cmd/minikube/cmd/start.go:281 +0x83
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b53760, 0xc0003fe1e0, 0x0, 0x6)
        /app/cmd/minikube/cmd/start.go:202 +0x6f3
github.com/spf13/cobra.(*Command).execute(0x2b53760, 0xc000479bc0, 0x6, 0x6, 0x2b53760, 0xc000479bc0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x0, 0xc000406901)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
```

Seems to be an issue specifically in `minikube update-context`, since that produces the below output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x18 pc=0x15a7d96]

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x1b245e6, 0x8, 0xc000041c10, 0xd, 0x20fb, 0xc000039860, 0x23, 0x1e3a7e0, 0xc0001049a0, 0xc000041c10)
        /app/pkg/minikube/kubeconfig/kubeconfig.go:143 +0x2b6
k8s.io/minikube/cmd/minikube/cmd.glob..func31(0x2b4e8a0, 0x2b911b0, 0x0, 0x0)
        /app/cmd/minikube/cmd/update-context.go:37 +0x111
github.com/spf13/cobra.(*Command).execute(0x2b4e8a0, 0x2b911b0, 0x0, 0x0, 0x2b4e8a0, 0x2b911b0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x0, 0xc00015c001)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
```

Downgrading to `1.9.2` again solved the issue:

```
�🔥  minikube v1.9.2 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
✨  Using the hyperv driver based on user configuration
�🛑  Starting control plane node m01 in cluster minikube
�🔥  Creating hyperv VM (CPUs=2, Memory=6144MB, Disk=51200MB) ...
�💀  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
�👍  Enabling addons: dashboard, default-storageclass, ingress, metrics-server, storage-provisioner
�😄  Done! kubectl is now configured to use "minikube"
```

**Comment by medyagh** [comment]
@kristapsstrals thanks for bringing this to our attention, I am curious if this is related to a config.json's change. do you mind trying to delete minikube and then start again to see if that would work?

**Comment by medyagh** [comment]
this is a bug and we will fix it and relese a patch for it. thank you for being the first to report it

**Comment by medyagh** [comment]
@kristapsstrals

while a patch is being released tonight, I encourage everyone to use our newest driver: docker

for more information see:
https://minikube.sigs.k8s.io/docs/drivers/docker/

again sorry for this bug !

**Comment by medyagh** [comment]
@kristapsstrals
minikube v1.10.1 is out including fix for this bug 
https://github.com/kubernetes/minikube/releases/tag/v1.10.1

**Comment by kristapsstrals** [comment]
@medyagh Thanks a lot for the fix! I'd use docker driver, but last I checked it did not support ingress addon on windows, which I need.
