### ISSUE TITLE
minikube v1.10.1 coredns resolves kubernetes.default to internal ip

### ISSUE THREAD

**Issue by ocassetti** [kubernetes/minikube#8276]
I am not 100% sure if this is expected behaviour but I think `kubernetes.default` gets resolved to the wrong IP address

I am trying to run Apache Spark 2.4.5. on minikube v1.10.1 with docker

```
minikube config set memory 8192
minikube config set cpus 4
minikube start

```

The cluster starts fine 

```
kubectl cluster-info
Kubernetes master is running at https://172.17.0.3:8443
KubeDNS is running at https://172.17.0.3:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
````
When I check how `kubernetes.default` gets resolved from a pod I get a different ip

```
 kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools   
If you don't see a command prompt, try pressing enter.
dnstools# nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1

```

This is causing the following error in Apache Spark 

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [wms-etl-1590491927772-driver]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:237)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:170)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator$$anonfun$1.apply(ExecutorPodsAllocator.scala:57)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator$$anonfun$1.apply(ExecutorPodsAllocator.scala:55)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsAllocator.<init>(ExecutorPodsAllocator.scala:55)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterManager.createSchedulerBackend(KubernetesClusterManager.scala:89)
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2788)
	... 13 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
```

I tried to change the configuration of `coredns` but I did not get anywhere

**Comment by tstromberg** [comment]
This is definitely expected behavior. The 'Broken pipe` error should be unrelated, as one should get a different error if DNS is unable to resolve. Would it be possible to see the output of `minikube logs`, particularly the `apiserver` section?

**Comment by ocassetti** [comment]
@tstromberg  I found the issue, somehow I was not applying the `rbac` policy and therefore it did not have permissions.
Thanks again and apologies.
