### ISSUE TITLE
minikube addons configure on a nonexistent cluster: panic: runtime error

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8302]
To reproduce:

2. `minikube -p xyz addons configure metallb`

Example output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x288 pc=0x224dd7a]

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd/config.glob..func8(0x37153a0, 0xc000275350, 0x1, 0x1)
	/app/cmd/minikube/cmd/config/configure.go:200 +0x1d2a
github.com/spf13/cobra.(*Command).execute(0x37153a0, 0xc000275320, 0x1, 0x1, 0x37153a0, 0xc000275320)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x3712ee0, 0x0, 0x1, 0xc0004156c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:112 +0x747
main.main()
	/app/cmd/minikube/main.go:66 +0xea
```

**Comment by tstromberg** [comment]
To fix this `cmd/minikube/cmd/config/configure.go` should probably call `mustload.Partial(name)` to validate the cluster exists.
