### ISSUE TITLE
minikube v1.11.0 failed to start with multinode on Windows 10

### ISSUE THREAD

**Issue by myugan** [kubernetes/minikube#8344]
**Steps to reproduce the issue:** 

1. Install latest minikube from https://github.com/kubernetes/minikube/releases.
2. Start a cluster with 3 nodes with command `minikube start --nodes 3 -p multinode`

**Full output of `minikube start` command used**

````
C:\Windows\system32>minikube start --nodes 3 -p multinode
* [multinode] minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB  100.00% 867.85 KiB p/s 3m2
* Starting control plane node multinode in cluster multinode
* Updating the running hyperv "multinode" VM ...
* Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.18.2
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get https://172.17.34.251:8443/apis/storage.k8s.io/v1/storageclasses: x509: certificate is valid for 172.17.34.242, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 172.17.34.251]
* Enabled addons: default-storageclass, storage-provisioner
*
X failed to start node: startup failed: Wait failed: node pressure: list nodes: Get https://172.17.34.251:8443/api/v1/nodes: x509: certificate is valid for 172.17.34.242, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 172.17.34.251
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by sharifelgamal** [comment]
It looks like you have an existing cluster under the 'multinode' cluster. What does `minikube status -p multinode` look like?

Also, could you rerun this command with `-v=4 --alsologtostderr` added to it?

I suspect a delete and restart will help but I want to see what sort of state your cluster is in to recreate this issue.

**Comment by myugan** [comment]
For this command `minikube status -p multinode -v=4 --alsologtostderr ` it show an output like this:

```
C:\Windows\system32>minikube status -p multinode -v=4 --alsologtostderr
I0603 07:45:10.473307   11408 mustload.go:64] Loading cluster: multinode
I0603 07:45:10.474304   11408 status.go:123] checking status of  ...
I0603 07:45:10.474304   11408 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM multinode ).state
I0603 07:45:11.042973   11408 main.go:110] libmachine: [stdout =====>] : Running

I0603 07:45:11.043141   11408 main.go:110] libmachine: [stderr =====>] :
I0603 07:45:11.043888   11408 status.go:188] multinode host status = "Running" (err=<nil>)
I0603 07:45:11.043888   11408 host.go:65] Checking if "multinode" exists ...
I0603 07:45:11.044885   11408 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM multinode ).state
I0603 07:45:11.772351   11408 main.go:110] libmachine: [stdout =====>] : Running

I0603 07:45:11.772651   11408 main.go:110] libmachine: [stderr =====>] :
I0603 07:45:11.773377   11408 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM multinode ).networkadapters[0]).ipaddresses[0]
I0603 07:45:12.730069   11408 main.go:110] libmachine: [stdout =====>] : 172.17.240.254

I0603 07:45:12.730366   11408 main.go:110] libmachine: [stderr =====>] :
I0603 07:45:12.734027   11408 host.go:65] Checking if "multinode" exists ...
I0603 07:45:12.734992   11408 system_pods.go:160] Checking kubelet status ...
I0603 07:45:12.757990   11408 ssh_runner.go:148] Run: systemctl --version
I0603 07:45:12.758988   11408 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM multinode ).state
I0603 07:45:13.320701   11408 main.go:110] libmachine: [stdout =====>] : Running

I0603 07:45:13.320989   11408 main.go:110] libmachine: [stderr =====>] :
I0603 07:45:13.323143   11408 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM multinode ).networkadapters[0]).ipaddresses[0]
I0603 07:45:14.232904   11408 main.go:110] libmachine: [stdout =====>] : 172.17.240.254

I0603 07:45:14.233242   11408 main.go:110] libmachine: [stderr =====>] :
I0603 07:45:14.235328   11408 sshutil.go:44] new ssh client: &{IP:172.17.240.254 Port:22 SSHKeyPath:C:\Users\myuga\.minikube\machines\multinode\id_rsa Username:docker}
I0603 07:45:14.326094   11408 ssh_runner.go:188] Completed: systemctl --version: (1.5671064s)
I0603 07:45:14.368762   11408 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service kubelet
I0603 07:45:14.391370   11408 status.go:232] multinode kubelet status = Stopped
I0603 07:45:14.394383   11408 kubeconfig.go:93] found "multinode" server: "https://172.17.34.251:8443"
I0603 07:45:14.396849   11408 api_server.go:145] Checking apiserver status ...
I0603 07:45:14.439414   11408 ssh_runner.go:148] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0603 07:45:14.495276   11408 api_server.go:149] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: Process exited with status 1
stdout:

stderr:
I0603 07:45:14.497862   11408 status.go:253] multinode apiserver status = Stopped (err=<nil>)
I0603 07:45:14.500240   11408 status.go:126] multinode status: &{Name:multinode Host:Running Kubelet:Stopped APIServer:Stopped Kubeconfig:Configured Worker:false}
multinode
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured
```

**Comment by myugan** [comment]
Output from command `minikube start --nodes 3 -p multinode -v=4 --alsologtostderr`:

```
I0611 17:15:30.385312    3092 start.go:98] hostinfo: {"hostname":"DESKTOP-46H5805","uptime":88067,"bootTime":1591782463,"procs":241,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"3215b3c0-2e44-43a8-9e78-c390616b1672"}
W0611 17:15:30.403848    3092 start.go:106] gopshost.Virtualization returned error: not implemented yet
* [multinode] minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
W0611 17:15:30.485433    3092 start.go:562] selectDriver api.Load: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
I0611 17:15:30.489461    3092 driver.go:253] Setting default libvirt URI to qemu:///system
W0611 17:15:30.493431    3092 start.go:562] selectDriver api.Load: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
I0611 17:15:30.537167    3092 notify.go:125] Checking for updates...
* Using the hyperv driver based on existing profile
I0611 17:15:32.052507    3092 start.go:214] selected driver: hyperv
I0611 17:15:32.053508    3092 start.go:611] validating driver "hyperv" against &{Name:multinode KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2048 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.2 ClusterName:multinode APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubeadm Key:pod-network-cidr Value:10.244.0.0/16}] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:172.17.34.251 Port:8443 KubernetesVersion:v1.18.2 ControlPlane:true Worker:true}] Addons:map[dashboard:false default-storageclass:true efk:false freshpod:false gvisor:false helm-tiller:false ingress:false ingress-dns:false istio:false istio-provisioner:false logviewer:false metallb:false metrics-server:false nvidia-driver-installer:false nvidia-gpu-device-plugin:false registry:false registry-aliases:false registry-creds:false storage-provisioner:true storage-provisioner-gluster:false] VerifyComponents:map[apiserver:true system_pods:true]}
I0611 17:15:32.054507    3092 start.go:617] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
I0611 17:15:32.175368    3092 iso.go:118] acquiring lock: {Name:mk3401866ea2248f50479a4260128f9f8d44b16a Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node multinode in cluster multinode
I0611 17:15:32.235708    3092 preload.go:95] Checking if preload exists for k8s version v1.18.2 and runtime docker
I0611 17:15:32.242122    3092 preload.go:103] Found local preload: C:\Users\myuga\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4
I0611 17:15:32.244127    3092 cache.go:49] Caching tarball of preloaded images
I0611 17:15:32.248129    3092 preload.go:129] Found C:\Users\myuga\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0611 17:15:32.250223    3092 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.2 on docker
I0611 17:15:32.273233    3092 profile.go:156] Saving config to C:\Users\myuga\.minikube\profiles\multinode\config.json ...
I0611 17:15:32.279236    3092 cache.go:152] Successfully downloaded all kic artifacts
I0611 17:15:32.295537    3092 start.go:240] acquiring machines lock for multinode: {Name:mke1b11f161519719a962b5089332deea978dbed Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0611 17:15:32.296539    3092 start.go:244] acquired machines lock for "multinode" in 0s
I0611 17:15:32.305551    3092 start.go:88] Skipping create...Using existing machine configuration
I0611 17:15:32.306242    3092 fix.go:53] fixHost starting:
I0611 17:15:32.328554    3092 fix.go:55] fixHost completed within 2.6886ms
I0611 17:15:32.328554    3092 start.go:75] releasing machines lock for "multinode", held for 31.017ms
! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
I0611 17:15:37.332509    3092 start.go:240] acquiring machines lock for multinode: {Name:mke1b11f161519719a962b5089332deea978dbed Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0611 17:15:37.333509    3092 start.go:244] acquired machines lock for "multinode" in 0s
I0611 17:15:37.344677    3092 start.go:88] Skipping create...Using existing machine configuration
I0611 17:15:37.344677    3092 fix.go:53] fixHost starting:
I0611 17:15:37.346641    3092 fix.go:55] fixHost completed within 1.9637ms
I0611 17:15:37.346641    3092 start.go:75] releasing machines lock for "multinode", held for 11.1308ms
* Failed to start hyperv VM. "minikube start -p multinode" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
I0611 17:15:37.352172    3092 exit.go:58] WithError(error provisioning host)=Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified. called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x19429e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc0008392e0)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc000116780, 0x0, 0x6)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc000116720, 0x6, 0x6, 0x2b6c200, 0xc000116720)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x20, 0xc0002f6d40)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0611 17:15:37.356291    3092 out.go:201] error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "multinode": open C:\Users\myuga\.minikube\machines\multinode\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by sharifelgamal** [comment]
Did you run `minikube delete -p multinode` before rerunning start? It seems like minikube is trying to restart an existing machine with that is in a bad state.

**Comment by medyagh** [comment]
@myugan do you mind retyring with our latest verison of minikube we fixed a few multi node bugs in v1.12.1 ?

**Comment by myugan** [comment]
let me try the latest version first for this issue @medyagh,

**Comment by medyagh** [comment]
@myugan do you still have this issue ?
I have not heard from you.
