### ISSUE TITLE
Minikube IP not found

### ISSUE THREAD

**Issue by andrewrotherham** [kubernetes/minikube#8415]
Hi, I'm trying to start minikube but it says IP address not found, funny because this worked fine yesterday  , please see 
![hyper-v set up](https://user-images.githubusercontent.com/66618878/84044133-11198200-a99f-11ea-9c6d-b5ae2be301a2.PNG)
attachment for screenshot  for how my hyper-v  is set up

1) I did minikube start

C:\Windows\system32>minikube start
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

then I did minikube start --alsologtostderr....and got this

C:\Windows\system32>minikube start --alsologtostderr
I0608 15:39:15.779643   19296 start.go:98] hostinfo: {"hostname":"MDXN00107076","uptime":1928,"bootTime":1591625227,"procs":275,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.18362 Build 18362","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"92fd1166-b33d-4681-8fd8-560d9246b0a6"}
W0608 15:39:15.781652   19296 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
I0608 15:39:15.789643   19296 notify.go:125] Checking for updates...
I0608 15:39:15.795636   19296 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on existing profile
I0608 15:39:16.639473   19296 start.go:214] selected driver: hyperv
I0608 15:39:16.639473   19296 start.go:611] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0608 15:39:16.640472   19296 start.go:617] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0608 15:39:16.642476   19296 iso.go:118] acquiring lock: {Name:mk3705e4d776ea346a47fb458c1949512bb34cfd Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0608 15:39:16.646471   19296 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0608 15:39:16.647471   19296 preload.go:103] Found local preload: C:\Users\andrewanewman2\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0608 15:39:16.647471   19296 cache.go:49] Caching tarball of preloaded images
I0608 15:39:16.648472   19296 preload.go:129] Found C:\Users\andrewanewman2\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0608 15:39:16.651473   19296 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0608 15:39:16.651473   19296 profile.go:156] Saving config to C:\Users\andrewanewman2\.minikube\profiles\minikube\config.json ...
I0608 15:39:16.654474   19296 cache.go:152] Successfully downloaded all kic artifacts
I0608 15:39:16.656472   19296 start.go:240] acquiring machines lock for minikube: {Name:mk1c79511a81187ee95fc73d659f49d4d9230747 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0608 15:39:16.656472   19296 start.go:244] acquired machines lock for "minikube" in 0s
I0608 15:39:16.657470   19296 start.go:88] Skipping create...Using existing machine configuration
I0608 15:39:16.657470   19296 fix.go:53] fixHost starting:
I0608 15:39:16.661475   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0608 15:39:17.846237   19296 main.go:110] libmachine: [stdout =====>] : Running

I0608 15:39:17.846237   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:17.846237   19296 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0608 15:39:17.847236   19296 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0608 15:39:17.853237   19296 machine.go:88] provisioning docker machine ...
I0608 15:39:17.854234   19296 buildroot.go:163] provisioning hostname "minikube"
I0608 15:39:17.855234   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0608 15:39:18.905027   19296 main.go:110] libmachine: [stdout =====>] : Running

I0608 15:39:18.905027   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:18.905027   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0608 15:39:20.165791   19296 main.go:110] libmachine: [stdout =====>] :
I0608 15:39:20.165791   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:20.166780   19296 machine.go:91] provisioned docker machine in 2.3130078s
I0608 15:39:20.166780   19296 fix.go:55] fixHost completed within 3.5099996s
I0608 15:39:20.166780   19296 start.go:75] releasing machines lock for "minikube", held for 3.510998s
! StartHost failed, but will try again: provision: IP not found
I0608 15:39:25.166435   19296 start.go:240] acquiring machines lock for minikube: {Name:mk1c79511a81187ee95fc73d659f49d4d9230747 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0608 15:39:25.166435   19296 start.go:244] acquired machines lock for "minikube" in 0s
I0608 15:39:25.167438   19296 start.go:88] Skipping create...Using existing machine configuration
I0608 15:39:25.167438   19296 fix.go:53] fixHost starting:
I0608 15:39:25.168438   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0608 15:39:26.008281   19296 main.go:110] libmachine: [stdout =====>] : Running

I0608 15:39:26.008281   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:26.008281   19296 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0608 15:39:26.008281   19296 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0608 15:39:26.015283   19296 machine.go:88] provisioning docker machine ...
I0608 15:39:26.015283   19296 buildroot.go:163] provisioning hostname "minikube"
I0608 15:39:26.015283   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0608 15:39:26.825634   19296 main.go:110] libmachine: [stdout =====>] : Running

I0608 15:39:26.825634   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:26.825634   19296 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0608 15:39:27.889579   19296 main.go:110] libmachine: [stdout =====>] :
I0608 15:39:27.889579   19296 main.go:110] libmachine: [stderr =====>] :
I0608 15:39:27.890576   19296 machine.go:91] provisioned docker machine in 1.8756605s
I0608 15:39:27.890576   19296 fix.go:55] fixHost completed within 2.7236719s
I0608 15:39:27.891577   19296 start.go:75] releasing machines lock for "minikube", held for 2.7246734s
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
I0608 15:39:27.897570   19296 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: IP not found called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc0008204c0)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc0001ea740, 0x0, 0x1)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc0001ea730, 0x1, 0x1, 0x2b6c200, 0xc0001ea730)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000109801)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0608 15:39:27.897570   19296 out.go:201] error provisioning host: Failed to start host: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by andrewrotherham** [comment]
![hyper-vset-up2](https://user-images.githubusercontent.com/66618878/84044619-bb91a500-a99f-11ea-95ab-b65f40663e0c.PNG)

**Comment by andrewrotherham** [comment]
Hi, I've found a workaround for this, please https://github.com/kubernetes/minikube/issues/8152...it's Medyagh's comment about using the following commands

minikube delete
minikube start --driver=docker

somehow this has worked, how I couldn't get it working the other way I don't know, but this may be useful for people

**Comment by andrewrotherham** [comment]
hi, follow #8152 from now
