### ISSUE TITLE
minikube start: docker container inspect minikube --format={{.State.Status}}: exit status 1

### ISSUE THREAD

**Issue by aamirashid** [kubernetes/minikube#8498]
docker "minikube" container is missing, will recreate. E0616 10:58:40.471044    3917 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exit status 1

**Comment by priyawadhwa** [comment]
Hey @aamirashid thanks for opening this issue. I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by ArPharazon** [comment]
I had the exact same issue with minikube v1.11.0 - see console messages below:

```
$ minikube start
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing docker container for "minikube" ...
! StartHost failed, but will try again: driver start: expected container state be running but got "Stopped"
* Restarting existing docker container for "minikube" ...
* Failed to start docker container. "minikube start" may fix it: driver start: expected container state be running but got "Stopped"
*
X error provisioning host: Failed to start host: driver start: expected container state be running but got "Stopped"
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

Logs was not very helpful at all:
```
$ minikube logs
* The control plane node must be running for this command
  - To fix this, run: "minikube start"
```

Tried starting minikube with more verbose logging enabled: (it was quite long so only posted the tail end here)
```
$ minikube start --alsologtostderr -v=4
... snipped ...
I0619 11:53:56.520896   26252 start.go:240] acquiring machines lock for minikube: {Name:mka21b03505142c01078f36b2d064dfd9577c151 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0619 11:53:56.520896   26252 start.go:244] acquired machines lock for "minikube" in 0s
I0619 11:53:56.521887   26252 start.go:88] Skipping create...Using existing machine configuration
I0619 11:53:56.521887   26252 fix.go:53] fixHost starting:
I0619 11:53:56.564892   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:53:56.993903   26252 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0619 11:53:56.994898   26252 fix.go:131] unexpected machine state, will restart: <nil>
* Restarting existing docker container for "minikube" ...
I0619 11:53:57.019882   26252 cli_runner.go:108] Run: docker start minikube
I0619 11:53:57.755270   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:53:58.207634   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:53:58.658796   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:53:59.107788   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:53:59.558753   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:00.027748   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:00.498746   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:00.953745   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:01.404764   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:01.874734   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:02.361739   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:02.850729   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:03.362753   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:03.871718   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:04.442821   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:05.009243   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:05.598239   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:06.381281   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:07.326776   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:08.364959   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:09.827260   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:11.995626   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:14.320137   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:17.708028   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:25.375275   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:33.073999   26252 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0619 11:54:33.492086   26252 fix.go:55] fixHost completed within 36.9704832s
I0619 11:54:33.492996   26252 start.go:75] releasing machines lock for "minikube", held for 36.971394s
* Failed to start docker container. "minikube start" may fix it: driver start: expected container state be running but got "Stopped"
I0619 11:54:33.495018   26252 exit.go:58] WithError(error provisioning host)=Failed to start host: driver start: expected container state be running but got "Stopped" called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc0004746a0)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc00011ca80, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc00011ca60, 0x2, 0x2, 0x2b6c200, 0xc00011ca60)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x20, 0xc000474a80)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0619 11:54:33.502997   26252 out.go:201] error provisioning host: Failed to start host: driver start: expected container state be running but got "Stopped"
*
X error provisioning host: Failed to start host: driver start: expected container state be running but got "Stopped"
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

Other things that I tried:
- minikube delete
- deleting the .minikube folder 
- rolled back to minikube v1.10.1 , but it had the same problems
- rolled back to minikube v1.9.2, and now it works again.

**Comment by priyawadhwa** [comment]
Hey @ArPharazon would you mind trying with our latest version (v1.12) and letting us know if this is fixed for you?

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by y455in** [comment]
Issue still persists. Fails with the following error
`stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil
I0807 13:26:46.556806   33810 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
W0807 13:26:46.653591   33810 cli_runner.go:148] docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube returned with exit code 1
I0807 13:26:46.653726   33810 retry.go:31] will retry after 300.341948ms: new client: new client: Error creating new ssh host from driver: Error getting ssh port for driver: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1`.

Latest version of minikube, latest version of Docker Desktop. Any suggestions how to resolve this?
