### ISSUE TITLE
while start minikube i am facing that problem what should i do ???

### ISSUE THREAD

**Issue by Umar-Basharat103** [kubernetes/minikube#8568]
~$ sudo minikube start 
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.4 LTS

❌  [NONE_DOCKER_EXIT_5] Failed to enable container runtime sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.

💡  Suggestion: Ensure that Docker is installed and healthy: Run 'sudo systemctl start docker' and 'journalctl -u docker'. Alternatively, select another value for --driver
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/5532

**Comment by prasadkatti** [comment]
If you are using the **_none_** driver, then you should make that **_docker_** is installed. https://minikube.sigs.k8s.io/docs/drivers/none/#requirements

**Comment by shayanjalil** [comment]
I'm following [this](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-updating-the-host) blog to get Minikube up and running on Windows + WSL.

Now my understanding is that when using Docker for Windows with WSL, WSL uses the docker backend installed on Windows and you do not need to install dokcer on Linux.

But when I try to run Minikube I get

```
shayan@DESKTOP-H4QPUDT:/usr/local/bin$ sudo minikube start --driver=none
😄  minikube v1.12.1 on Ubuntu 20.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04 LTS

❌  [NONE_DOCKER_EXIT_5] Failed to enable container runtime sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.

💡  Suggestion: Ensure that Docker is installed and healthy: Run 'sudo systemctl start docker' and 'journalctl -u docker'. Alternatively, select another value for --driver
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/5532
shayan@DESKTOP-H4QPUDT:/usr/local/bin$
```

Detailed output:

```
/usr/local/bin$ sudo minikube start --alsologtostderr -v=4 --driver=none
I0720 17:02:54.204000    2066 out.go:170] Setting JSON to false
I0720 17:02:54.204497    2066 start.go:101] hostinfo: {"hostname":"DESKTOP-H4QPUDT","uptime":2117,"bootTime":1595244457,"procs":81,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"4.19.104-microsoft-standard","virtualizationSystem":"","virtualizationRole":"","hostid":"2fd590ee-1f8f-0159-773a-3c735f104aeb"}
I0720 17:02:54.204701    2066 start.go:111] virtualization:
😄  minikube v1.12.1 on Ubuntu 20.04
I0720 17:02:54.211099    2066 exec_runner.go:49] Run: systemctl --version
I0720 17:02:54.212065    2066 driver.go:257] Setting default libvirt URI to qemu:///system
✨  Using the none driver based on existing profile
I0720 17:02:54.214367    2066 start.go:217] selected driver: none
I0720 17:02:54.214389    2066 start.go:621] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.238.8 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0720 17:02:54.214447    2066 start.go:632] status for none: {Installed:true Healthy:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0720 17:02:54.214484    2066 start.go:1003] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0720 17:02:54.214562    2066 start_flags.go:340] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.238.8 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
👍  Starting control plane node minikube in cluster minikube
I0720 17:02:54.216855    2066 profile.go:150] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0720 17:02:54.216968    2066 cache.go:178] Successfully downloaded all kic artifacts
I0720 17:02:54.217005    2066 start.go:241] acquiring machines lock for minikube: {Name:mka00e65579c2b557a802898fd1cf03ec4ab30a1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0720 17:02:54.217277    2066 start.go:245] acquired machines lock for "minikube" in 248.399µs
I0720 17:02:54.217290    2066 start.go:89] Skipping create...Using existing machine configuration
I0720 17:02:54.217295    2066 fix.go:53] fixHost starting: m01
W0720 17:02:54.217429    2066 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0720 17:02:54.217513    2066 api_server.go:146] Checking apiserver status ...
I0720 17:02:54.217529    2066 exec_runner.go:49] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0720 17:02:54.225475    2066 api_server.go:150] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0720 17:02:54.225510    2066 system_pods.go:161] Checking kubelet status ...
I0720 17:02:54.225544    2066 exec_runner.go:49] Run: sudo systemctl is-active --quiet service kubelet
I0720 17:02:54.231052    2066 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0720 17:02:54.231085    2066 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing none bare metal machine for "minikube" ...
I0720 17:02:54.237074    2066 profile.go:150] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0720 17:02:54.237176    2066 start.go:204] post-start starting for "minikube" (driver="none")
I0720 17:02:54.237207    2066 start.go:214] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0720 17:02:54.237271    2066 exec_runner.go:49] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0720 17:02:54.241662    2066 main.go:115] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0720 17:02:54.241701    2066 main.go:115] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0720 17:02:54.241726    2066 main.go:115] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
ℹ️  OS release is Ubuntu 20.04 LTS
I0720 17:02:54.245515    2066 filesync.go:118] Scanning /root/.minikube/addons for local assets ...
I0720 17:02:54.245565    2066 filesync.go:118] Scanning /root/.minikube/files for local assets ...
I0720 17:02:54.245608    2066 start.go:207] post-start completed in 8.397693ms
I0720 17:02:54.245637    2066 fix.go:92] none is local, skipping auth/time setup (requires ssh)
I0720 17:02:54.245658    2066 fix.go:55] fixHost completed within 28.361376ms
I0720 17:02:54.245676    2066 start.go:76] releasing machines lock for "minikube", held for 28.388476ms
I0720 17:02:54.245878    2066 exec_runner.go:49] Run: sudo systemctl is-active --quiet service containerd
I0720 17:02:54.245978    2066 exec_runner.go:49] Run: curl -sS -m 2 https://k8s.gcr.io/
I0720 17:02:54.251113    2066 exec_runner.go:49] Run: sudo systemctl daemon-reload
I0720 17:02:54.356633    2066 exec_runner.go:49] Run: sudo systemctl start docker
I0720 17:02:54.362393    2066 exit.go:58] WithError(Failed to enable container runtime)=sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.
 called from:
goroutine 1 [running]:
runtime/debug.Stack(0x1b8febe, 0x9, 0x1b893b6)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x1bbe107, 0x22, 0x1eb6e80, 0xc0003ca0d0)
        /app/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/pkg/minikube/node.configureRuntimes(0x7fe2a1d9d588, 0x2cff560, 0xc0008cbf08, 0x8, 0x0, 0x0, 0x0, 0xc0008fe000, 0x6b, 0x898, ...)
        /app/pkg/minikube/node/start.go:275 +0x24e
k8s.io/minikube/pkg/minikube/node.Start(0x1ef59a0, 0x2cff560, 0x1, 0x1f180c0, 0xc0005cb740, 0xc0008bef00, 0xc00066f180, 0xc0005cb540, 0xc0009122a0, 0xc0005cb701, ...)
        /app/pkg/minikube/node/start.go:91 +0x1a1
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1ef59a0, 0x2cff560, 0x1, 0x1f180c0, 0xc0005cb740, 0xc0008bef00, 0xc00066f180, 0xc0005cb540, 0xc0009122a0, 0xc000101880, ...)
        /app/cmd/minikube/cmd/start.go:283 +0x7c
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2cb86a0, 0xc0008a0300, 0x0, 0x3)
        /app/cmd/minikube/cmd/start.go:203 +0x3bf
github.com/spf13/cobra.(*Command).execute(0x2cb86a0, 0xc0008a02d0, 0x3, 0x3, 0x2cb86a0, 0xc0008a02d0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x2cb76e0, 0x0, 0x1, 0xc0005c2b20)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
        /app/cmd/minikube/main.go:71 +0x11f

❌  [NONE_DOCKER_EXIT_5] Failed to enable container runtime sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.

💡  Suggestion: Ensure that Docker is installed and healthy: Run 'sudo systemctl start docker' and 'journalctl -u docker'. Alternatively, select another value for --driver
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/5532
shayan@DESKTOP-H4QPUDT:/usr/local/bin$ minikube start --alsologtostderr -v=4
```

**Comment by wimsikal** [comment]
You need to install docker on Ubuntu.

`
sudo apt-get update

sudo apt-get install \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"

sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io

# if prompted about grub during install, select all drives and then select yes when the message pops up again

sudo docker run hello-world
`

**Comment by priyawadhwa** [comment]
Hey @shayanjalil the  `none` driver is only compatible with Linux. I'd suggest running Windows with the docker drivre via:

```
minikube start --driver docker
```
if you have docker installed.

**Comment by priyawadhwa** [comment]
@Umar-Basharat103 similarly, I'd recommend using docker on ubuntu as well as it's more reliable. Do you have docker installed?

**Comment by shayanjalil** [comment]
@priyawadhwa in my comment I mentioned that I'm following [this](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-updating-the-host) blog to get minikube up and running inside a Linux environment using WSL on Windows. This blog doesn't ask to install docker in Linux. It says that WSL will use the Windows installation for docker.

**Comment by a-dyakov-mercuryo** [comment]
Im trying start minikube by this article  [WSL+Docker: Kubernetes on the Windows Desktop](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-kubernetes-from-everywhere) and get same error

**Comment by prasadkatti** [comment]
You are using the `none` driver. Do you have docker installed?

**Comment by a-dyakov-mercuryo** [comment]
@prasadkatti docker installed only on host machine. On WSL2 machine, for example `docker <command>` works fine, but there is no docker service

**Comment by raimundogomes** [comment]
I have the same problem with I try install minikube in (WSL+Docker + Kubernetes on the Windows Desktop)

Installation instructions:
[wsl-docker-kubernetes-on-the-windows-desktop](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-kubernetes-from-everywhere)

Error message:
`/usr/local/bin$ sudo minikube start --driver=none
😄  minikube v1.12.3 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.4 LTS

E0830 19:58:47.631488     876 exit.go:76] &{ID:NONE_DOCKER_EXIT_5 Err:sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.
 Advice:Ensure that Docker is installed and healthy: Run 'sudo systemctl start docker' and 'journalctl -u docker'. Alternatively, select another value for --driver URL:https://minikube.sigs.k8s.io/docs/reference/drivers/none Issues:[5532] ShowIssueLink:false}
❌  [NONE_DOCKER_EXIT_5] Failed to enable container runtime sudo systemctl start docker: exit status 5
stdout:

stderr:
Failed to start docker.service: Unit docker.service not found.

💡  Suggestion: Ensure that Docker is installed and healthy: Run 'sudo systemctl start docker' and 'journalctl -u docker'. Alternatively, select another value for --driver
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/5532`

**When comand with systemctl**
`:/usr/local/bin$ sudo systemctl start docker
Failed to start docker.service: Unit docker.service not found.`

Apparently the problem is how the "systemctl" command is mapping the docker service.  **docker is working normally.**
But the docker folders are in locations other than the default:
`/mnt/wsl$ ls
docker-desktop  docker-desktop-bind-mounts  docker-desktop-data`

**Comment by avinashs24** [comment]
Same issue here. I'm following this [blog ](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/). I have Docker for windows with WSL Integration enabled. With this, there is no need to install docker locally in the WSL. I'm able to use docker in my Ubuntu WSL straightaway after enabling it in Docker for windows.
However when setting kubernetes minkube, after the Systemd step when we start minikube, it fails with the error - 
`Failed to restart docker.service: Unit docker.service not found.`

**Comment by Grompot77** [comment]
I have been following the same [blog ](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/) post, even did a brand new ubuntu instance with wsl2, not the store one, same problem.  Even tried to use minikube v1.10.1 which is around the same period when the blog post was done.  Then tried to run it with root, still no luck.  Hopefully Nuno can come to us on how he got it to work with Docker Desktop for windows. 

Please note that we are trying to follow [https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/), this article is very specific and it does not require the docker driver to be installed on the ubuntu distro.

**Comment by shayanjalil** [comment]
Has anyone found a solution to this so far? I'm still stuck 😞

**Comment by KamranShahid** [comment]
Same problem
Have windows 10, docker, WSL2. Following same article [(https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/)]
docker with WSL2 is working fine and i have run some other container with it successfully
here i have used above article correctly till the minikube dashboard command.
Please let me know what to do

![image](https://user-images.githubusercontent.com/2170442/100426489-c3124b00-30b2-11eb-91cb-1aa7396c5aa0.png)

**Comment by medyagh** [comment]
I suggest this blog post https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-updating-the-host

 to be updated to use docker driver, 
anyone like to take this issue and update the kuberentes docs to use docker driver instead of none ? 

@KamranShahid 
@prasadkatti 
@idvoretskyi

**Comment by medyagh** [comment]
if anyone likes to take this issue, please reffer to this issue on the kuberetnes website 
https://github.com/kubernetes/website/issues/26998

**Comment by afbjorklund** [comment]
Using the "none" driver has been the standard in katacoda for years, and works fine - _unless_ you want to use multinode.

The original warnings (above) are just because WSL didn't support systemd at the time, and the code looked for it (wrong).
