### ISSUE TITLE
minikube update-context panic

### ISSUE THREAD

**Issue by MarlonGamez** [kubernetes/minikube#9100]
Possibly related to #9089 (?)

I currently don't have a minikube context in my kube config. When trying to run `minikube start`, I run into the problem in #9089. 

When running `minikube update-context`, I run into this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x523891f]

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x57bad36, 0x8, 0x57bb784, 0x9, 0x8000, 0xc0000437a0, 0x1f, 0x5b32f40, 0xc0002783a0, 0x57bb784)
	/private/tmp/minikube-20200812-94589-17snemo/pkg/minikube/kubeconfig/kubeconfig.go:143 +0x2af
k8s.io/minikube/cmd/minikube/cmd.glob..func31(0x6927200, 0x696cf80, 0x0, 0x0)
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/update-context.go:37 +0x10a
github.com/spf13/cobra.(*Command).execute(0x6927200, 0x696cf80, 0x0, 0x0, 0x6927200, 0x696cf80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x6925280, 0x0, 0x1, 0xc00079cb00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/main.go:71 +0x11f
```

And when running with the `--alsologtostderr` flag:
```
I0826 11:58:22.909124   73366 mustload.go:64] Loading cluster: minikube
I0826 11:58:22.910152   73366 cli_runner.go:109] Run: docker container inspect minikube --format={{.State.Status}}
I0826 11:58:22.958498   73366 host.go:65] Checking if "minikube" exists ...
I0826 11:58:22.959063   73366 cli_runner.go:109] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0826 11:58:23.010032   73366 kubeconfig.go:117] verify returned: extract IP: "minikube" does not appear in /Users/marlongamez/.kube/config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x523891f]

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x57bad36, 0x8, 0x57bb784, 0x9, 0x8000, 0xc000137520, 0x1f, 0x5b32f40, 0xc0005dc3a0, 0x57bb784)
	/private/tmp/minikube-20200812-94589-17snemo/pkg/minikube/kubeconfig/kubeconfig.go:143 +0x2af
k8s.io/minikube/cmd/minikube/cmd.glob..func31(0x6927200, 0xc000b30ce0, 0x0, 0x1)
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/update-context.go:37 +0x10a
github.com/spf13/cobra.(*Command).execute(0x6927200, 0xc000b30cd0, 0x1, 0x1, 0x6927200, 0xc000b30cd0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x6925280, 0x0, 0x1, 0xc0007d2b00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/main.go:71 +0x11f
```

**Comment by tstromberg** [comment]
This should be fixed at head - do you mind testing with the binary I had you download?

**Comment by medyagh** [comment]
yes we merged a Pr to fix this. this shoudl be fixed on HEAD @MarlonGamez 

/triage needs-information
/triage support
