### ISSUE TITLE
none driver: TestOffline/group/docker "panic: reflect: indirection through nil pointer to embedded struct "

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9744]
```
	W1119 20:04:46.520507    9260 out.go:146] X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
	stdout:
	
	stderr:
	panic: reflect: indirection through nil pointer to embedded struct [recovered]
		panic: reflect: indirection through nil pointer to embedded struct
```

as seen here 
https://storage.googleapis.com/minikube-builds/logs/9742/c237d5d/none_Linux.html#fail_TestOffline%2fgroup%2fdocker

this ran on Debian Agent 4 (kvm kic-docker docker) https://storage.googleapis.com/minikube-builds/logs/9742/none_Linux.txt

**Comment by medyagh** [comment]
I sshed to Debian Agent 4 and I ran the command myself

```
jenkins@debian-jenkins-agent-4:/home/medya$ docker info --format {{.CgroupDriver}}
cgroupfs

```

and it worked

**Comment by ilya-zuyev** [comment]
```
stderr:
	panic: reflect: indirection through nil pointer to embedded struct [recovered]
		panic: reflect: indirection through nil pointer to embedded struct
	
	goroutine 1 [running]:
	text/template.errRecover(0xc000563320)
		/usr/local/go/src/text/template/exec.go:170 +0x1b5
	panic(0x55fc322c0de0, 0x55fc32617480)
		/usr/local/go/src/runtime/panic.go:679 +0x1b6
	reflect.Value.FieldByIndex(0x55fc324a5c40, 0xc00004e400, 0x99, 0xc000422050, 0x2, 0x2, 0x0, 0x55fc326d4220, 0x55fc322c0de0)
		/usr/local/go/src/reflect/value.go:883 +0x39e
	text/template.(*state).evalField(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0x7ffd4bd1e514, 0xc, 0x55fc326a31e0, 0xc0005d0180, 0xc0005d4070, 0x1, ...)
		/usr/local/go/src/text/template/exec.go:605 +0x475
	text/template.(*state).evalFieldChain(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0x55fc324a5c40, 0xc00004e400, 0x99, 0x55fc326a31e0, 0xc0005d0180, 0xc0005d4060, ...)
		/usr/local/go/src/text/template/exec.go:558 +0x222
	text/template.(*state).evalFieldNode(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0xc0005d0180, 0xc0005d4070, 0x1, 0x1, 0x55fc32374560, 0x55fc335b9e78, ...)
		/usr/local/go/src/text/template/exec.go:522 +0x115
	text/template.(*state).evalCommand(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0xc0005d0150, 0x55fc32374560, 0x55fc335b9e78, 0x99, 0xd0, 0x55fc3247d980, ...)
		/usr/local/go/src/text/template/exec.go:460 +0x79c
	text/template.(*state).evalPipeline(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0xc00025e0c0, 0xc0005d8038, 0xc0005da0d0, 0xc000563158)
		/usr/local/go/src/text/template/exec.go:434 +0x11c
	text/template.(*state).walk(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0x55fc326a3060, 0xc0005d01b0)
		/usr/local/go/src/text/template/exec.go:258 +0x49d
	text/template.(*state).walk(0xc0005632a0, 0x55fc324a5c40, 0xc00004e400, 0x99, 0x55fc326a32a0, 0xc0005d0120)
		/usr/local/go/src/text/template/exec.go:266 +0x144
	text/template.(*Template).execute(0xc00004e380, 0x55fc3263aca0, 0xc00057fd40, 0x55fc324a5c40, 0xc00004e400, 0x0, 0x0)
		/usr/local/go/src/text/template/exec.go:221 +0x20c
	text/template.(*Template).Execute(...)
		/usr/local/go/src/text/template/exec.go:204
	github.com/docker/cli/cli/command/system.formatInfo(0x55fc326cf0e0, 0xc0003f21c0, 0x0, 0xc00058a150, 0x1, 0x1, 0xc00034c140, 0x0, 0x0, 0x0, ...)
		/go/src/github.com/docker/cli/cli/command/system/info.go:478 +0x1f5
	github.com/docker/cli/cli/command/system.runInfo(0xc0004f0f00, 0x55fc326cf0e0, 0xc0003f21c0, 0xc00045c7f0, 0x0, 0x0)
		/go/src/github.com/docker/cli/cli/command/system/info.go:85 +0x343
	github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc0004f0f00, 0xc000256080, 0x0, 0x2, 0x0, 0x0)
		/go/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
	github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004f0f00, 0xc000505120, 0x2, 0x2, 0xc0004f0f00, 0xc000505120)
		/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x462
	github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000466f00, 0xc000505110, 0x3, 0x3)
		/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
	github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
		/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
	main.runDocker(0xc0003f21c0, 0x55fc3263d1c0, 0xc0000e8010)
		/go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d3
	main.main()
		/go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3
```

**Comment by priyawadhwa** [comment]
Looks like this is working on none driver now, so I'm going to close this issue:

```
$ /home/tstromberg/bin/passrate.sh TestOffline/group/docker
-------------------------------------------------
docker_Linux      | 2020-11-26 | 100% | 19 of 19
docker_Linux      | 2020-11-27 | 100% | 23 of 23
docker_Linux      | 2020-11-28 |  91% | 21 of 23
docker_Linux      | 2020-11-29 | 100% | 22 of 22
docker_Linux      | 2020-11-30 |  82% | 9 of 11
-------------------------------------------------
Hyper-V_Windows   | 2020-11-27 |   0% | 0 of 1
-------------------------------------------------
KVM_Linux         | 2020-11-26 | 100% | 18 of 18
KVM_Linux         | 2020-11-27 | 100% | 22 of 22
KVM_Linux         | 2020-11-28 | 100% | 22 of 22
KVM_Linux         | 2020-11-29 | 100% | 21 of 21
KVM_Linux         | 2020-11-30 | 100% | 12 of 12
-------------------------------------------------
none_Linux        | 2020-11-26 | 100% | 19 of 19
none_Linux        | 2020-11-27 | 100% | 23 of 23
none_Linux        | 2020-11-28 | 100% | 23 of 23
none_Linux        | 2020-11-29 | 100% | 23 of 23
none_Linux        | 2020-11-30 | 100% | 11 of 11
-------------------------------------------------
VirtualBox_Linux  | 2020-11-26 | 100% | 5 of 5
VirtualBox_Linux  | 2020-11-27 |  91% | 20 of 22
VirtualBox_Linux  | 2020-11-28 |  95% | 20 of 21
VirtualBox_Linux  | 2020-11-29 | 100% | 21 of 21
VirtualBox_Linux  | 2020-11-30 | 100% | 10 of 10
-------------------------------------------------
VirtualBox_macOS  | 2020-11-26 | 100% | 3 of 3
VirtualBox_macOS  | 2020-11-27 | 100% | 1 of 1
VirtualBox_macOS  | 2020-11-28 | 100% | 10 of 10
VirtualBox_macOS  | 2020-11-29 | 100% | 10 of 10
VirtualBox_macOS  | 2020-11-30 | 100% | 6 of 6
-------------------------------------------------
z__ALL__          | 2020-11-26 | 100% | 64 of 64
z__ALL__          | 2020-11-27 |  97% | 89 of 92
z__ALL__          | 2020-11-28 |  97% | 96 of 99
z__ALL__          | 2020-11-29 | 100% | 97 of 97
z__ALL__          | 2020-11-30 |  96% | 48 of 50
-------------------------------------------------
```

**Comment by Raiyan444** [comment]
Added current user to docker group fixed the issue.
